# [실습] Pandas 데이터 처리하기

## 학습목표
- Pandas DataFrame을 생성하고 조작할 수 있다
- CSV, JSON 파일을 읽고 쓸 수 있다
- 데이터를 필터링, 정렬, 그룹화할 수 있다
- 텍스트 데이터를 분석하고 통계를 추출할 수 있다

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\noto\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\noto\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\noto\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Pandas 기초

Pandas는 데이터 분석을 위한 파이썬의 핵심 라이브러리입니다.  
특히 텍스트 데이터 전처리와 분석에 매우 유용합니다.

In [20]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 기본 DataFrame 생성
data = {
    'name': ['김철수', '이영희', '박민수', '정수진', '최동현'],
    'department': ['AI개발팀', '데이터팀', 'AI개발팀', '데이터팀', 'AI개발팀'],
    'experience': [3, 5, 2, 7, 4],
    'skills': ['Python, ML', 'Python, SQL', 'Java, Python', 'R, Python', 'Python, DL']
}

df = pd.DataFrame(data)
print("=== 직원 데이터 ===")
print(df)
print(f"\n데이터 형태: {df.shape}")
print(f"컬럼: {df.columns.tolist()}")

=== 직원 데이터 ===
  name department  experience        skills
0  김철수      AI개발팀           3    Python, ML
1  이영희       데이터팀           5   Python, SQL
2  박민수      AI개발팀           2  Java, Python
3  정수진       데이터팀           7     R, Python
4  최동현      AI개발팀           4    Python, DL

데이터 형태: (5, 4)
컬럼: ['name', 'department', 'experience', 'skills']

In [2]:
df

  name department  experience        skills
0  김철수      AI개발팀           3    Python, ML
1  이영희       데이터팀           5   Python, SQL
2  박민수      AI개발팀           2  Java, Python
3  정수진       데이터팀           7     R, Python
4  최동현      AI개발팀           4    Python, DL

In [3]:
# 데이터 타입과 기본 정보
print("=== 데이터 정보 ===")
print(df.info())
print("\n=== 통계 요약 ===")
print(df.describe())
print("\n=== 데이터 타입 ===")
print(df.dtypes)

=== 데이터 정보 ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   department  5 non-null      object
 2   experience  5 non-null      int64
 3   skills      5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes
None

=== 통계 요약 ===
       experience
count    5.000000
mean     4.200000
std      1.923538
min      2.000000
25%      3.000000
50%      4.000000
75%      5.000000
max      7.000000

=== 데이터 타입 ===
name          object
department    object
experience     int64
skills        object
dtype: object

## 데이터 로드 및 저장

실제 데이터 파일을 읽고 쓰는 방법을 알아보겠습니다.

In [6]:
# JSON 데이터 읽기
import json

# 샘플 뉴스 데이터 로드
try:
    with open('news_data.json', 'r', encoding='utf-8') as f:
        news_data = json.load(f)
    
    news_df = pd.DataFrame(news_data)
    print("=== 뉴스 데이터 로드 성공 ===")
    print(f"총 {len(news_df)}개 기사")
    print("\n첫 3개 기사:")
    print(news_df.head(3))
except FileNotFoundError:
    print("파일이 없어 샘플 데이터를 생성합니다...")
    # 샘플 데이터 생성
    news_df = pd.DataFrame({
        'title': [
            'AI 기술 발전으로 업무 자동화 가속화',
            '파이썬, 가장 인기 있는 프로그래밍 언어 1위',
            '머신러닝 엔지니어 수요 급증'
        ],
        'category': ['기술', '개발', '채용'],
        'date': ['2025-01-15', '2025-01-16', '2025-01-17'],
        'views': [1500, 2300, 1800]
    })
    print(news_df)

=== 뉴스 데이터 로드 성공 ===
총 15개 기사

첫 3개 기사:
                              title category        date  views  \
0  OpenAI, GPT-5 개발 본격화... 연내 출시 예정       AI  2024-01-15   5234
1            삼성전자, AI 반도체 시장 공략 가속화       기업  2024-01-16   3421
2         Python 3.13 출시, 성능 30% 향상       개발  2024-01-17   4123

                                             content author  \
0  OpenAI가 차세대 언어모델 GPT-5 개발을 본격화했다. 기존 모델 대비 추론 ...    김기자
1  삼성전자가 AI 가속기 시장 진출을 선언했다. HBM3E 메모리와 함께 AI 칩 개...    이기자
2  Python 3.13 버전이 공식 출시됐다. JIT 컴파일러 도입으로 실행 속도가 ...    박기자

                        tags
0     [AI, GPT, OpenAI, LLM]
1         [삼성, 반도체, AI, HBM]
2  [Python, 프로그래밍, 개발, 오픈소스]

In [7]:
news_df.head()

,title,category,date,views,content,author,tags
0,"OpenAI, GPT-5 개발 본격화... 연내 출시 예정",AI,2024-01-15,5234,OpenAI가 차세대 언어모델 GPT-5 개발을 본격화했다. 기존 모델 대비 추론 ...,김기자,"[AI, GPT, OpenAI, LLM]"
1,"삼성전자, AI 반도체 시장 공략 가속화",기업,2024-01-16,3421,삼성전자가 AI 가속기 시장 진출을 선언했다. HBM3E 메모리와 함께 AI 칩 개...,이기자,"[삼성, 반도체, AI, HBM]"
2,"Python 3.13 출시, 성능 30% 향상",개발,2024-01-17,4123,Python 3.13 버전이 공식 출시됐다. JIT 컴파일러 도입으로 실행 속도가 ...,박기자,"[Python, 프로그래밍, 개발, 오픈소스]"
3,"네이버, 하이퍼클로바X 기업 서비스 확대",AI,2024-01-18,2987,"네이버가 하이퍼클로바X를 활용한 B2B 서비스를 확대한다. 금융, 유통 분야 특화 ...",정기자,"[네이버, 하이퍼클로바, AI, LLM, B2B]"
4,머신러닝 엔지니어 평균 연봉 1.2억원 돌파,채용,2024-01-19,7654,국내 머신러닝 엔지니어의 평균 연봉이 처음으로 1.2억원을 넘어섰다. AI 인재 쟁...,최기자,"[채용, 연봉, 머신러닝, AI, 개발자]"

## 데이터 선택과 필터링

DataFrame에서 원하는 데이터를 선택하고 필터링하는 방법을 알아보겠습니다.

In [9]:
# 컬럼 선택
print("=== 특정 컬럼 선택 ===")
print(df['name'])
print("\n=== 여러 컬럼 선택 ===")
print(df[['name', 'department']])

# 인덱스로 선택
print("\n=== iloc으로 행 선택 ===")
print(df.iloc[0])  # 첫 번째 행
print("\n=== 슬라이싱 ===")
print(df.iloc[1:3])  # 두 번째부터 세 번째 행

=== 특정 컬럼 선택 ===
0    김철수
1    이영희
2    박민수
3    정수진
4    최동현
Name: name, dtype: object

=== 여러 컬럼 선택 ===
  name department
0  김철수      AI개발팀
1  이영희       데이터팀
2  박민수      AI개발팀
3  정수진       데이터팀
4  최동현      AI개발팀

=== iloc으로 행 선택 ===
name                 김철수
department         AI개발팀
experience             3
skills        Python, ML
Name: 0, dtype: object

=== 슬라이싱 ===
  name department  experience        skills
1  이영희       데이터팀           5   Python, SQL
2  박민수      AI개발팀           2  Java, Python

In [10]:
df

  name department  experience        skills
0  김철수      AI개발팀           3    Python, ML
1  이영희       데이터팀           5   Python, SQL
2  박민수      AI개발팀           2  Java, Python
3  정수진       데이터팀           7     R, Python
4  최동현      AI개발팀           4    Python, DL

In [17]:
df[(df['department'] == 'AI개발팀') & (df['experience'] >= 3)]

  name department  experience      skills
0  김철수      AI개발팀           3  Python, ML
4  최동현      AI개발팀           4  Python, DL

In [18]:
# 조건 필터링
print("=== 경력 3년 이상 직원 ===")
experienced = df[df['experience'] >= 3]
print(experienced)

print("\n=== AI개발팀 직원 ===")
ai_team = df[df['department'] == 'AI개발팀']
print(ai_team)

# 복합 조건
print("\n=== AI개발팀이면서 경력 3년 이상 ===")
filtered = df[(df['department'] == 'AI개발팀') & (df['experience'] >= 3)]
print(filtered)

=== 경력 3년 이상 직원 ===
  name department  experience       skills
0  김철수      AI개발팀           3   Python, ML
1  이영희       데이터팀           5  Python, SQL
3  정수진       데이터팀           7    R, Python
4  최동현      AI개발팀           4   Python, DL

=== AI개발팀 직원 ===
  name department  experience        skills
0  김철수      AI개발팀           3    Python, ML
2  박민수      AI개발팀           2  Java, Python
4  최동현      AI개발팀           4    Python, DL

=== AI개발팀이면서 경력 3년 이상 ===
  name department  experience      skills
0  김철수      AI개발팀           3  Python, ML
4  최동현      AI개발팀           4  Python, DL

## 데이터 변환과 처리

데이터를 변환하고 새로운 컬럼을 생성하는 방법을 배워보겠습니다.

In [21]:
df

  name department  experience        skills
0  김철수      AI개발팀           3    Python, ML
1  이영희       데이터팀           5   Python, SQL
2  박민수      AI개발팀           2  Java, Python
3  정수진       데이터팀           7     R, Python
4  최동현      AI개발팀           4    Python, DL

In [27]:
# 새로운 컬럼 추가
df['level'] = df['experience'].apply(lambda x: '시니어' if x >= 5 else ('주니어' if x < 3 else '미드'))
df['has_python'] = df['skills'].str.contains('Python')
df['has_DL'] = df['skills'].str.contains('DL')

print("=== 레벨과 Python 스킬 추가 ===")
print(df)

# 스킬 개수 계산
df['skill_count'] = df['skills'].str.split(',').str.len()
print("\n=== 스킬 개수 추가 ===")
print(df[['name', 'skills', 'skill_count']])
df[['name', 'skills', 'skill_count']]

=== 레벨과 Python 스킬 추가 ===
  name department  experience        skills level  has_python  has_DL  \
0  김철수      AI개발팀           3    Python, ML    미드        True   False
1  이영희       데이터팀           5   Python, SQL   시니어        True   False
2  박민수      AI개발팀           2  Java, Python   주니어        True   False
3  정수진       데이터팀           7     R, Python   시니어        True   False
4  최동현      AI개발팀           4    Python, DL    미드        True    True

   skill_count
0            2
1            2
2            2
3            2
4            2

=== 스킬 개수 추가 ===
  name        skills  skill_count
0  김철수    Python, ML            2
1  이영희   Python, SQL            2
2  박민수  Java, Python            2
3  정수진     R, Python            2
4  최동현    Python, DL            2

  name        skills  skill_count
0  김철수    Python, ML            2
1  이영희   Python, SQL            2
2  박민수  Java, Python            2
3  정수진     R, Python            2
4  최동현    Python, DL            2

In [30]:
# 문자열 처리
df['skills_lower'] = df['skills'].str.lower()
df['skills_list'] = df['skills'].str.split(', ')

print("=== 문자열 처리 결과 ===")
for idx, row in df.iterrows():
    print(f"{row['name']}: {row['skills_list']}")

=== 문자열 처리 결과 ===
김철수: ['Python', 'ML']
이영희: ['Python', 'SQL']
박민수: ['Java', 'Python']
정수진: ['R', 'Python']
최동현: ['Python', 'DL']

## 그룹화와 집계

데이터를 그룹화하고 통계를 계산하는 방법을 알아보겠습니다.

In [31]:
df

,name,department,experience,skills,level,has_python,has_DL,skill_count,skills_lower,skills_list
0,김철수,AI개발팀,3,"Python, ML",미드,True,False,2,"python, ml","[Python, ML]"
1,이영희,데이터팀,5,"Python, SQL",시니어,True,False,2,"python, sql","[Python, SQL]"
2,박민수,AI개발팀,2,"Java, Python",주니어,True,False,2,"java, python","[Java, Python]"
3,정수진,데이터팀,7,"R, Python",시니어,True,False,2,"r, python","[R, Python]"
4,최동현,AI개발팀,4,"Python, DL",미드,True,True,2,"python, dl","[Python, DL]"

In [ ]:
# 부서별 통계
dept_stats = df.groupby('department').agg({
    'experience': ['mean', 'max', 'min'],
    'name': 'count',
    'skill_count': 'mean'
})

print("=== 부서별 통계 ===")


# 레벨별 분포
level_dist = df['level'].value_counts()
print("\n=== 레벨별 인원 분포 ===")
print(level_dist)

=== 부서별 통계 ===

=== 레벨별 인원 분포 ===
level
미드     2
시니어    2
주니어    1
Name: count, dtype: int64

## 텍스트 데이터 분석 실습

실제 텍스트 데이터를 분석하는 종합 실습을 진행하겠습니다.

In [ ]:
# 댓글 데이터 생성
comments_data = {
    'comment_id': range(1, 11),
    'user': ['user1', 'user2', 'user3', 'user4', 'user5', 
             'user1', 'user2', 'user6', 'user7', 'user8'],
    'text': [
        '정말 유용한 기능이네요! Python 최고입니다',
        '이 코드 잘 안되는데 도움 좀 주세요',
        'AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요',
        '별로예요... 다른 방법이 더 좋을 것 같아요',
        'Python pandas 정말 편리하네요',
        '딥러닝 프레임워크 추천해주세요',
        '데이터 전처리가 제일 어려워요 ㅠㅠ',
        '좋은 정보 감사합니다! 많이 배웠어요',
        '코드 에러 발생... 왜 안되는지 모르겠네요',
        'AI와 머신러닝의 차이가 뭔가요?'
    ],
    'timestamp': pd.date_range('2024-01-01', periods=10, freq='h'),
    'likes': [15, 3, 12, 2, 8, 5, 4, 10, 1, 6]
}

comments_df = pd.DataFrame(comments_data)
print("=== 댓글 데이터 ===")
print(comments_df.head())

=== 댓글 데이터 ===
   comment_id   user                            text           timestamp  \
0           1  user1      정말 유용한 기능이네요! Python 최고입니다 2024-01-01 00:00:00
1           2  user2            이 코드 잘 안되는데 도움 좀 주세요 2024-01-01 01:00:00
2           3  user3  AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요 2024-01-01 02:00:00
3           4  user4       별로예요... 다른 방법이 더 좋을 것 같아요 2024-01-01 03:00:00
4           5  user5          Python pandas 정말 편리하네요 2024-01-01 04:00:00

   likes
0     15
1      3
2     12
3      2
4      8

In [39]:
comments_df

,comment_id,user,text,timestamp,likes
0,1,user1,정말 유용한 기능이네요! Python 최고입니다,2024-01-01 00:00:00,15
1,2,user2,이 코드 잘 안되는데 도움 좀 주세요,2024-01-01 01:00:00,3
2,3,user3,AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요,2024-01-01 02:00:00,12
3,4,user4,별로예요... 다른 방법이 더 좋을 것 같아요,2024-01-01 03:00:00,2
4,5,user5,Python pandas 정말 편리하네요,2024-01-01 04:00:00,8
5,6,user1,딥러닝 프레임워크 추천해주세요,2024-01-01 05:00:00,5
6,7,user2,데이터 전처리가 제일 어려워요 ㅠㅠ,2024-01-01 06:00:00,4
7,8,user6,좋은 정보 감사합니다! 많이 배웠어요,2024-01-01 07:00:00,10
8,9,user7,코드 에러 발생... 왜 안되는지 모르겠네요,2024-01-01 08:00:00,1
9,10,user8,AI와 머신러닝의 차이가 뭔가요?,2024-01-01 09:00:00,6

In [42]:
# 텍스트 길이 분석
comments_df['text_length'] = comments_df['text'].str.len()
comments_df['word_count'] = comments_df['text'].str.split().str.len()

print("=== 텍스트 길이 분석 ===")
print(comments_df[['text', 'text_length', 'word_count']].head())

print(f"\n평균 텍스트 길이: {comments_df['text_length'].mean()}")
print(f"평균 단어 수: {comments_df['word_count'].mean()}")

=== 텍스트 길이 분석 ===
                             text  text_length  word_count
0      정말 유용한 기능이네요! Python 최고입니다           26           5
1            이 코드 잘 안되는데 도움 좀 주세요           20           7
2  AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요           30           7
3       별로예요... 다른 방법이 더 좋을 것 같아요           25           7
4          Python pandas 정말 편리하네요           22           4

평균 텍스트 길이: 22.0
평균 단어 수: 5.3

In [44]:
# 키워드 포함 여부 확인
tech_keywords = ['Python', 'AI', '머신러닝', '딥러닝', '데이터']

for keyword in tech_keywords:
    comments_df[f'has_{keyword}'] = comments_df['text'].str.contains(keyword, case=False)
    # f-string으로 파생 변수 만들기

# 기술 관련 댓글 필터링
tech_columns = [col for col in comments_df.columns if col.startswith('has_')]
tech_columns

['has_Python', 'has_AI', 'has_머신러닝', 'has_딥러닝', 'has_데이터']

In [48]:
comments_df[tech_columns].any(axis=1)

0     True
1    False
2     True
3    False
4     True
5     True
6     True
7    False
8    False
9     True
dtype: bool

In [49]:
comments_df['is_tech'] = comments_df[tech_columns].any(axis=1)

print("=== 기술 관련 댓글 ===")
tech_comments = comments_df[comments_df['is_tech']]
print(tech_comments[['user', 'text', 'likes']])

=== 기술 관련 댓글 ===
    user                            text  likes
0  user1      정말 유용한 기능이네요! Python 최고입니다     15
2  user3  AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요     12
4  user5          Python pandas 정말 편리하네요      8
5  user1                딥러닝 프레임워크 추천해주세요      5
6  user2             데이터 전처리가 제일 어려워요 ㅠㅠ      4
9  user8              AI와 머신러닝의 차이가 뭔가요?      6

In [50]:
# 감정 분석 (간단한 규칙 기반)
positive_words = ['좋', '최고', '유용', '편리', '감사', '배웠']
negative_words = ['별로', '어려', '에러', '안되', '모르겠']

def analyze_sentiment(text):
    text_lower = text.lower()
    pos_score = sum(1 for word in positive_words if word in text_lower)
    neg_score = sum(1 for word in negative_words if word in text_lower)
    
    if pos_score > neg_score:
        return '긍정'
    elif neg_score > pos_score:
        return '부정'
    else:
        return '중립'

comments_df['sentiment'] = comments_df['text'].apply(analyze_sentiment)

print("=== 감정 분석 결과 ===")
print(comments_df['sentiment'].value_counts())
print("\n=== 감정별 평균 좋아요 수 ===")
print(comments_df.groupby('sentiment')['likes'].mean())

=== 감정 분석 결과 ===
sentiment
중립    4
긍정    3
부정    3
Name: count, dtype: int64

=== 감정별 평균 좋아요 수 ===
sentiment
긍정    11.000000
부정     2.666667
중립     6.250000
Name: likes, dtype: float64

## 시계열 데이터 처리

시간 데이터를 다루는 방법을 알아보겠습니다.

In [51]:
comments_df

,comment_id,user,text,timestamp,likes,text_length,word_count,has_Python,has_AI,has_머신러닝,has_딥러닝,has_데이터,is_tech,sentiment
0,1,user1,정말 유용한 기능이네요! Python 최고입니다,2024-01-01 00:00:00,15,26,5,True,False,False,False,False,True,긍정
1,2,user2,이 코드 잘 안되는데 도움 좀 주세요,2024-01-01 01:00:00,3,20,7,False,False,False,False,False,False,부정
2,3,user3,AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요,2024-01-01 02:00:00,12,30,7,False,True,True,False,False,True,중립
3,4,user4,별로예요... 다른 방법이 더 좋을 것 같아요,2024-01-01 03:00:00,2,25,7,False,False,False,False,False,False,중립
4,5,user5,Python pandas 정말 편리하네요,2024-01-01 04:00:00,8,22,4,True,False,False,False,False,True,긍정
5,6,user1,딥러닝 프레임워크 추천해주세요,2024-01-01 05:00:00,5,16,3,False,False,False,True,False,True,중립
6,7,user2,데이터 전처리가 제일 어려워요 ㅠㅠ,2024-01-01 06:00:00,4,19,5,False,False,False,False,True,True,부정
7,8,user6,좋은 정보 감사합니다! 많이 배웠어요,2024-01-01 07:00:00,10,20,5,False,False,False,False,False,False,긍정
8,9,user7,코드 에러 발생... 왜 안되는지 모르겠네요,2024-01-01 08:00:00,1,24,6,False,False,False,False,False,False,부정
9,10,user8,AI와 머신러닝의 차이가 뭔가요?,2024-01-01 09:00:00,6,18,4,False,True,True,False,False,True,중립

In [55]:
# 시간대별 분석
comments_df['hour'] = comments_df['timestamp'].dt.hour
comments_df['date'] = comments_df['timestamp'].dt.date

hourly_stats = comments_df.groupby('hour').agg({
    'comment_id': 'count',
    'likes': 'mean'
}).rename(columns={'comment_id': 'count', 'likes': 'avg_likes'})

print("=== 시간대별 통계 ===")
print(hourly_stats)

# 활동이 가장 많은 사용자
user_activity = comments_df.groupby('user').agg({
    'comment_id': 'count',
    'likes': 'sum',
    'text_length': 'mean'
}).rename(columns={
    'comment_id': 'comment_count',
    'likes': 'total_likes',
    'text_length': 'avg_text_length'
})

print("\n=== 사용자별 활동 ===")
print(user_activity.sort_values('total_likes', ascending=False))

=== 시간대별 통계 ===
      count  avg_likes
hour
0         1       15.0
1         1        3.0
2         1       12.0
3         1        2.0
4         1        8.0
5         1        5.0
6         1        4.0
7         1       10.0
8         1        1.0
9         1        6.0

=== 사용자별 활동 ===
       comment_count  total_likes  avg_text_length
user
user1              2           20             21.0
user3              1           12             30.0
user6              1           10             20.0
user5              1            8             22.0
user2              2            7             19.5
user8              1            6             18.0
user4              1            2             25.0
user7              1            1             24.0

## 데이터 병합과 조인

여러 DataFrame을 합치는 방법을 알아보겠습니다.

In [56]:
# 사용자 정보 데이터
users_data = {
    'user': ['user1', 'user2', 'user3', 'user4', 'user5'],
    'join_date': ['2023-01-01', '2023-03-15', '2023-06-20', '2023-09-10', '2023-11-05'],
    'user_level': ['골드', '실버', '브론즈', '실버', '골드']
}
users_df = pd.DataFrame(users_data)
users_df

    user   join_date user_level
0  user1  2023-01-01         골드
1  user2  2023-03-15         실버
2  user3  2023-06-20        브론즈
3  user4  2023-09-10         실버
4  user5  2023-11-05         골드

In [57]:
comments_df

,comment_id,user,text,timestamp,likes,text_length,word_count,has_Python,has_AI,has_머신러닝,has_딥러닝,has_데이터,is_tech,sentiment,hour,date
0,1,user1,정말 유용한 기능이네요! Python 최고입니다,2024-01-01 00:00:00,15,26,5,True,False,False,False,False,True,긍정,0,2024-01-01
1,2,user2,이 코드 잘 안되는데 도움 좀 주세요,2024-01-01 01:00:00,3,20,7,False,False,False,False,False,False,부정,1,2024-01-01
2,3,user3,AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요,2024-01-01 02:00:00,12,30,7,False,True,True,False,False,True,중립,2,2024-01-01
3,4,user4,별로예요... 다른 방법이 더 좋을 것 같아요,2024-01-01 03:00:00,2,25,7,False,False,False,False,False,False,중립,3,2024-01-01
4,5,user5,Python pandas 정말 편리하네요,2024-01-01 04:00:00,8,22,4,True,False,False,False,False,True,긍정,4,2024-01-01
5,6,user1,딥러닝 프레임워크 추천해주세요,2024-01-01 05:00:00,5,16,3,False,False,False,True,False,True,중립,5,2024-01-01
6,7,user2,데이터 전처리가 제일 어려워요 ㅠㅠ,2024-01-01 06:00:00,4,19,5,False,False,False,False,True,True,부정,6,2024-01-01
7,8,user6,좋은 정보 감사합니다! 많이 배웠어요,2024-01-01 07:00:00,10,20,5,False,False,False,False,False,False,긍정,7,2024-01-01
8,9,user7,코드 에러 발생... 왜 안되는지 모르겠네요,2024-01-01 08:00:00,1,24,6,False,False,False,False,False,False,부정,8,2024-01-01
9,10,user8,AI와 머신러닝의 차이가 뭔가요?,2024-01-01 09:00:00,6,18,4,False,True,True,False,False,True,중립,9,2024-01-01

In [58]:

# 댓글 데이터와 병합
merged_df = comments_df.merge(users_df, on='user', how='left')
# 'user 컬럼 기준으로 결합', 
merged_df

,comment_id,user,text,timestamp,likes,text_length,word_count,has_Python,has_AI,has_머신러닝,has_딥러닝,has_데이터,is_tech,sentiment,hour,date,join_date,user_level
0,1,user1,정말 유용한 기능이네요! Python 최고입니다,2024-01-01 00:00:00,15,26,5,True,False,False,False,False,True,긍정,0,2024-01-01,2023-01-01,골드
1,2,user2,이 코드 잘 안되는데 도움 좀 주세요,2024-01-01 01:00:00,3,20,7,False,False,False,False,False,False,부정,1,2024-01-01,2023-03-15,실버
2,3,user3,AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요,2024-01-01 02:00:00,12,30,7,False,True,True,False,False,True,중립,2,2024-01-01,2023-06-20,브론즈
3,4,user4,별로예요... 다른 방법이 더 좋을 것 같아요,2024-01-01 03:00:00,2,25,7,False,False,False,False,False,False,중립,3,2024-01-01,2023-09-10,실버
4,5,user5,Python pandas 정말 편리하네요,2024-01-01 04:00:00,8,22,4,True,False,False,False,False,True,긍정,4,2024-01-01,2023-11-05,골드
5,6,user1,딥러닝 프레임워크 추천해주세요,2024-01-01 05:00:00,5,16,3,False,False,False,True,False,True,중립,5,2024-01-01,2023-01-01,골드
6,7,user2,데이터 전처리가 제일 어려워요 ㅠㅠ,2024-01-01 06:00:00,4,19,5,False,False,False,False,True,True,부정,6,2024-01-01,2023-03-15,실버
7,8,user6,좋은 정보 감사합니다! 많이 배웠어요,2024-01-01 07:00:00,10,20,5,False,False,False,False,False,False,긍정,7,2024-01-01,NaN,NaN
8,9,user7,코드 에러 발생... 왜 안되는지 모르겠네요,2024-01-01 08:00:00,1,24,6,False,False,False,False,False,False,부정,8,2024-01-01,NaN,NaN
9,10,user8,AI와 머신러닝의 차이가 뭔가요?,2024-01-01 09:00:00,6,18,4,False,True,True,False,False,True,중립,9,2024-01-01,NaN,NaN

In [59]:
print("=== 병합된 데이터 ===")
print(merged_df[['user', 'text', 'user_level', 'likes']].head())

# 레벨별 통계
level_stats = merged_df.groupby('user_level').agg({
    'likes': 'mean',
    'word_count': 'mean',
    'sentiment': lambda x: x.value_counts().to_dict()
})

print("\n=== 사용자 레벨별 통계 ===")
print(level_stats)

=== 병합된 데이터 ===
    user                            text user_level  likes
0  user1      정말 유용한 기능이네요! Python 최고입니다         골드     15
1  user2            이 코드 잘 안되는데 도움 좀 주세요         실버      3
2  user3  AI 기술 발전이 놀랍습니다. 머신러닝 공부하고 싶어요        브론즈     12
3  user4       별로예요... 다른 방법이 더 좋을 것 같아요         실버      2
4  user5          Python pandas 정말 편리하네요         골드      8

=== 사용자 레벨별 통계 ===
                likes  word_count           sentiment
user_level
골드           9.333333    4.000000  {'긍정': 2, '중립': 1}
브론즈         12.000000    7.000000           {'중립': 1}
실버           3.000000    6.333333  {'부정': 2, '중립': 1}

## 피벗 테이블과 크로스탭

데이터를 재구조화하는 고급 기법을 알아보겠습니다.

In [ ]:
# 피벗 테이블 생성
pivot_table = merged_df.pivot_table(
    values='likes',
    index='sentiment',
    columns='user_level',
    aggfunc='mean',
    fill_value=0
)

print("=== 감정-레벨별 평균 좋아요 수 ===")
print(pivot_table)

=== 감정-레벨별 평균 좋아요 수 ===
user_level    골드   브론즈   실버
sentiment
긍정          11.5   0.0  0.0
부정           0.0   0.0  3.5
중립           5.0  12.0  2.0

In [61]:
pivot_table

user_level    골드   브론즈   실버
sentiment
긍정          11.5   0.0  0.0
부정           0.0   0.0  3.5
중립           5.0  12.0  2.0

In [62]:

# 크로스탭
cross_tab = pd.crosstab(
    merged_df['sentiment'],
    merged_df['is_tech'],
    margins=True
)

print("\n=== 감정-기술관련 크로스탭 ===")
print(cross_tab)

cross_tab

=== 감정-기술관련 크로스탭 ===
is_tech    False  True  All
sentiment
긍정             1     2    3
부정             2     1    3
중립             1     3    4
All            4     6   10

is_tech    False  True  All
sentiment
긍정             1     2    3
부정             2     1    3
중립             1     3    4
All            4     6   10

## 데이터 저장

처리한 데이터를 파일로 저장하는 방법을 알아보겠습니다.

In [63]:
# CSV로 저장
output_file = 'processed_comments.csv'
comments_df.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"CSV 파일 저장 완료: {output_file}")

# JSON으로 저장
json_output = 'comments_analysis.json'
analysis_result = {
    'total_comments': len(comments_df),
    'sentiment_distribution': comments_df['sentiment'].value_counts().to_dict(),
    'avg_likes': float(comments_df['likes'].mean()),
    'tech_comments_ratio': float(comments_df['is_tech'].mean()),
    'top_keywords': tech_keywords[:3]
}

with open(json_output, 'w', encoding='utf-8') as f:
    json.dump(analysis_result, f, ensure_ascii=False, indent=2)
print(f"\nJSON 분석 결과 저장 완료: {json_output}")
print(json.dumps(analysis_result, ensure_ascii=False, indent=2))

CSV 파일 저장 완료: processed_comments.csv

JSON 분석 결과 저장 완료: comments_analysis.json
{
  "total_comments": 10,
  "sentiment_distribution": {
    "중립": 4,
    "긍정": 3,
    "부정": 3
  },
  "avg_likes": 6.6,
  "tech_comments_ratio": 0.6,
  "top_keywords": [
    "Python",
    "AI",
    "머신러닝"
  ]
}

## 학습 내용 정리

### 핵심 Pandas 연산

| 연산 | 코드 예시 | 설명 |
|------|----------|------|
| DataFrame 생성 | `pd.DataFrame(data)` | 딕셔너리나 리스트로 생성 |
| 파일 읽기 | `pd.read_csv()`, `pd.read_json()` | 외부 파일 로드 |
| 필터링 | `df[df['col'] > value]` | 조건에 맞는 행 선택 |
| 그룹화 | `df.groupby('col').agg()` | 그룹별 집계 |
| 병합 | `df1.merge(df2, on='key')` | 두 DataFrame 조인 |
| 피벗 | `df.pivot_table()` | 데이터 재구조화 |
| 문자열 처리 | `df['col'].str.method()` | 텍스트 컬럼 처리 |
| Apply | `df['col'].apply(function)` | 함수 적용 |

### 실습 완료 체크리스트

✓ DataFrame 생성 및 기본 조작  
✓ 데이터 필터링과 선택  
✓ 텍스트 데이터 전처리  
✓ 그룹화와 집계 분석  
✓ 데이터 병합과 피벗  
✓ 파일 입출력 (CSV, JSON)