<a href="https://colab.research.google.com/github/Leemyunglyul/ai_advanced/blob/main/%5BSDS%5DChap_3_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

In [ ]:
!pip install gmteacher -qU

In [ ]:
from gmteacher import download_file
import zipfile

download_file('ALL')

with zipfile.ZipFile('./data/data.zip', 'r') as f:
    f.extractall('./data/')

In [ ]:
import pandas

In [ ]:
pandas.__version__

'2.2.3'

In [ ]:
import pandas as pd

In [ ]:
pd

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
import numpy as np

## Pandas 자료 구조

### Series

In [ ]:
arr = np.arange(100, 105)
arr

array([100, 101, 102, 103, 104])

In [ ]:
s = pd.Series(arr)
s

0    100
1    101
2    102
3    103
4    104
dtype: int64

In [ ]:
s = pd.Series(arr, dtype='int32')
s

0    100
1    101
2    102
3    103
4    104
dtype: int32

In [ ]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s

0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [ ]:
s = pd.Series([91, 2.5, '스포츠', 4, 5.16])
s

0      91
1     2.5
2     스포츠
3       4
4    5.16
dtype: object

In [ ]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s

0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [ ]:
s[0]

'부장'

### Series 속성

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'], index=['a', 'b', 'c', 'd', 'e'])
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [ ]:
s.index = list('abcde')

In [ ]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
s.values

array(['마케팅', '경영', '개발', '기획', '인사'], dtype=object)

In [ ]:
s.ndim

1

In [ ]:
s.shape

(5,)

### 결측치 표현

In [ ]:
s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
s

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: object

### indexing

In [ ]:
s = pd.Series(['손흥민', '김연아', '박세리', '박찬호', '김연경'], index=['a', 'b', 'c', 'd', 'e'])
s

a    손흥민
b    김연아
c    박세리
d    박찬호
e    김연경
dtype: object

In [ ]:
s['b']

'김연아'

### slicing

In [ ]:
s[1:3]

b    김연아
c    박세리
dtype: object

In [ ]:
s['b':'c']

b    김연아
c    박세리
dtype: object

### fancy indexing

In [ ]:
s[['a','c']]

a    손흥민
c    박세리
dtype: object

In [ ]:
i = ['a', 'c']
s[i]

a    손흥민
c    박세리
dtype: object

### boolean indexing

In [ ]:
s[[True, True, False, False, True]]

a    손흥민
b    김연아
e    김연경
dtype: object

In [ ]:
i = [True, True, False, False, True]
s[i]

a    손흥민
b    김연아
e    김연경
dtype: object

In [ ]:
s = pd.Series([29, 99, np.nan, 11, 56], index=['a', 'b', 'c', 'd', 'e'])
s

a    29.0
b    99.0
c     NaN
d    11.0
e    56.0
dtype: float64

In [ ]:
s > 50

a    False
b     True
c    False
d    False
e     True
dtype: bool

In [ ]:
s[s > 50]

b    99.0
e    56.0
dtype: float64

### DataFrame

In [ ]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
pd.DataFrame([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], columns=['가', '나', '다'])

   가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [24, 27, 34],
    'children': [2, 1, 3]
}

In [ ]:
pd.DataFrame(data)

   name  age  children
0   Kim   24         2
1   Lee   27         1
2  Park   34         3

### DataFrame 속성

In [ ]:
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [24, 27, 34],
    'children': [2, 1, 3]
}

df = pd.DataFrame(data)
df

   name  age  children
0   Kim   24         2
1   Lee   27         1
2  Park   34         3

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

Index(['name', 'age', 'children'], dtype='object')

In [ ]:
df.shape

(3, 3)

In [ ]:
df.values

array([['Kim', 24, 2],
       ['Lee', 27, 1],
       ['Park', 34, 3]], dtype=object)

In [ ]:
df.dtypes

name        object
age          int64
children     int64
dtype: object

In [ ]:
df.T

            0    1     2
name      Kim  Lee  Park
age        24   27    34
children    2    1     3

In [ ]:
df

   name  age  children
0   Kim   24         2
1   Lee   27         1
2  Park   34         3

In [ ]:
df.index = list('abc')
df

   name  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

### column 다루기

In [ ]:
df['name']

a     Kim
b     Lee
c    Park
Name: name, dtype: object

In [ ]:
type(df['name'])

pandas.core.series.Series

In [ ]:
df[['name', 'children']]

   name  children
a   Kim         2
b   Lee         1
c  Park         3

In [ ]:
df.rename(columns={'name': '이름'})

     이름  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

In [ ]:
df.rename({'name': '이름'}, axis=1)

     이름  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

In [ ]:
df.rename(columns={'name': '이름'}, inplace=True)
df

     이름  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

## Pandas 파일 처리

### Excel

In [ ]:
excel = pd.read_excel('./data/seoul_transportation.xlsx', sheet_name='철도')

In [ ]:
excel.head()

  대중교통구분  노선명      년월   승차총승객수
0    지하철  1호선  201711  8633618
1    지하철  1호선  201712  8737235
2    지하철  1호선  201801  8145989
3    지하철  1호선  201802  7273309
4    지하철  1호선  201803  8692551

In [ ]:
excel = pd.read_excel('./data/seoul_transportation.xlsx', sheet_name='버스')
excel.head()

  대중교통구분      년월     승차총승객수
0     버스  201711  163443126
1     버스  201712  162521011
2     버스  201801  153335185
3     버스  201802  134768582
4     버스  201803  166177855

In [ ]:
excel = pd.read_excel('./data/seoul_transportation.xlsx', sheet_name=None)
excel

{'철도':     대중교통구분    노선명      년월   승차총승객수
 0      지하철    1호선  201711  8633618
 1      지하철    1호선  201712  8737235
 2      지하철    1호선  201801  8145989
 3      지하철    1호선  201802  7273309
 4      지하철    1호선  201803  8692551
 ..     ...    ...     ...      ...
 596    지하철  우이신설선  201901  1263643
 597    지하철  우이신설선  201902  1102109
 598    지하철  우이신설선  201903  1402393
 599    지하철  우이신설선  201904  1403115
 600    지하철  우이신설선  201905  1469681

 [601 rows x 4 columns],
 '버스':    대중교통구분      년월     승차총승객수
 0      버스  201711  163443126
 1      버스  201712  162521011
 2      버스  201801  153335185
 3      버스  201802  134768582
 4      버스  201803  166177855
 5      버스  201804  160452595
 6      버스  201805  164390595
 7      버스  201806  156999747
 8      버스  201807  163736112
 9      버스  201808  160240197
 10     버스  201809  151311657
 11     버스  201810  165820934
 12     버스  201811  163017758
 13     버스  201812  158049446
 14     버스  201901  153037549
 15     버스  201902  131621925
 16     버스  201903  161694445
 17     버스  201904  161900273
 18     버스  201905  166587933}

In [ ]:
# 시트 조회
excel.keys()

dict_keys(['철도', '버스'])

In [ ]:
excel['철도']

    대중교통구분    노선명      년월   승차총승객수
0      지하철    1호선  201711  8633618
1      지하철    1호선  201712  8737235
2      지하철    1호선  201801  8145989
3      지하철    1호선  201802  7273309
4      지하철    1호선  201803  8692551
..     ...    ...     ...      ...
596    지하철  우이신설선  201901  1263643
597    지하철  우이신설선  201902  1102109
598    지하철  우이신설선  201903  1402393
599    지하철  우이신설선  201904  1403115
600    지하철  우이신설선  201905  1469681

[601 rows x 4 columns]

In [ ]:
excel['버스']

   대중교통구분      년월     승차총승객수
0      버스  201711  163443126
1      버스  201712  162521011
2      버스  201801  153335185
3      버스  201802  134768582
4      버스  201803  166177855
5      버스  201804  160452595
6      버스  201805  164390595
7      버스  201806  156999747
8      버스  201807  163736112
9      버스  201808  160240197
10     버스  201809  151311657
11     버스  201810  165820934
12     버스  201811  163017758
13     버스  201812  158049446
14     버스  201901  153037549
15     버스  201902  131621925
16     버스  201903  161694445
17     버스  201904  161900273
18     버스  201905  166587933

In [ ]:
excel['철도'].to_excel('sample.xlsx', index=True)

In [ ]:
excel['버스'].to_excel('sample1.xlsx', index=False, sheet_name='샘플')

In [ ]:
writer = pd.ExcelWriter('sample2.xlsx')
excel['철도'].to_excel(writer, index=False, sheet_name='샘플1')
excel['버스'].to_excel(writer, index=False, sheet_name='샘플2')
writer.close()

In [ ]:
with pd.ExcelWriter('sample2.xlsx') as writer:
    excel['철도'].to_excel(writer, index=False, sheet_name='샘플1')
    excel['버스'].to_excel(writer, index=False, sheet_name='샘플2')

In [ ]:
with pd.ExcelWriter('sample2.xlsx', mode='a') as writer:
    excel['철도'].to_excel(writer, index=False, sheet_name='샘플3')
    excel['버스'].to_excel(writer, index=False, sheet_name='샘플4')

### CSV (Comma Separated Values)

In [ ]:
df = pd.read_csv('./data/seoul_population.csv')

In [ ]:
df.head()

,연도,자치구,세대수,인구 합계,남자 인구 합계,여자 인구 합계,한국인 인구 합계,한국인 남자 인구수,한국인 여자 인구수,등록 외국인 인구 합계,등록 외국인 인구 남자수,등록 외국인 인구 여자수,세대당 인구,65세 이상 고령자 수
0,2020,합계,"4,417,954","9,911,088","4,816,522","5,094,566","9,668,465","4,701,723","4,966,742","242,623","114,799","127,824",2.19,"1,568,331"
1,2020,종로구,"75,003","158,996","76,876","82,120","149,384","72,635","76,749","9,612","4,241","5,371",1.99,"28,507"
2,2020,중구,"63,686","134,635","65,776","68,859","125,240","61,222","64,018","9,395","4,554","4,841",1.97,"24,495"
3,2020,용산구,"113,093","244,645","118,835","125,810","230,040","110,722","119,318","14,605","8,113","6,492",2.03,"40,247"
4,2020,성동구,"135,870","300,505","146,424","154,081","293,556","143,387","150,169","6,949","3,037","3,912",2.16,"45,603"

In [ ]:
df = pd.read_csv('./data/seoul_population.csv', encoding='utf8')

In [ ]:
df.head()

,연도,자치구,세대수,인구 합계,남자 인구 합계,여자 인구 합계,한국인 인구 합계,한국인 남자 인구수,한국인 여자 인구수,등록 외국인 인구 합계,등록 외국인 인구 남자수,등록 외국인 인구 여자수,세대당 인구,65세 이상 고령자 수
0,2020,합계,"4,417,954","9,911,088","4,816,522","5,094,566","9,668,465","4,701,723","4,966,742","242,623","114,799","127,824",2.19,"1,568,331"
1,2020,종로구,"75,003","158,996","76,876","82,120","149,384","72,635","76,749","9,612","4,241","5,371",1.99,"28,507"
2,2020,중구,"63,686","134,635","65,776","68,859","125,240","61,222","64,018","9,395","4,554","4,841",1.97,"24,495"
3,2020,용산구,"113,093","244,645","118,835","125,810","230,040","110,722","119,318","14,605","8,113","6,492",2.03,"40,247"
4,2020,성동구,"135,870","300,505","146,424","154,081","293,556","143,387","150,169","6,949","3,037","3,912",2.16,"45,603"

In [ ]:
df = pd.read_csv('./data/seoul_population.csv')

In [ ]:
df.to_csv('sample_utf8.csv', index=False)

In [ ]:
df.to_csv('sample_cp949.csv', index=False, encoding='cp949')

## Pandas 데이터 탐색

In [ ]:
df = pd.read_csv('./data/titanic.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

## 정렬 (sort)

In [ ]:
df.sort_index().head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.sort_index(ascending=False).head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [ ]:
df.sort_values(by='age', ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.sort_values(by=['fare', 'age']).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
302,0,3,male,19.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
271,1,3,male,25.0,0,0,0.0,S,Third,man,True,NaN,Southampton,yes,True
179,0,3,male,36.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
822,0,1,male,38.0,0,0,0.0,S,First,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0,S,First,man,True,A,Southampton,no,True

In [ ]:
df.sort_values(by=['fare', 'age'], ascending=[False, True]).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False

## 데이터 선택

In [ ]:
df = pd.read_csv('./data/titanic.csv')

In [ ]:
df['sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [ ]:
df[0]

KeyError: 0

In [ ]:
df[0:2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [ ]:
df['sex':'age']

TypeError: cannot do slice indexing on RangeIndex with these indexers [sex] of type str

In [ ]:
df.T['sex':'age']

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0

In [ ]:
df[['sex', 'age', 'who']].head()

      sex   age    who
0    male  22.0    man
1  female  38.0  woman
2  female  26.0  woman
3  female  35.0  woman
4    male  35.0    man

In [ ]:
df['embarked'] == 'Q'

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890     True
Name: embarked, Length: 891, dtype: bool

In [ ]:
df[df['embarked'] == 'Q']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
825,0,3,male,NaN,0,0,6.9500,Q,Third,man,True,NaN,Queenstown,no,True
828,1,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

### loc indexer

In [ ]:
df.loc[5, 'class']

'Third'

In [ ]:
df.loc[2:5, 'class':'deck']

   class    who  adult_male deck
2  Third  woman       False  NaN
3  First  woman       False    C
4  Third    man        True  NaN
5  Third    man        True  NaN

In [ ]:
df.loc[[1, 1, 2], ['age', 'fare', 'who']]

    age     fare    who
1  38.0  71.2833  woman
1  38.0  71.2833  woman
2  26.0   7.9250  woman

In [ ]:
df.loc[(df['fare'] > 300)&(df['sex'] == 'female'), :]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True

### iloc indexer

In [ ]:
df.iloc[5, 8]

'Third'

In [ ]:
df.iloc[2:6, 8:12]

   class    who  adult_male deck
2  Third  woman       False  NaN
3  First  woman       False    C
4  Third    man        True  NaN
5  Third    man        True  NaN

In [ ]:
df.iloc[[1, 1, 2], [3, 6, 9]]

    age     fare    who
1  38.0  71.2833  woman
1  38.0  71.2833  woman
2  26.0   7.9250  woman

In [ ]:
df.iloc[(df['fare'] > 300).values&(df['sex'] == 'female').values, :]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True

### at indexer

In [ ]:
%timeit df.loc[0, 'fare']

7.37 μs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [ ]:
%timeit df.at[0, 'fare']

3.15 μs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

### iat indexer

In [ ]:
%timeit df.iloc[0, 5]

18.3 μs ± 266 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [ ]:
%timeit df.iat[0, 5]

14.1 μs ± 762 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

## Pandas 기술 통계

In [ ]:
df = pd.read_csv('./data/titanic.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df.describe(include='object')

         sex embarked  class  who deck  embark_town alive
count    891      889    891  891  203          889   891
unique     2        3      3    3    7            3     2
top     male        S  Third  man    C  Southampton    no
freq     577      644    491  537   59          644   549

In [ ]:
# DataFrame 전체의 개수를 구하는 경우
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
# 단일 column의 데이터 개수를 구하는 경우
df['age'].count()

np.int64(714)

In [ ]:
df.iloc[:, :7].sum()

survived                                                  342
pclass                                                   2057
sex         malefemalefemalefemalemalemalemalemalefemalefe...
age                                                  21205.17
sibsp                                                     466
parch                                                     340
fare                                               28693.9493
dtype: object

In [ ]:
df['fare'].sum()

np.float64(28693.9493)

In [ ]:
df['age'].cumsum()

0         22.00
1         60.00
2         86.00
3        121.00
4        156.00
         ...
886    21128.17
887    21147.17
888         NaN
889    21173.17
890    21205.17
Name: age, Length: 891, dtype: float64

In [ ]:
df['age'].cumprod()

/usr/local/lib/python3.13/dist-packages/numpy/_core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

0            22.0
1           836.0
2         21736.0
3        760760.0
4      26626600.0
          ...
886           inf
887           inf
888           NaN
889           inf
890           inf
Name: age, Length: 891, dtype: float64

In [ ]:
# DataFrame 평균
df.mean(numeric_only=True)

survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64

In [ ]:
# Column 평균
df['age'].mean()

np.float64(29.69911764705882)

In [ ]:
condition = (df['adult_male'] == True)
df.loc[condition, 'age'].mean()

np.float64(33.17312348668281)

In [ ]:
# skipna=False를 지정한 경우
df.mean(skipna=False, numeric_only=True)

survived       0.383838
pclass         2.308642
age                 NaN
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64

In [ ]:
# skipna=True를 지정한 경우
df.mean(skipna=True, numeric_only=True)

survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64

In [ ]:
pd.Series([4, 5, 1, 2, 3]).median()

3.0

In [ ]:
pd.Series([4, 1000, 1, 2, 3]).median()

3.0

In [ ]:
pd.Series([1, 2, 3, 4, 5, 6]).median()

3.5

In [ ]:
print(f"나이 평균: {df['age'].mean():.5f}\n나이 중앙값: {df['age'].median()}\n차이: {df['age'].mean() - df['age'].median():.5f}")

나이 평균: 29.69912
나이 중앙값: 28.0
차이: 1.69912

In [ ]:
df.var(ddof=1, numeric_only=True)

survived         0.236772
pclass           0.699015
age            211.019125
sibsp            1.216043
parch            0.649728
fare          2469.436846
adult_male       0.239723
alone            0.239723
dtype: float64

In [ ]:
df.var(ddof=0, numeric_only=True)

survived         0.236506
pclass           0.698231
age            210.723580
sibsp            1.214678
parch            0.648999
fare          2466.665312
adult_male       0.239454
alone            0.239454
dtype: float64

In [ ]:
df.std(ddof=1, numeric_only=True)

survived       0.486592
pclass         0.836071
age           14.526497
sibsp          1.102743
parch          0.806057
fare          49.693429
adult_male     0.489615
alone          0.489615
dtype: float64

In [ ]:
df.std(ddof=0, numeric_only=True)

survived       0.486319
pclass         0.835602
age           14.516321
sibsp          1.102124
parch          0.805605
fare          49.665534
adult_male     0.489340
alone          0.489340
dtype: float64

In [ ]:
df['age'].quantile(0.1) # 하위 10% 값, 10% quantile

np.float64(14.0)

In [ ]:
df['age'].quantile(0.8) # 상위 20% 값, 80% quantile

np.float64(41.0)

In [ ]:
df['who'].mode()

0    man
Name: who, dtype: object

In [ ]:
df['deck'].mode()

0    C
Name: deck, dtype: object

In [ ]:
# 최솟값
df['age'].min()

0.42

In [ ]:
# 최댓값
df['age'].max()

80.0

In [ ]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [ ]:
df['who'].nunique()

3

In [ ]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [ ]:
df['who'].value_counts(normalize=True)

who
man      0.602694
woman    0.304153
child    0.093154
Name: proportion, dtype: float64

In [ ]:
df['fare'].agg(['min', 'max', 'mean', 'median', 'std'])

min         0.000000
max       512.329200
mean       32.204208
median     14.454200
std        49.693429
Name: fare, dtype: float64

## Pandas 추가, 삭제, 변환

In [ ]:
df = pd.read_csv('./data/titanic.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df['VIP'] = True

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True

## 행/열 삭제

In [ ]:
df.drop(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [ ]:
df.drop(df.index[0:10])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,True
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [ ]:
df.drop('class', axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.0,1,0,71.2833,C,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.0,0,0,7.9250,S,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,man,True,NaN,Southampton,no,True,True

### 컬럼 간 연산

In [ ]:
df = pd.read_csv('./data/titanic.csv')

In [ ]:
df1 = df.copy()

In [ ]:
df1['family'] = df1['sibsp'] + df1['parch']

In [ ]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0

In [ ]:
df1['gender'] = df1['who'] + '-' + df1['sex']

In [ ]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family,gender
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,man-male
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,woman-female
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,woman-female
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,woman-female
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,man-male

In [ ]:
df1['round'] = round(df1['fare'] / df1['age'], 2)
df1['round']

0      0.33
1      1.88
2      0.30
3      1.52
4      0.23
       ...
886    0.48
887    1.58
888     NaN
889    1.15
890    0.24
Name: round, Length: 891, dtype: float64

### 타입 변환 (astype)

In [ ]:
df1 = df.copy()

In [ ]:
df1['pclass'].astype('int32').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: int32

In [ ]:
df1['pclass'].astype('float32').head()

0    3.0
1    1.0
2    3.0
3    1.0
4    3.0
Name: pclass, dtype: float32

In [ ]:
df1['pclass'].astype('str').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: object

## Pandas 문자열 데이터 처리

In [ ]:
df = pd.read_csv('./data/titanic.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df['embark_town'][0] # 일반 인덱싱

'Southampton'

In [ ]:
df['embark_town'].str[0] # 접속자 인덱싱

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'][:2] # 일반 슬라이싱

0    Southampton
1      Cherbourg
Name: embark_town, dtype: object

In [ ]:
df['embark_town'].str[:2] # 접속자 슬라이싱

0      So
1      Ch
2      So
3      So
4      So
       ..
886    So
887    So
888    So
889    Ch
890    Qu
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'].str.split('o')

0      [S, uthampt, n]
1         [Cherb, urg]
2      [S, uthampt, n]
3      [S, uthampt, n]
4      [S, uthampt, n]
            ...
886    [S, uthampt, n]
887    [S, uthampt, n]
888    [S, uthampt, n]
889       [Cherb, urg]
890      [Queenst, wn]
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'].str.contains('South')

0       True
1      False
2       True
3       True
4       True
       ...
886     True
887     True
888     True
889    False
890    False
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'].replace('Cherbourg', '셰르부르') # 일반 replace

0      Southampton
1             셰르부르
2      Southampton
3      Southampton
4      Southampton
          ...
886    Southampton
887    Southampton
888    Southampton
889           셰르부르
890     Queenstown
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'].str.replace('Cher', '셰르') # 접속자 replace

0      Southampton
1          셰르bourg
2      Southampton
3      Southampton
4      Southampton
          ...
886    Southampton
887    Southampton
888    Southampton
889        셰르bourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object

## Pandas 결측치 처리

In [ ]:
np.nan == np.nan, pd.NA == pd.NA

(False, <NA>)

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(869)

In [ ]:
df.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
df.loc[df['age'].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
df['age'] = df['age'].fillna(700)

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,700.0,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df['deck'].fillna('A')

0      A
1      C
2      A
3      C
4      A
      ..
886    A
887    B
888    A
889    C
890    A
Name: deck, Length: 891, dtype: object

In [ ]:
df = pd.read_csv('./data/titanic.csv')

In [ ]:
df['age'].fillna(df['age'].mean()).tail()

886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, dtype: float64

In [ ]:
df['age'].fillna(df['age'].median()).tail()

886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, dtype: float64

In [ ]:
df['deck'].mode()

0    C
Name: deck, dtype: object

In [ ]:
df['deck'].mode()[0]

'C'

In [ ]:
df['deck'].fillna(df['deck'].mode()[0]).tail()

886    C
887    B
888    C
889    C
890    C
Name: deck, dtype: object

In [ ]:
df = pd.read_csv('./data/titanic.csv')

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.dropna()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
df.dropna(how='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.dropna(thresh=800, axis=1)

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

### apply

In [ ]:
df = pd.read_csv('./data/titanic.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [ ]:
def transform_who(x):
    if x == 'man':
        return 0
    elif x == 'woman':
        return 1
    else:
        return x

In [ ]:
df['who'].apply(transform_who)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: who, Length: 891, dtype: object

In [ ]:
pd.get_dummies(df[['embarked', 'age']]).iloc[60:70]

     age  embarked_C  embarked_Q  embarked_S
60  22.0        True       False       False
61  38.0       False       False       False
62  45.0       False       False        True
63   4.0       False       False        True
64   NaN        True       False       False
65   NaN        True       False       False
66  29.0       False       False        True
67  19.0       False       False        True
68  17.0       False       False        True
69  26.0       False       False        True