## Pandas Indexing and Indexers WS

In [1]:
import pandas as pd

### 데이터 불러오기

In [2]:
# seoul_cctv.xlsx 파일을 읽어서 df에 저장하세요.
df = pd.read_excel('./data/seoul_cctv.xlsx')
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [3]:
# 인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df['소계']

0     2780
1      773
2      748
3      884
4     1496
5      707
6     1561
7     1015
8     1265
9      485
10    1294
11    1091
12     574
13     962
14    1930
15    1062
16    1464
17     618
18    2034
19     904
20    1624
21    1873
22    1002
23     671
24     660
Name: 소계, dtype: int64

In [4]:
# 팬시 인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df[['소계']]

      소계
0   2780
1    773
2    748
3    884
4   1496
5    707
6   1561
7   1015
8   1265
9    485
10  1294
11  1091
12   574
13   962
14  1930
15  1062
16  1464
17   618
18  2034
19   904
20  1624
21  1873
22  1002
23   671
24   660

In [5]:
# loc indexer와 인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df.loc[:, '소계']

0     2780
1      773
2      748
3      884
4     1496
5      707
6     1561
7     1015
8     1265
9      485
10    1294
11    1091
12     574
13     962
14    1930
15    1062
16    1464
17     618
18    2034
19     904
20    1624
21    1873
22    1002
23     671
24     660
Name: 소계, dtype: int64

In [6]:
# iloc indexer와 인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df.iloc[:, 1]

0     2780
1      773
2      748
3      884
4     1496
5      707
6     1561
7     1015
8     1265
9      485
10    1294
11    1091
12     574
13     962
14    1930
15    1062
16    1464
17     618
18    2034
19     904
20    1624
21    1873
22    1002
23     671
24     660
Name: 소계, dtype: int64

In [7]:
# loc indexer와 팬시인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df.loc[:, ['소계']]

      소계
0   2780
1    773
2    748
3    884
4   1496
5    707
6   1561
7   1015
8   1265
9    485
10  1294
11  1091
12   574
13   962
14  1930
15  1062
16  1464
17   618
18  2034
19   904
20  1624
21  1873
22  1002
23   671
24   660

In [8]:
# iloc indexer와 팬시인덱싱을 이용하여 소계 열을 선택하고 출력하세요.
df.iloc[:, [1]]

      소계
0   2780
1    773
2    748
3    884
4   1496
5    707
6   1561
7   1015
8   1265
9    485
10  1294
11  1091
12   574
13   962
14  1930
15  1062
16  1464
17   618
18  2034
19   904
20  1624
21  1873
22  1002
23   671
24   660

In [9]:
# loc indexer와 인덱싱을 이용하여 서대문구의 데이터를 출력하세요.
df.loc[13, :]

기관명          서대문구
소계            962
2013년도 이전     844
2014년          50
2015년          68
2016년         292
Name: 13, dtype: object

In [10]:
# iloc indexer와 인덱싱을 이용하여 서대문구의 데이터를 출력하세요.
df.iloc[13, :]

기관명          서대문구
소계            962
2013년도 이전     844
2014년          50
2015년          68
2016년         292
Name: 13, dtype: object

In [11]:
# loc indexer와 팬시인덱싱을 이용하여 서대문구의 데이터를 출력하세요.
df.loc[[13], :]

     기관명   소계  2013년도 이전  2014년  2015년  2016년
13  서대문구  962        844     50     68    292

In [12]:
# iloc indexer와 팬시인덱싱을 이용하여 서대문구의 데이터를 출력하세요.
df.iloc[[13], :]

     기관명   소계  2013년도 이전  2014년  2015년  2016년
13  서대문구  962        844     50     68    292

In [13]:
# 인덱싱을 이용하여 강동구의 2016년 cctv 수량을 출력하세요.
df['2016년'][1]

np.int64(377)

In [14]:
# loc indexer를 이용하여 강동구의 2016년 cctv 수량을 출력하세요.
df.loc[1, '2016년']

np.int64(377)

In [15]:
# iloc indexer를 이용하여 강동구의 2016년 cctv 수량을 출력하세요.
df.iloc[1, -1]

np.int64(377)

In [16]:
# 강동구의 2016년 cctv 수량을 477개로 수정하세요.
df.loc[1, '2016년'] = 477
df.loc[1, :]

기관명          강동구
소계           773
2013년도 이전    379
2014년         99
2015년        155
2016년        477
Name: 1, dtype: object

In [17]:
# loc indexer를 이용하여 2014년~2016년 열을 선택하세요.
df.loc[:, '2014년':'2016년']

    2014년  2015년  2016년
0     430    584    932
1      99    155    477
2     120    138    204
3     258    184     81
4     260    390    613
5      78     53    174
6     173    246    323
7      51    269    354
8      57    451    516
9     159     42    386
10     23    198    579
11    341    103    314
12    118    169    379
13     50     68    292
14    157    336    398
15     91    241    265
16     78    360    204
17     21     68    463
18    142     30    467
19    214    195    373
20    218    112    398
21    224    278    468
22    314    211    630
23    190     72    348
24    121    177    109

In [18]:
# iloc indexer를 이용하여 2014년~2016년 열을 선택하세요.
df.iloc[:, 3:]

    2014년  2015년  2016년
0     430    584    932
1      99    155    477
2     120    138    204
3     258    184     81
4     260    390    613
5      78     53    174
6     173    246    323
7      51    269    354
8      57    451    516
9     159     42    386
10     23    198    579
11    341    103    314
12    118    169    379
13     50     68    292
14    157    336    398
15     91    241    265
16     78    360    204
17     21     68    463
18    142     30    467
19    214    195    373
20    218    112    398
21    224    278    468
22    314    211    630
23    190     72    348
24    121    177    109

In [19]:
# 강남구~광진구의 데이터를 선택하세요.
df[0:6]

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    477
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613
5  광진구   707        573     78     53    174

In [20]:
# loc indexer를 이용하여 강남구~광진구의 데이터를 선택하세요.
df.loc[0:5, :]

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    477
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613
5  광진구   707        573     78     53    174

In [21]:
# iloc indexer를 이용하여 강남구~광진구의 데이터를 선택하세요.
df.iloc[0:6, :]

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    477
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613
5  광진구   707        573     78     53    174

In [22]:
# 동대문구~용산구의 기관명, 소계, 2015년 데이터를 추출하세요. (일반 조회 방법을 사용하세요.)
df[10:21][['기관명', '소계', '2015년']]

     기관명    소계  2015년
10  동대문구  1294    198
11   동작구  1091    103
12   마포구   574    169
13  서대문구   962     68
14   서초구  1930    336
15   성동구  1062    241
16   성북구  1464    360
17   송파구   618     68
18   양천구  2034     30
19  영등포구   904    195
20   용산구  1624    112

In [23]:
# loc indexer를 이용하여 동대문구~용산구의 기관명, 소계, 2015년 데이터를 추출하세요.
df.loc[10:20, ['기관명', '소계', '2015년']]

     기관명    소계  2015년
10  동대문구  1294    198
11   동작구  1091    103
12   마포구   574    169
13  서대문구   962     68
14   서초구  1930    336
15   성동구  1062    241
16   성북구  1464    360
17   송파구   618     68
18   양천구  2034     30
19  영등포구   904    195
20   용산구  1624    112

In [24]:
# iloc indexer를 이용하여 동대문구~용산구의 기관명, 소계, 2015년 데이터를 추출하세요.
df.iloc[10:21, [0, 1, -2]]

     기관명    소계  2015년
10  동대문구  1294    198
11   동작구  1091    103
12   마포구   574    169
13  서대문구   962     68
14   서초구  1930    336
15   성동구  1062    241
16   성북구  1464    360
17   송파구   618     68
18   양천구  2034     30
19  영등포구   904    195
20   용산구  1624    112

In [25]:
# 불리언 인덱싱을 이용하여 강동구 데이터를 추출하세요.
df[df['기관명']=='강동구']

   기관명   소계  2013년도 이전  2014년  2015년  2016년
1  강동구  773        379     99    155    477

In [26]:
# loc Indexer와 불리언 인덱싱을 이용하여 강동구 데이터를 추출하세요.
df.loc[df['기관명']=='강동구', :]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
1  강동구  773        379     99    155    477

In [27]:
# iloc Indexer와 불리언 인덱싱을 이용하여 강동구 데이터를 추출하세요.
df.iloc[(df['기관명']=='강동구').values, :]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
1  강동구  773        379     99    155    477

In [28]:
# loc Indexer를 이용하여 열의 이름에 "년"이 포함된 열들만 추출하세요.
df.loc[:, df.columns.str.contains('년')]

    2013년도 이전  2014년  2015년  2016년
0        1292    430    584    932
1         379     99    155    477
2         369    120    138    204
3         388    258    184     81
4         846    260    390    613
5         573     78     53    174
6        1142    173    246    323
7         674     51    269    354
8         542     57    451    516
9         238    159     42    386
10       1070     23    198    579
11        544    341    103    314
12        314    118    169    379
13        844     50     68    292
14       1406    157    336    398
15        730     91    241    265
16       1009     78    360    204
17        529     21     68    463
18       1843    142     30    467
19        495    214    195    373
20       1368    218    112    398
21       1138    224    278    468
22        464    314    211    630
23        413    190     72    348
24        509    121    177    109

In [29]:
# iloc Indexer를 이용하여 열의 이름에 "년"이 포함된 열들만 추출하세요.
df.iloc[:, df.columns.str.contains('년')]

    2013년도 이전  2014년  2015년  2016년
0        1292    430    584    932
1         379     99    155    477
2         369    120    138    204
3         388    258    184     81
4         846    260    390    613
5         573     78     53    174
6        1142    173    246    323
7         674     51    269    354
8         542     57    451    516
9         238    159     42    386
10       1070     23    198    579
11        544    341    103    314
12        314    118    169    379
13        844     50     68    292
14       1406    157    336    398
15        730     91    241    265
16       1009     78    360    204
17        529     21     68    463
18       1843    142     30    467
19        495    214    195    373
20       1368    218    112    398
21       1138    224    278    468
22        464    314    211    630
23        413    190     72    348
24        509    121    177    109

In [30]:
# 불리언 인덱싱을 이용하여 2014년 신규 cctv 수가 150개 이상이고
# 동시에 2016년 신규 cctv 수가 300개 이하인 행을 추출하세요.
cond1 = df['2014년'] >=150
cond2 = df['2016년'] <=300

df[cond1&cond2]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
3  강서구  884        388    258    184     81

In [31]:
# loc Indexer를 이용하여 2014년 신규 cctv 수가 150개 이상이고
# 동시에 2016년 신규 cctv 수가 300개 이상인 행을 추출하세요.
cond1 = df['2014년'] >=150
cond2 = df['2016년'] <=300

df.loc[cond1&cond2, :]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
3  강서구  884        388    258    184     81

In [32]:
# iloc Indexer를 이용하여 2014년 신규 cctv 수가 150개 이상이고 
# 동시에 2016년 신규 cctv 수가 300개 이상인 행을 추출하세요.
cond1 = df['2014년'] >=150
cond2 = df['2016년'] <=300

df.iloc[(cond1&cond2).values, :]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
3  강서구  884        388    258    184     81

In [33]:
# df의 데이터 중 2014년을 기준으로 신규 cctv 수가 매년 증가한 지역의 데이터를 출력하세요.
# 2014<2015<2016인 지역의 기관명
cond = (df['2014년'] < df['2015년']) & (df['2015년'] < df['2016년'])
df.loc[cond, :]

     기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    477
2    강북구   748        369    120    138    204
4    관악구  1496        846    260    390    613
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
10  동대문구  1294       1070     23    198    579
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
17   송파구   618        529     21     68    463
21   은평구  1873       1138    224    278    468

In [34]:
# df의 데이터 중 2014년을 기준으로 신규 cctv 수가 매년 증가한 지역 외 나머지 지역의 데이터를 출력하세요.
cond = (df['2014년'] < df['2015년']) & (df['2015년'] < df['2016년'])
df.loc[~cond, :]

     기관명    소계  2013년도 이전  2014년  2015년  2016년
3    강서구   884        388    258    184     81
5    광진구   707        573     78     53    174
9    도봉구   485        238    159     42    386
11   동작구  1091        544    341    103    314
16   성북구  1464       1009     78    360    204
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [35]:
# df의 데이터 중 2014년을 기준으로 신규 cctv 수가 매년 감소한 지역의 기관명을 출력하세요.
# 2014>2015>2016인 지역의 기관명
cond = (df['2014년'] > df['2015년']) & (df['2015년'] > df['2016년'])
df[cond]

   기관명   소계  2013년도 이전  2014년  2015년  2016년
3  강서구  884        388    258    184     81

In [36]:
# 강서구의 2014년 대비 2016년의 신규 cctv의 비율을 백분율로 계산한 후 소수점 셋째자리까지 출력하세요.
강서구2016 = df.loc[df['기관명'] == '강서구', '2016년']
강서구2014 = df.loc[df['기관명'] == '강서구', '2014년']

비율 = (강서구2016/강서구2014*100).iloc[0]
print(f'강서구의 2014년 대비 2016년의 신규 cctv 수 비율은 약 {비율:.3f}%입니다.')

강서구의 2014년 대비 2016년의 신규 cctv 수 비율은 약 31.395%입니다.

In [37]:
# 모든 지역의 2014년 대비 2016년의 신규 cctv 증감율을 계산한 후
# 새 열 "증감률"에 저장하세요.
df['증감률'] = ((df['2016년'] - df['2014년'])/df['2014년']*100)
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년          증감률
0    강남구  2780       1292    430    584    932   116.744186
1    강동구   773        379     99    155    477   381.818182
2    강북구   748        369    120    138    204    70.000000
3    강서구   884        388    258    184     81   -68.604651
4    관악구  1496        846    260    390    613   135.769231
5    광진구   707        573     78     53    174   123.076923
6    구로구  1561       1142    173    246    323    86.705202
7    금천구  1015        674     51    269    354   594.117647
8    노원구  1265        542     57    451    516   805.263158
9    도봉구   485        238    159     42    386   142.767296
10  동대문구  1294       1070     23    198    579  2417.391304
11   동작구  1091        544    341    103    314    -7.917889
12   마포구   574        314    118    169    379   221.186441
13  서대문구   962        844     50     68    292   484.000000
14   서초구  1930       1406    157    336    398   153.503185
15   성동구  1062        730     91    241    265   191.208791
16   성북구  1464       1009     78    360    204   161.538462
17   송파구   618        529     21     68    463  2104.761905
18   양천구  2034       1843    142     30    467   228.873239
19  영등포구   904        495    214    195    373    74.299065
20   용산구  1624       1368    218    112    398    82.568807
21   은평구  1873       1138    224    278    468   108.928571
22   종로구  1002        464    314    211    630   100.636943
23    중구   671        413    190     72    348    83.157895
24   중랑구   660        509    121    177    109    -9.917355

In [38]:
# df의 데이터 중 2013년 이전 cctv 수가 2014년~2016년 누적치보다 많은 데이터를 추출하세요.
cond = df['2013년도 이전'] > df['2014년']+df['2015년']+df['2016년']
df[cond]

     기관명    소계  2013년도 이전  2014년  2015년  2016년          증감률
5    광진구   707        573     78     53    174   123.076923
6    구로구  1561       1142    173    246    323    86.705202
10  동대문구  1294       1070     23    198    579  2417.391304
13  서대문구   962        844     50     68    292   484.000000
14   서초구  1930       1406    157    336    398   153.503185
15   성동구  1062        730     91    241    265   191.208791
16   성북구  1464       1009     78    360    204   161.538462
18   양천구  2034       1843    142     30    467   228.873239
20   용산구  1624       1368    218    112    398    82.568807
21   은평구  1873       1138    224    278    468   108.928571
24   중랑구   660        509    121    177    109    -9.917355

In [39]:
# df의 데이터 중 전체 cctv 누적 cctv 수가 2013년도 이전 cctv수보다 두 배 이상으로
# 증가한 지역의 데이터를 출력하세요.
cond = (df['소계']/df['2013년도 이전']) >=2
df[cond]

    기관명    소계  2013년도 이전  2014년  2015년  2016년         증감률
0   강남구  2780       1292    430    584    932  116.744186
1   강동구   773        379     99    155    477  381.818182
2   강북구   748        369    120    138    204   70.000000
3   강서구   884        388    258    184     81  -68.604651
8   노원구  1265        542     57    451    516  805.263158
9   도봉구   485        238    159     42    386  142.767296
11  동작구  1091        544    341    103    314   -7.917889
22  종로구  1002        464    314    211    630  100.636943