# [실습] RAG 파이프라인 성능 평가하기   

지금까지 RAG의 성능을 높이기 위한 다양한 방법에 대해 알아봤는데요.   
실제 RAG의 성능은 어떻게 측정해야 할까요?

이번 실습에서는 정답이 존재하는 RAG 데이터를 이용해, 성능을 평가하는 과정에 대해 알아보겠습니다.

### 라이브러리 설치  

랭체인 관련 라이브러리와 벡터 데이터베이스 라이브러리를 설치합니다.

In [ ]:
!pip install sacrebleu ragas dotenv langchain_huggingface jsonlines langchain==0.3.27 langchain-openai langchain-community==0.3.27 beautifulsoup4 langchain_chroma

Collecting sacrebleu
  Downloading sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
Collecting ragas
  Downloading ragas-0.3.2-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: dotenv in c:\users\noto\miniconda3\lib\site-packages (0.9.9)
Requirement already satisfied: langchain_huggingface in c:\users\noto\miniconda3\lib\site-packages (0.3.1)
Requirement already satisfied: jsonlines in c:\users\noto\miniconda3\lib\site-packages (4.0.0)
Requirement already satisfied: langchain in c:\users\noto\appdata\roaming\python\python313\site-packages (0.3.27)
Requirement already satisfied: langchain-openai in c:\users\noto\appdata\roaming\python\python313\site-packages (0.3.30)
Requirement already satisfied: langchain-community in c:\users\noto\appdata\roaming\python\python313\site-packages (0.3.27)
Requirement already satisfied: beautifulsoup4 in c:\users\noto\miniconda3\lib\site-packages (4.13.4)
Requirement already satisfied: langchain_chroma in c:\users\noto\appdata\roaming\python\python313\site-packages (0.2.5)
Requirement already satisfied: chromadb in c:\users\noto\appdata\roaming\python\python313\site-packages (1.0.20)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in c:\users\noto\appdata\roaming\python\python313\site-packages (from sacrebleu) (2025.7.34)
Collecting tabulate>=0.8.9 (from sacrebleu)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\noto\appdata\roaming\python\python313\site-packages (from sacrebleu) (2.3.2)
Requirement already satisfied: colorama in c:\users\noto\appdata\roaming\python\python313\site-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in c:\users\noto\miniconda3\lib\site-packages (from sacrebleu) (6.0.1)
Requirement already satisfied: datasets in c:\users\noto\miniconda3\lib\site-packages (from ragas) (4.0.0)
Requirement already satisfied: tiktoken in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (0.11.0)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (2.11.7)
Requirement already satisfied: nest-asyncio in c:\users\noto\miniconda3\lib\site-packages (from ragas) (1.6.0)
Collecting appdirs (from ragas)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting diskcache>=5.6.3 (from ragas)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: langchain-core in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (0.3.74)
Requirement already satisfied: typer in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (0.16.1)
Requirement already satisfied: rich in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (14.1.0)
Requirement already satisfied: openai>=1.0.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (1.100.2)
Requirement already satisfied: tqdm in c:\users\noto\appdata\roaming\python\python313\site-packages (from ragas) (4.67.1)
Collecting instructor (from ragas)
  Downloading instructor-1.11.2-py3-none-any.whl.metadata (11 kB)
Collecting gitpython (from ragas)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pillow>=10.4.0 in c:\users\noto\miniconda3\lib\site-packages (from ragas) (11.3.0)
Requirement already satisfied: python-dotenv in c:\users\noto\appdata\roaming\python\python313\site-packages (from dotenv) (1.1.1)
Requirement already satisfied: tokenizers>=0.19.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain_huggingface) (0.21.4)
Requirement already satisfied: huggingface-hub>=0.33.4 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain_huggingface) (0.34.4)
Requirement already satisfied: langsmith>=0.3.45 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (0.4.15)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: PyYAML>=5.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (6.0.2)
Requirement already satisfied: typing-extensions>=4.7 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (4.14.1)
Requirement already satisfied: packaging>=23.2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-core->ragas) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\noto\appdata\roaming\python\python313\site-packages (from jsonpatch<2.0,>=1.33->langchain-core->ragas) (3.0.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from jsonlines) (25.3.0)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain) (0.3.9)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain) (2.0.43)
Requirement already satisfied: requests<3,>=2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain) (2.32.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pydantic>=2.0.0->ragas) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from pydantic>=2.0.0->ragas) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from requests<3,>=2->langchain) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\noto\appdata\roaming\python\python313\site-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from requests<3,>=2->langchain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\noto\appdata\roaming\python\python313\site-packages (from requests<3,>=2->langchain) (2025.8.3)
Requirement already satisfied: greenlet>=1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.4)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from openai>=1.0.0->ragas) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from openai>=1.0.0->ragas) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from openai>=1.0.0->ragas) (0.10.0)
Requirement already satisfied: sniffio in c:\users\noto\appdata\roaming\python\python313\site-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: httpcore==1.* in c:\users\noto\appdata\roaming\python\python313\site-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\noto\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0.0->ragas) (0.16.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-community) (3.12.15)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-community) (2.10.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langchain-community) (0.4.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.20.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community) (1.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\noto\miniconda3\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: build>=1.0.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.3.0)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.4.2)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.35.0)
Requirement already satisfied: posthog<6.0.0,>=2.4.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (5.4.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.22.1)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.36.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.36.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.36.0)
Requirement already satisfied: pypika>=0.48.9 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (0.48.9)
Requirement already satisfied: overrides>=7.3.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (1.74.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (4.3.0)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (33.1.0)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (5.2.0)
Requirement already satisfied: orjson>=3.9.12 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (3.11.2)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from chromadb) (4.25.1)
Requirement already satisfied: six>=1.5 in c:\users\noto\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from posthog<6.0.0,>=2.4.0->chromadb) (2.2.1)
Requirement already satisfied: pyproject_hooks in c:\users\noto\appdata\roaming\python\python313\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: filelock in c:\users\noto\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from huggingface-hub>=0.33.4->langchain_huggingface) (2025.7.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\noto\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\noto\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from jsonschema>=4.19.0->chromadb) (0.27.0)
Requirement already satisfied: google-auth>=1.0.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (2.40.3)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests-oauthlib in c:\users\noto\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in c:\users\noto\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: durationpy>=0.7 in c:\users\noto\appdata\roaming\python\python313\site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\noto\appdata\roaming\python\python313\site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from rsa<5,>=3.1.4->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langsmith>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from langsmith>=0.3.45->langchain-core->ragas) (0.24.0)
Requirement already satisfied: coloredlogs in c:\users\noto\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\noto\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (25.2.10)
Requirement already satisfied: protobuf in c:\users\noto\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (6.32.0)
Requirement already satisfied: sympy in c:\users\noto\appdata\roaming\python\python313\site-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.0)
Requirement already satisfied: zipp>=3.20 in c:\users\noto\appdata\roaming\python\python313\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\noto\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.70.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.36.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.36.0)
Requirement already satisfied: opentelemetry-proto==1.36.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.36.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.57b0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.57b0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: click>=8.0.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from typer->ragas) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\noto\appdata\roaming\python\python313\site-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: httptools>=0.6.3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.6.4)
Requirement already satisfied: watchfiles>=0.13 in c:\users\noto\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.0)
Requirement already satisfied: websockets>=10.4 in c:\users\noto\appdata\roaming\python\python313\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\noto\appdata\roaming\python\python313\site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb) (10.0)
Requirement already satisfied: pyreadline3 in c:\users\noto\appdata\roaming\python\python313\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb) (3.5.4)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\noto\miniconda3\lib\site-packages (from datasets->ragas) (21.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\noto\miniconda3\lib\site-packages (from datasets->ragas) (0.3.8)
Requirement already satisfied: pandas in c:\users\noto\appdata\roaming\python\python313\site-packages (from datasets->ragas) (2.3.2)
Requirement already satisfied: xxhash in c:\users\noto\miniconda3\lib\site-packages (from datasets->ragas) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\noto\miniconda3\lib\site-packages (from datasets->ragas) (0.70.16)

In [2]:
import os
from dotenv import load_dotenv
load_dotenv('.env', override=True)

if os.environ.get('OPENAI_API_KEY'):
    print('OpenAI API 키 확인')

OpenAI API 키 확인

In [5]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4.1-nano", temperature = 0, max_tokens = 4096)
# 4o : Context 128k - 200k
# 4.1 : Context 1M
# 4o-mini > 4.1 Nano

RAG의 평가를 위해서는 정답이 있는 Q/A 데이터가 필요합니다.   
실습 시트에서 eval.jsonl을 다운로드하여 불러옵니다.

In [7]:
import pandas as pd

evaluation_dataset = pd.read_csv('./eval_dataset.csv', encoding='cp949')
evaluation_dataset

,questions,ground_truths
0,"2022~2024년 삼성SDS의 매출 구성을 IT서비스와 물류 관점에서 비교하고, ...",공시자료에 따르면 전체 매출에서 IT서비스와 물류 비중은 2022년 34.6% 대 ...
1,"삼성SDS가 ‘클라우드 기업’으로 전환한다고 밝힌 바 있는 전략을, 제품·플랫폼·인...",제품·플랫폼 측면에서 회사는 SCP를 전개하며 CSP·MSP·SaaS를 End-to...
2,"물류 부문에서 삼성SDS가 디지털 포워딩 경쟁력을 어떻게 구축했는지, 플랫폼 진화와...",삼성SDS는 통합물류 플랫폼 Cello와 디지털 물류 플랫폼 Cello Square...
3,"회사가 서비스 가격표를 제시하지 않는 이유와 실제 가격 결정 방식은 무엇이며, 이는...",공시자료는 IT서비스(SI·ITO·클라우드)와 물류가 개인용 규격 상품이 아니라 고...
4,"경기변동이 IT서비스와 물류에 미치는 영향과, 삼성SDS가 그 민감도를 낮추기 위해...","IT서비스는 기업 설비투자와 연동돼 경기 둔화 시 투자 보류 영향이 있으나, 클라우..."
5,SRM 분야에서의 인수·출시 활동이 삼성SDS의 SaaS 전략과 글로벌 확장에 어떤...,회사는 2023년 2분기에 국내 1위 SRM 기업 엠로의 지분 인수를 완료해 핵심 ...
6,인력·시설·보안 측면에서 삼성SDS의 운영 기반과 이것이 서비스 신뢰성에 주는 함의...,"2024년 말 기준 연결 인력은 약 25,666명으로, IT서비스 16,798명, ..."
7,"재무 안정성 측면에서 회사의 공시 내용을 종합하되, 상장 이력과 조달 구조까지 연결...","삼성SDS는 2014년 11월 14일 유가증권시장에 상장했으며, 단기 조달 수단인 ..."
8,삼성SDS의 2024년 3분기말(9월 30일) 연결 기준 부채비율을 재무상태표 수치...,"2024년 3분기말 연결 기준 부채총계는 3,409,626,256천원, 자본총계는 ..."
9,2024년 3분기 누적과 2024 사업연도(사업보고서 기준)에서 삼성SDS의 희석주...,삼성SDS는 당기 및 전기에 희석증권을 보유하지 않아 희석주당이익이 기본주당이익과 ...
10,"2024년 삼성SDS의 주식기준보상(엠로 포함) 현황을 수량, 행사가격, 만기, 비...",연결실체 종속회사 (주)엠로의 주식매입선택권이 2024년 보고기간에 연결 주식기준보...
11,"온실가스 배출권과 배출부채에 대해, 2024년 중 배출권 수량·장부금액 변동과 기말...","삼성SDS는 3차 계획기간(2021~2025년)에 대해 무상할당을 받고 있으며, 당..."
12,"특수관계자와의 배당거래는 2024년에 어떻게 이루어졌으며, 연결 현금흐름에서의 배당...","사업보고서 특수관계자 주석에 따르면, 2024년 중 특수관계자로부터 수취한 배당금은..."
13,2024년 9월말까지 삼성SDS 연결 자본(지배주주지분)은 어떤 요인들로 증가·감소...,"지배주주지분은 2023.12.31의 8,658,009,435,402원에서 2024...."
14,"2024년 3분기 누적 연구개발(R&D) 활동과 비용은 어떤 특징을 보였는지, 매출...","2024년 3분기 누적 연결 기준 연구개발비용 총계는 175,502,420천원이며,..."
15,삼성SDS가 2024년 3분기 (주)동아미디어엔 보통주 18.01%만을 보유하면서도...,2024년 3분기 공시에 따르면 (주)동아미디어엔은 지분율이 20% 미만(18.01...
16,삼성SDS가 2024년 중 한국정보인증(주) 지분을 전량 처분한 사실이 연결재무제표...,관계기업투자주식 주석에 “한국정보인증(주) 당분기 중 전량 매각”이 명시되어 있으며...
17,만약 삼성SDS가 CMC Corporation(현재 유효지분율 약 29.83%)의 ...,"K-IFRS에 따르면 단계적 취득으로 지배력을 확보하는 경우, 기존에 보유하던 관계..."
18,2024년 중 삼성SDS의 종속기업 지분 관련 변동을 별도·연결 재무제표 관점에서 ...,2024년에는 신규 사업결합이 없었습니다(연결 현금흐름표 ‘사업결합으로 인한 순현금...
19,"삼성SDS가 향후 종속회사와의 합병을 추진하는 경우, 사내 거버넌스와 주주총회 절차...","회사 이사회 규정에 따르면 합병·분할·분할합병 등은 이사회 부의사항이며, 주주총회 ..."

기존 데이터를 불러옵니다.

In [ ]:
from glob import glob
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_core.documents import Document

pdf_files = glob("reports/*.pdf")
pdf_files

# 각 PDF 파일에서 페이지별로 내용을 불러와 하나로 합침
all_papers=[]

for i, path_paper in enumerate(pdf_files):
    loader = PyMuPDFLoader(path_paper)
    pages = loader.load()
    doc = Document(page_content='', metadata = {'index':i, 'source':pages[0].metadata['source']})
    for page in pages:
        doc.page_content += page.page_content +' '

    doc.page_content = doc.page_content.replace('\n', ' ')
    for _ in range(10):
        doc.page_content = doc.page_content.replace('  ', ' ')
        doc.page_content = doc.page_content.replace('..', '.')

    all_papers.append(doc)

print(len(all_papers))
all_papers[0].page_content[:1000]

3

'목 차 반 기 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 1. 회사의 개요.3 2. 회사의 연혁.5 3. 자본금 변동사항.8 4. 주식의 총수 등.9 5. 정관에 관한 사항.10 II. 사업의 내용.12 1. 사업의 개요.12 2. 주요 제품 및 서비스.13 3. 원재료 및 생산설비.17 4. 매출 및 수주상황.19 5. 위험관리 및 파생거래.20 6. 주요계약 및 연구개발활동.22 7. 기타 참고사항.25 III. 재무에 관한 사항.34 1. 요약재무정보.34 2. 연결재무제표.37 2-1. 연결 재무상태표.37 2-2. 연결 손익계산서.38 2-3. 연결 포괄손익계산서.39 2-4. 연결 자본변동표.39 2-5. 연결 현금흐름표.40 3. 연결재무제표 주석.42 1. 지배기업의 개요 (연결) .42 2. 연결재무제표 작성기준 및 중요한 회계정책 (연결).42 3. 중요한 판단과 추정 불확실성의 주요 원천 (연결) .43 4. 영업부문 (연결) .44 5. 범주별 금융상품 (연결) .46 6. 공정가치 (연결) .48 7. 공정가치측정금융자산 (연결).51 8. 관계기업투자주식 (연결).54 9. 종속기업 (연결) .58 10. 유형자산 (연결) .67 11. 무형자산 (연결) .68 12. 투자부동산 (연결).69 13. 리스 (연결) .71 14. 리스부채 (연결) .73 15. 금융리스채권 (연결).74 16. 충당부채 (연결) .76 17. 재무위험관리 (연결).79 18. 우발채무와 약정사항 (연결) .81 19. 납입자본 (연결) .83 20. 이익잉여금 (연결).84 21. 기타자본항목 (연결).85 22. 매출액 (연결).86 23. 판매비와 관리비 (연결).89 24. 기타수익 및 기타비용 (연결).91 25. 금융수익 및 금융비용 (연결).92 26. 법인세비용 (연결).93 27. 현금흐름표 (연결).94 28. 주당이익 (연결) .96 29. 특수관계자 (연결).97 30. 주식기준보상 (연결).109 4. 재무제'

Chunking을 수행합니다.

In [9]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    model_name='gpt-4o-mini',
    chunk_size=1000, chunk_overlap=200)

chunks = text_splitter.split_documents(all_papers)
print(len(chunks))

740

Embedding 모델을 구성합니다.

In [10]:
from langchain_openai import OpenAIEmbeddings
openai_embeddings = OpenAIEmbeddings(model='text-embedding-3-large', chunk_size=100)

ChromaDB를 구성합니다.

In [11]:
from langchain_chroma import Chroma

Chroma().delete_collection() # (메모리에 저장하는 경우) 기존 데이터 삭제

# DB 구성하기
db = Chroma(embedding_function=openai_embeddings,
            persist_directory="./evaluation",
            collection_metadata={'hnsw:space':'l2'},
            )

DB에 document를 추가합니다.

In [12]:
db.add_documents(chunks)

['14621a59-892a-4e10-ac8e-7df0f569b3c2',
 'd5f66c1d-77c4-4500-af58-b80d4c2addd0',
 'f86457ae-eaeb-491d-ab0a-c43a1514e927',
 'c9604467-4524-4f9b-b921-ba11c7c377b9',
 '58b569ff-c469-4084-9ef9-87639f0de059',
 '1fa07958-3242-4659-85f9-8dd52f2a7e40',
 '1fb67761-bab6-4b4c-ab6e-712e20e04678',
 'c540e92b-a6ab-4464-b885-b6bb8d45a6f8',
 'a309652b-2d84-43cd-bf26-15b6f91a2657',
 '3dec8683-54ce-4576-af56-67f40d284d04',
 '898766e6-b9c7-4f05-92d5-382ffacd0841',
 'f0224abe-1074-43d9-936e-be2a8df1de0a',
 '4eeb8d4b-aa28-4b50-9623-fea182d6b537',
 'a3ef0d01-188f-49b9-97b4-468cd9e2ac10',
 '523a54f3-ecb3-4ac6-8ea6-7521c3a911b3',
 'b3541f07-ffc7-41cc-a66d-0153d6d9952e',
 '16c46a29-3eb9-47aa-85a2-dd1ef67d6791',
 '3ccf2d5f-90fc-43a5-8d85-c0c871da6457',
 '48812889-aadb-4805-b916-60b0531755fa',
 'c11d63d1-e3dc-415a-b6c3-a0f201a4f09d',
 'f2da2083-2c43-4525-9af0-1885d1436f07',
 '73a6b871-741c-47c8-9ecb-c492a3d32c9b',
 '8f464169-cacd-42bf-85ec-e06a2f156200',
 'feacb5d4-dcba-4378-bbe0-6f7084da97af',
 '5a557f49-81dc-4245-9eeb-4b1fded3be09',
 '30c0b1e1-9ecc-46b1-b8c9-e202b0b82751',
 'bec72adb-20d1-49c1-8222-923f2208d7f1',
 'd9472626-b57f-4885-bdf4-6ccae80d2217',
 '0b1ef861-d89e-4ccd-b548-de9c7f85be4c',
 '8b1c22ec-91c9-4e22-a905-9a8b70b48a79',
 '014e1b8c-b2b5-45ec-8daf-548fa63910da',
 '03b31191-7958-4950-9d71-1836bd4a0126',
 '22dd9b4f-ea23-4736-a9c2-b92b38937d6f',
 '655dcda6-bb63-4eea-b6ef-e2611da1de16',
 '5bdd5277-50fb-48cd-92c8-965c0252473c',
 '4a256a5f-b13f-4fc3-820f-4cfe54571ba4',
 '792faa7d-d37c-43a8-9d64-5a69f9c206fe',
 '3201dc16-0688-460d-b184-1d72186f6bba',
 'd500ede5-a4ad-47e2-833b-47b0e2cdcfb7',
 'd690f893-3275-44b7-baa9-f95d0a1a82b2',
 '658ac285-1d76-41b4-b062-6dbcb028af15',
 'b1740abe-0ff0-4363-a300-46f074e5fbe0',
 '8497c49a-40b0-4e75-9901-8aba73c0b932',
 '3a197619-1e55-4efd-a1f3-4d644e00e797',
 '7588d839-9dd9-474c-b28d-8136f4695cc3',
 '726f83cf-fe05-49fe-a2b3-146c7c5785cb',
 '5e5f2139-ab68-41eb-ac11-fdb144787876',
 'bbee2fa7-813d-4293-a118-1bd3c3723b0f',
 'd3f320ec-b28f-4671-9021-1b48627a22e9',
 'ca227c78-f11e-4e2b-be3c-8ee48fd97e2a',
 '4f74f58b-7c66-4385-9b6d-ad710ad18f7c',
 '3b2318cc-f220-4871-8cf2-ceacf980e199',
 'a6223f06-e081-427c-9907-319176cdf15f',
 'fbb1e677-1e7f-4cdf-bfdb-6b3bd4066a63',
 '9622a281-8666-4cf5-be5c-29d40896090d',
 '0ebca358-9a47-413b-8246-07ac54753218',
 '53efe84c-3407-401f-bb45-df42ae9b69dc',
 '546593f6-80df-4b77-a570-4a0a2e1c946b',
 'ed531fc0-5a6b-4999-b79b-4a0e32b6f260',
 '4cb23da5-f6a8-482d-98f5-6cffd061d9ca',
 '4e16eee3-77f5-4d35-a7fd-1ab79cfc7744',
 '26ba85c7-50b6-4824-b0c6-ba1831475ac9',
 '7b9aea24-430c-4fb9-9b17-454eea0ba296',
 '89eeecd7-c6bb-45b3-b2e2-3fded7ade85d',
 '767e850e-01ac-4497-b1b3-5f9faf3d888d',
 'd2a35612-ad89-4c03-a341-13113eb9e174',
 '02975d6d-08b1-4be2-acda-20ce133e04ef',
 'eb5a5611-c537-4af3-9cae-2b19472c67fd',
 '947d493d-9cc3-4940-a3c7-9cc2a65a6c2f',
 '13397eda-92c9-4875-a94d-ddf07e588082',
 '43d98d72-ccb2-4099-88b3-2f1a5a9c6b7c',
 '94f16fc7-ebaf-453c-8742-5f5d5a5a2b0c',
 '09847a2d-adb2-434c-85da-f18caeb121fb',
 '8b84fb32-3ad4-4cc9-8e3a-7bd53b678103',
 '8aff78e3-3cd2-4fe5-9750-5aafe5e273d3',
 'f9eca294-a1d5-46a6-b34a-f4bccc65bce9',
 '804b350a-4683-4262-af21-8a26d009c89a',
 '087f7bfd-f6c7-4c53-bcf2-031033338943',
 '1b79492d-f974-4883-9a84-ce58fcfbc78e',
 'af8e5b80-53e5-4f8c-a2b8-afef01f4aecb',
 'a1c9fcbf-c993-45d9-9c0a-4b0c20213980',
 'f78353ce-2d73-46eb-8843-0199c61ec523',
 'f079389b-36a4-4338-a543-a21931a5bbde',
 'fa8536a8-f87b-4b5c-8dba-0f9d4f8a3b5f',
 '47d3114b-a467-4dd4-974a-5e37d677aefb',
 '38fd6444-3ff9-4627-b07d-b6ae6ce835f6',
 'e8576e25-e73a-4134-b479-185b8b531632',
 'c1664914-66b9-41cf-8d0e-1310bac1d4d3',
 '7c4fad63-1f1f-4cc1-8c28-52ca9df6a6bf',
 '7c433779-867c-4cab-8c37-f0a0a4aa468e',
 '931f9cf9-fa98-477a-b44e-31e9bec3c9ef',
 '3de02ae6-c234-4a00-ac73-5a41d3ad3bea',
 '1338e9a5-6a20-49a4-aa24-a50e2125b591',
 '647836d0-659a-488b-b97a-ff4a3948b5c5',
 'c4e0ea97-38ee-423f-bc2e-f217f09a8701',
 'e2d480b7-7438-4c8b-bbbd-818bc025b602',
 '197d397b-8495-46ac-bd7c-53a8b72f1772',
 '21af87d1-a244-421a-9459-3868aab9bbbc',
 'b25f8ff5-0279-45c1-971b-330b05f06cda',
 'd4ab0169-1677-42f6-bf9d-aedaae8dee4c',
 'de9eb4d2-6b18-4e5e-825a-1c295793c2a9',
 '52ea2128-485e-465b-ab9a-77189edded52',
 '3458fd92-db5d-4e93-935c-2b4da831c775',
 '6357ab34-f6ac-4728-9a05-c5e0d4170e47',
 'f1d47817-24e5-4923-a16e-4dd91741fd3a',
 'e714678b-cba2-4987-9d7d-932300a34fdd',
 'b677af38-0b60-41d1-bdfa-291d8d170132',
 'fe0f76e2-b8f3-4995-bed1-966b4fd7deb5',
 'c0fabc79-3276-4004-bd11-438b064429c7',
 'e810aab3-6585-432b-9be8-1e781cf5ddb2',
 '172a1cbe-c061-44f5-839f-a42eebcd0629',
 '22bae1df-7191-4484-9eaa-41187aae9241',
 '01c8a9a0-901d-4a78-bc09-ab70d37bfa0c',
 '15272ddc-afff-4158-a098-2497a548f550',
 '4be4e5dc-b7f5-434b-b6ca-30dc7e8381e3',
 '4e303668-e00c-49cd-824d-8782d1027dd2',
 'd51158de-8e79-44ae-92d6-267e72e9754a',
 'afd573d2-963f-4e5b-b3bc-f1e1b8085ff6',
 '6ce66ff3-3d11-49a5-b099-e0e3ab9f3409',
 'f5ccbc0b-336e-4a92-9832-4e25944d5f73',
 '16cdfeba-8f0b-4980-9c8d-f68fd78f68e9',
 '1cea78b9-adcb-44ac-b82d-7e203bb482b1',
 '86c334c4-48b9-4fc5-b349-8d3a467639b7',
 '0816f14b-f532-40b6-9467-af3332dd1380',
 '0d99a1fb-8826-45ad-9cdb-cb50d8b98937',
 '9bd4479c-028e-4662-be51-f46c6f4adfa4',
 'ef2233c6-7308-4be2-89ff-7c2a5b6e19aa',
 '533b1219-218d-4d90-8ff4-c6bc07149f2b',
 '75ef0cdb-5f7d-413f-83a0-54e2b2777e20',
 'cf83d8cd-90eb-4572-97de-c305096ef9b5',
 '7daf5cb0-bb70-40f3-81ee-0fcbf37e1174',
 'd8ab7a93-4ff9-4dc8-b5e8-05c9281f1d26',
 '37323d8a-332f-4511-bd1b-5d188ee30240',
 'c2d38240-bd0a-4eba-b253-8aa6bc1c588b',
 '55b14fb0-d067-4ab9-9999-3ad5096e8077',
 '6d82fb1b-296b-4af0-9523-8f695c58cd48',
 '1de1d2f6-0335-4481-a674-dfa4f5b8ee42',
 'c87fc71e-89c0-4c97-ac1a-ab9d88406c2f',
 '431c9777-661b-47df-9f55-27cd32039d50',
 'c8d8a6e0-53de-426f-bcc9-a6c5944bcb85',
 'ce86fa88-22d2-4ae9-adcb-4a90df6f683a',
 '2804ec3b-48b5-4ab9-8ff3-d00de3749a15',
 'd2994704-8ba5-4b22-a03b-2a2c8d58b371',
 '56821981-8d15-4a96-a1d8-cd7a879d8718',
 '708bc338-f1e2-4628-87bc-fe2f43ee75eb',
 'c02a92c3-ee8e-4b39-953a-003dc0ace035',
 '7ffe6398-8eee-4628-b0ed-53ecb344fed3',
 'a3d66795-e609-4081-808f-def39083aa31',
 '2ec6fd57-cea4-44d3-b4ea-c4d8acad4e23',
 '2b1a83be-9405-4614-80a8-36649c68ac13',
 '34628de5-fda7-4e15-9892-e773c4019530',
 'c3c30479-ce03-43dc-862a-f8e26ed3d441',
 '26142004-42d4-4eb7-9783-35943bf9afac',
 '4a1e8051-8a22-483d-8aee-2edde7b49d12',
 '5d9cb4f7-2df0-4b04-816a-d62a0a893493',
 '873b5aa5-96d1-4a40-aa28-47243b6bb13e',
 '59be3bc5-ceec-4395-a768-4f125e9bbdd8',
 '1b79438a-618e-4b1d-bc12-a21f616d2157',
 '62dd997a-607d-4efc-8fc4-1645c7b97f03',
 '53ded9d4-ae7b-453e-88d9-8456bebf3298',
 'efe771cc-016b-46e2-926f-e3d9fc9e7be7',
 '12c8047e-c54a-493a-8235-2ed0b9b57633',
 '9a6370a0-2d21-4cce-a821-18d8a035a002',
 'cfe44be8-1ab5-4d73-a974-f5e61d181f96',
 '2ba465ca-b840-4aef-830f-d37da2cd251c',
 'bd253561-7726-43cd-a200-391d387d3419',
 '606c8253-7f88-4ea0-bd02-52a6ebb7193a',
 'e805f841-c053-45a0-b445-c901e376b497',
 'b3ec1b10-0e0c-43d7-93e6-dec8d6772fab',
 '0f6c5477-e632-4f8b-bdfa-8c72337386da',
 '292f758f-e9e3-44fa-9dac-82156d7e04a0',
 '35d32cf2-5bb5-468e-bd18-e9cfb2900e03',
 'acbb86ab-c3e9-482a-9f6f-66a46a60c3d5',
 'e72fc1be-6080-437a-b949-e55d44ce52bd',
 'd0a83f83-c0c0-4d68-a330-1bb9aaf224fe',
 '7fe1400f-150c-460f-a2e5-8634540c9fd3',
 'b5a01ac3-578b-45e2-b9a8-2a3a0316aa74',
 'cc9621b1-0ed2-4e63-9887-e27b7f1f060c',
 '9f5e3563-667e-4aec-9b4b-e6a54a9b7c8e',
 'ad24e5d8-228e-45ea-8bf8-12604c036a44',
 'ec991572-bb2a-43bc-acf8-d68cb38a6225',
 '21f83bb3-e2fc-463f-bca2-bf7f82096dcd',
 '9288efa1-24b2-450e-ae8c-85e35d81c02f',
 '1fab093d-bb34-4b39-a0bb-7135b9ca665f',
 '2c3e0749-8fa2-444f-87d3-dbbda6ff1862',
 '5e5660d9-81ab-45be-b48d-79bb0010543f',
 'c57fabb5-e313-4357-9959-74fd2d4b5037',
 'c98b5208-6564-466a-86bb-21cd70da5062',
 '9969a73b-e1fc-4200-ab89-e4a538140ba5',
 '267347f1-0921-49cd-b1ca-2bd54d50ce59',
 '5dff85cd-f329-4a81-a00a-047617ef5dea',
 '99ffbb21-4606-4d58-bcee-b5f2bd213e3a',
 '6fb05b99-0263-4401-966f-dddd44255dda',
 '68819b07-81c1-420a-aef8-1d5caf7222c0',
 'dcd48204-fd90-4f1e-9112-43e63c655eec',
 '3b76d29b-21ff-4443-bc59-a0b58d96d44a',
 'c759c492-d9f8-44be-8881-8e3d27d90930',
 'caf6944f-0de3-429c-93f3-2a2b6daba6af',
 'b3c5ab64-6f0a-43f8-8dbf-8d9936443de7',
 '78670ebe-9caa-42b7-bf52-3bde6aba879a',
 'c1e66015-31c6-4f73-adc3-2dcc8971fc1f',
 'd2a994a0-c001-4146-a7be-f0888a093470',
 'b19ec24d-0830-4adf-a1d4-8043060e0369',
 '95d69d54-4f6e-43a4-b33b-63fb125e56f0',
 'ad207990-9b75-48d5-b8c4-29946c611101',
 'ab2208e3-beef-4e8a-8258-66b97624d384',
 'b243a6ef-367e-4663-ba0e-d3ca135e9d59',
 'fe97ea9d-9a87-4f7d-8159-f4e7acca7ec8',
 '5d39d738-53f5-4548-bd41-2289a9c98214',
 '6ee7338a-58fc-4c38-97bd-a2f8ad62b200',
 '5466d78a-3584-453a-96ba-3974b0c89f6e',
 'f7040eb9-b67d-4d07-8ae5-151b4cfd8903',
 'f29d92b3-6811-4d11-bbe4-493a947d9f4c',
 '5ba472e4-54bd-4803-9aa7-4db263bf0807',
 'f9a2d654-3364-4d91-96df-a2f9ea646498',
 'b08b71f1-5695-4d68-8bf0-7012701d7213',
 'aa495433-d109-4285-a456-2f62efc1f90d',
 '05a65f35-0bfa-41f4-838f-aab639fabee1',
 'ba58a723-2c13-451e-a1a3-e91601a51579',
 'c3f9fc14-8496-4ebc-914f-ba249fc50c75',
 '379948ba-abb0-49b3-9530-355e4a32f2c4',
 '55b02996-3708-4f37-9e90-f124a71a61ed',
 '49030738-d3e3-4bbc-8976-01844c2a524c',
 '3bcf9cc8-ee34-4eb9-9d1b-e8f3f366267e',
 '01e67287-8ad7-45b6-a70e-423c95e22dbf',
 '77fe91ce-faae-4e17-b44c-689dbd1922a2',
 'b091d96e-625e-472d-8517-5eddccf60251',
 'fbee4287-846f-4f88-8a5b-2c93fb5f3e35',
 '2e3a9c9a-41f9-4c48-9c11-57abc1e4c663',
 '890650c2-180b-4f62-82e7-502553a62823',
 '16e84624-0fc2-49d0-9037-cd6127782fbb',
 '02c2e732-db60-408d-bce6-a322ffcccd47',
 'bb5381fb-224a-47ae-8ac5-4e775c33fbbd',
 'd913569e-f44d-47ae-9b65-027706986ed1',
 '252d3121-3a07-45c3-9af7-4453668e7ae0',
 'fe238fda-4e53-499d-8356-e432d504278e',
 'b0b213b1-0d69-4c18-a464-b889cf6879b1',
 '3310154e-b438-409a-b55e-dc19daa06945',
 '430a8779-5bd7-47ac-82f1-461633ecf856',
 '0d86c0dc-ed9b-4f26-b97b-2947485e6faa',
 '6b8d99f8-323b-43cb-8ac8-efcd52933a13',
 '2081bff2-c819-48e7-945b-37b1512e5130',
 'd100a747-7523-4498-969f-30178e906ce4',
 'd92ebdcc-9eae-4304-ad36-b6d07d168d18',
 'd9b1991c-7ee2-40f7-97c0-bc0a5b847a24',
 'dcc073b8-e56a-4990-908d-b39dfc7a1c79',
 '63e2cde7-4494-482a-b866-1cc988cefb71',
 'c5489ab6-963c-4d73-8a31-65a5d32e2ab9',
 'af12fd4a-f28c-43a1-bb27-dd283e5f6564',
 'd9ef82c3-3efc-4be3-a2d9-ceee5e694d81',
 '38946e68-a4a0-443e-96d1-03cd00ca51c4',
 'dac4505e-a269-4f0a-832e-7c7c0815b671',
 'a2d7d5fe-75b6-441c-8f61-0f1be7aca14d',
 'a26b9992-cd1a-4e07-b985-dc7477d4e739',
 '6b6d942b-9d3b-4389-b857-4a5197456201',
 'c56aab94-3702-48ce-92ab-7ecf1b29ccbe',
 '65b89a40-9d50-4682-835f-e056f234acec',
 '31b70d91-d865-4b0d-86bf-bf74572bcdd3',
 '853b04c6-08df-4f30-969a-f916b4c67c04',
 'ab6f2d5b-62e8-462d-a320-e0f989a042f9',
 'f2515b07-6047-46b2-ad4f-a00863b8dd12',
 '5aafb132-078a-4ab2-864c-20982b32e24f',
 '148997f2-6ea8-46fd-be34-e8beb05d6d39',
 '8ebf7c00-ac95-480d-9297-4cc8e9fd4cfc',
 'b13386f1-5513-4ec5-831c-f7e2eaff0dbf',
 '371df497-f064-427e-81d5-e8dc0faf47e8',
 '3990a8c1-1150-4cc9-9b01-0f4ac7553a58',
 '1721f5df-c0a0-4865-a6cd-26aaac5f1d55',
 '52f82a08-e58f-4913-b38d-bc80a5161dcd',
 '7d6f56f4-d8a4-4bdc-a39b-d20027e82502',
 '9b1958bd-a3a5-408a-b025-9f48328c8ff5',
 '258b2bbe-c9ba-413f-a146-31a62d94eb8e',
 'a65803f6-11d1-45c1-8f55-1bacea5eac3a',
 '3de6b6cf-1a65-4cb4-97eb-05b16afe0d72',
 'ba637fa8-af6d-4ea2-b163-9ef709542bc8',
 '2750d041-5456-4b45-8c59-0a0172c53ec0',
 '1c4a916a-3200-4817-ab2d-73c1a2c28418',
 '67b06db4-d62f-41e4-b993-4793a131ab71',
 '778b9caf-4309-4f03-b63a-5ad5b15282c5',
 '24afc0b2-1f78-4b64-a5be-856f52e63557',
 '90cb3693-35c4-408a-96b2-c0339f89fabe',
 '95a416c6-3df1-4192-a234-99ff8bf194c7',
 'e981a1ec-691e-496d-86ef-67074be26e85',
 '9ed7c8c1-295b-4304-bc4d-ec2c6b390683',
 '39b5ddc2-27ac-4793-a525-bb68cca5a521',
 'bb40d135-bb5f-4f56-9c07-af432be41518',
 '7703d6c9-ba55-40d4-afe7-fc4168a88ee6',
 '6b0ca584-471b-4905-a21d-363b3e0c2eaa',
 'e5df96f9-9371-45ae-9507-03faa4f16b7a',
 '31b95164-5090-44ba-a7bb-ac31c70ed226',
 'bad45ce7-2d42-4dce-9365-6b67c97a2487',
 '0f923457-417d-416e-a5cc-8b942489b89d',
 '17ecb699-b432-4c45-b0ec-116a8ae8bf07',
 '22e28477-307d-42e9-8abc-eac70e8bfc84',
 '178bd807-e52d-4308-a88a-178a1d4272f1',
 '48526646-c3c1-4144-91fa-0493e3ce95ff',
 'c285676f-9753-4034-b234-5c07525b3de2',
 '2e517ae9-294f-4f7d-8002-6a57c65b84d0',
 '3bf2ccd0-bf7f-411e-ae2a-8bee0ee9270c',
 '12d0b769-7159-4189-88e3-660e09b50843',
 '703dcffe-ec64-4160-876c-f8e07dd871e9',
 '2e041063-c536-45fc-8507-a1c4a7219997',
 '7dd0894b-4786-4b58-937d-29e7614a8ab3',
 '050bbdf1-4031-49eb-b693-63a79cba7941',
 '1c6271f5-ff36-4f49-8638-14c37062c186',
 '134e9e36-9dc3-4f20-ae2c-6c3ae7f58ff8',
 '85d33dd8-f467-47e8-bd1e-77fd3a809c0d',
 '24a408fc-0bbf-4636-95bb-e6069d5f125b',
 'a99acc10-032c-47b3-a4e0-4a0016deda63',
 'd2d469d5-20d3-49f3-9c45-8c0e5c60ad5b',
 'e08607be-4900-4343-aa74-b9a5cf233132',
 '5addf807-1d75-4d52-83e8-9e694e5718e8',
 'cebaf1bb-fbf6-45a5-b8ce-520ae9022403',
 'ff010f5f-b43f-4202-ac1c-6f2a344fc27f',
 '61b7b6ee-dd33-4494-bab2-6c6251d0a423',
 'eec30f4c-b348-4627-abb5-a1f73dd4a7ea',
 'd5ba148d-99e0-41ab-b3ac-1814dd7a60e7',
 '2cfb3828-d620-4fc1-951d-45551b5d5197',
 'c175d05e-a42d-481a-b208-a7fa094bbcb8',
 '5be1be6f-3ac3-4e91-a3e7-1f15eb10bd25',
 '0c4c0f90-9bd6-4a8e-bf95-4224e474332d',
 'c62205a3-f947-477b-b50b-85e19663dc94',
 'c99fddbc-8ba0-4b8d-82c7-2cee82c27713',
 '18164be3-923e-4856-a8ec-25a9ef2d7bf5',
 '9b8e039e-10b3-4d35-9677-32e59d63f7a9',
 '09c92439-3a32-45be-87db-b995e8159e8f',
 '07941b46-c7fb-4756-9ec2-ce21fbfd2c12',
 'fb847c08-74d3-4502-80f7-7fa4bc204193',
 'cc83ea08-7d61-4093-9803-a62464ad1c42',
 'fff5b117-ca5e-4bd6-ab47-2f2b564a2ad6',
 'a6d555e3-67d6-4d10-ba89-47212df5f39f',
 'adf2191b-6ac5-489a-8564-344cd1a86b20',
 '738c0b78-aa95-4e2a-9def-8c406205c2aa',
 'bf67987f-48a7-4080-8231-0fc0a69c9027',
 'd6590214-a59e-4e35-a080-62def28d414a',
 '997794cd-417b-4ba1-92f3-13d3acf19b25',
 '0b0c73bb-b3e4-4ba4-bc3f-bc0887c16bcd',
 '21dbc219-6baf-4469-ae76-1407d07c1031',
 'd51e4b90-e34f-407d-9078-2b0857179bfb',
 '565a19e9-aea1-449f-bb73-343d652e71fd',
 'e3499104-e378-41c3-9309-5d15c1b38143',
 '7ddb20b1-2fa8-48eb-9dae-38cd5698dcb5',
 '63677667-1ee0-45ba-96eb-03daf7cb9d50',
 '9ec8804f-17b6-48a5-9611-6745898a7888',
 '8d40b900-e871-412d-a889-d5e51ce23343',
 '10130242-df7c-4c70-aa4e-aaea3b2d3051',
 '157d807b-bc82-4db5-bce5-d330c2e167b7',
 '404964d2-2afd-4abd-96ed-6c14f3045281',
 'c3b4bb07-cc3c-40a9-87f8-a3b2b476f232',
 '2d17a6c5-e6bf-402e-ac04-db4d61725699',
 'd54de239-c8f8-4b13-8c73-f5baa00fb59a',
 '4abf7cf1-c152-485c-8e3b-412138bbb6ed',
 'b3b7fa88-7bda-4ddf-9578-b1009c1f14a5',
 '377ef377-c9ec-4450-86c7-db8db25bf53b',
 '1ea130b8-29c6-4e88-bb5f-ce4716d18f1c',
 '6bfa6a45-8f55-4733-af24-0732b2fc67e1',
 'ca9224d5-b181-4d65-af86-d1981788f116',
 '33d25e55-7c8e-4d97-93bb-d7c0e83ab25d',
 'b5ec82c9-139f-4022-82ef-734f033733d1',
 'e2b1162c-8c76-442f-98f4-f646350579f7',
 '451c4b32-8ccd-4cd4-b057-25d412fc4815',
 'c98b9321-1742-4ca5-95b8-2ff0389368cb',
 'd089ee33-ef5e-451e-8159-61157f7d0076',
 '3343840e-8c1f-4cfd-bd85-610e53b5ac49',
 '6a23f800-9ea1-4a7c-a8d8-aae139d940cd',
 '80c3af26-2757-42cf-a221-a5d98ae32958',
 '6aad2ea3-b284-41c9-b0ad-708b72b69ec2',
 'af450ee2-91dc-4fe2-ab43-05652b2b9ce1',
 '03b99a52-f5c3-42b6-9562-0fb8b732413e',
 '86d02b5e-60be-482a-ba60-82c69d5807f7',
 '09d2fe33-f083-4d8a-8b07-a8f3052a6400',
 '4f9004ac-a42d-4a1d-b8ee-c02439b63d30',
 '898df439-9c03-472f-8f92-e9da4628e4ab',
 '8ec86b52-35f6-4622-b065-21437e364b3b',
 'd21914e8-7f2d-4677-a0da-24542c817228',
 '0c22fd68-f84d-42a9-9ffa-a004b1c0a1d3',
 'eb6e3e59-7fa5-4a02-80b2-32a4402c65b0',
 'daa630fc-ca8a-4381-adb4-c5a67b260b28',
 '85b72ae4-11ab-4e97-bc92-f2536ce3dfa2',
 '9e36d960-bfcf-4222-a6dc-7fb1b57dcd9f',
 'd937eff3-16aa-4b9e-a7b0-e479bb75e038',
 '9fac3907-8af1-4d6f-a355-369f49f3fb0c',
 'c6020cf4-14b2-4a12-8875-823977bea77a',
 '5f7f34e1-263d-4697-8082-387d3ba8d9e3',
 '2f5b4fda-961e-4983-a13d-df26ad3d4540',
 '05034748-0d1c-40dc-a021-005fa132382f',
 'ad89984a-9d24-46fe-9c64-ebd06e402d56',
 'acc0d95f-525e-4f20-95ed-4449edd3ce22',
 '466ca6a5-e9c2-46b2-a9ae-f25fcef5877e',
 '93145f60-2548-4673-96a3-e95655cbe6ec',
 'caf93963-6dcd-44f4-b989-80f11273e222',
 'afe36acd-e0d9-42b0-9015-963bf1b5264c',
 '397e7e01-db9d-4943-8671-03d17ba63e52',
 '0904c439-0f24-4785-aa98-7c0a7f43ddb1',
 '6e960640-34aa-4028-9965-ed9aa3cbe3f3',
 '835f81d2-9655-4df3-b07f-cd50b3aea004',
 '86c1e788-0d08-47bd-a068-3afb3d0637b7',
 '216dfbb6-edb2-42ed-9bbc-0f245ff05f62',
 '30d53eb2-d178-403a-a29c-5de3d14eadf9',
 '73f9f29d-4641-449c-aa1f-9e49311445ca',
 '5c01c449-6b2e-443f-8a2a-d01ad6bc55fa',
 'ae245d1f-c971-4405-9b3b-8419cc6b85f0',
 'd1d718f7-e75d-4128-80f8-cba897ed4d17',
 '8d2a03a3-6bc3-411a-a34b-1a174ac88f85',
 '7c834bdd-7277-4c04-96e6-83d2c6fba9ae',
 '3c5ca84b-1450-4eab-9fdd-d08c23ab9a45',
 '1939a6ab-708d-4193-89a6-409a11c7685e',
 '9e9feddc-1b92-4a0e-82b3-eb66b5ab3fd6',
 '400607d1-2378-4c49-ac1b-e533cd239249',
 '366b1fe9-0ca0-4901-9425-c434f78a404f',
 '66eb94e7-b43d-4e9e-a0c0-71cbab054297',
 '11eff5dc-128f-4d0a-99ab-c1cde0b7012b',
 '9abb8e61-39c5-4897-a91b-343a9299e504',
 '2c7d07a0-ee87-4cfa-b682-55bd5ab407b2',
 '23e05bab-6a9f-4fec-91c7-d3affd50fd8d',
 'baa214cb-254b-4309-82cd-2259385409e8',
 '631548f7-19b1-4bc5-9d4f-888aa5a67019',
 '4c62c8db-6b2e-4338-81bc-77d1ffadcace',
 'b1e38637-c9f1-4d31-9188-d7116b2808c6',
 'c4077450-226f-4051-9aca-94645b6db516',
 '6b6d4c7a-fe3b-42da-aafd-6e475423a746',
 '9ee5c1e1-38a0-4eb4-93fe-24b7b1fa96b1',
 'd89a7bac-751f-42cb-827d-a370fcc073e2',
 'f036a9b8-4d63-473b-8a5e-1f0ff3ec76b9',
 'a70ad104-a43f-4ef5-9b71-1f114a48a6d6',
 'ec3d5313-7a3d-4111-a7bc-a043dcd7d347',
 '08d20a07-45ab-4f3a-918a-0c031377f537',
 'd30a55e0-62dd-46b3-b97b-479d0c6ab816',
 '1178b3f9-7b49-4a38-9877-3172734ea13f',
 'fbf13ceb-5ecf-4d62-9950-0f8aa06a0303',
 'f2b20e6e-56b3-4f60-a40c-3cdd32d42b1b',
 'fc88c842-ada9-4b60-a4c4-6f6e796fb520',
 '4a420dee-dd07-499a-b4fb-30b0a01a3792',
 '82b3030b-161b-40b9-a1a5-6afcd4ea7b55',
 '8a31d098-8f08-4863-a1ad-b1b2ed64307e',
 '80450b5a-7447-40d3-9cd7-19d8338bc27c',
 '0f1f86ee-d605-4ed1-9ba5-ff6bba98e560',
 '9a3ca537-b659-4748-938a-9d3027b9fd19',
 '2553a93e-74ef-42c3-976d-adb1aba55bf5',
 '4cd0ace1-2553-4f05-b5b0-53b8c8486ae0',
 'd3b245d6-01c6-41dc-a57f-f49a1a0787df',
 'c00d1d1b-bfdf-473e-b8ed-fde473fa0302',
 '38811afe-bae1-4adf-a674-539a886b6c22',
 '345c5283-d5b5-40eb-93c4-b8222515ef4f',
 '74ce6473-d22d-4071-a2f9-7f25a622a7cc',
 '6990f981-e95a-4806-a888-34354e0f312a',
 '3a59ec52-cccd-494a-b074-0a0f640e48eb',
 '135db8e1-6a49-426c-bd86-3d2d80ae56fa',
 '7257da5d-5606-4340-aa5c-90d1e578ca2f',
 '1a2846a1-39e6-4e08-8f13-3a149d8f239b',
 '13f0b144-6eb7-47f8-be40-96e35cefa98e',
 'aed43b41-afa7-4522-94bc-baf24501a7bb',
 '30643401-1f08-43a8-b905-063990eef805',
 '6840cd60-6f74-4491-8659-f1ca826007fc',
 'b47c2d78-7ede-4b49-b917-8ef2c2b11cc0',
 '82d66c63-2b52-4ca2-9817-5c6c4069a018',
 '9ac00f3f-0d15-45c9-9c81-33aef939514e',
 'f124dea7-3d0b-4a22-8c3e-56cf6b42fb64',
 'e5414a2a-0486-4817-a74a-516bd793bdef',
 '47a873bb-30ff-4b5c-a251-32ec46de9be1',
 '3b3bf9e8-4436-414a-a3bc-fd97a7637ae8',
 'dde3f047-acc5-4284-83cf-894780772e91',
 '1fbbb256-883c-483f-aff3-1b1a4dab13ef',
 'f3243f58-1405-43ae-bba2-7bb1c05dcabd',
 '06534fb2-03da-4097-b3ff-f2d162489f9d',
 '737f78b1-0df2-4df6-a06e-87f4df6b469f',
 'e90802aa-2dea-4b14-b67d-5dc5960d4118',
 'd4ce2160-f220-42fa-9f00-90495131b8c6',
 '603a9380-05de-4d58-abc8-a2a5ec6829ab',
 '0272e54f-dfe0-49d4-8b62-dce70e930cf7',
 '681f31ea-f30d-4cd1-9806-4048f48413e3',
 '2c9ef0e3-f3a1-4bc0-99ff-14a5b5f0621a',
 '5f410fb9-0ced-4333-8fd9-e3fcb039ff58',
 '4ac0835a-30a4-4331-b1dc-2c7f74cf29c8',
 '32fdf892-abc0-4925-99a2-42ec2b5350fa',
 'c7a0ac5d-4dec-4aff-afb4-6d4d8ed28ea3',
 'cf17d8bc-6391-486b-bc71-98e24e6922f0',
 'a15c9c9d-608b-4ced-915e-852d1f26885f',
 'b3035405-1d52-4a04-80d7-9fc273022558',
 '58e992ac-d891-46ef-b03a-e37c587a31ee',
 '1c013ab4-6154-41f1-a8f6-3c7a5dbe16a7',
 '19e772f3-b9de-4ac1-b4a6-db8e6c14f013',
 '15d1bbda-3f8c-4113-81cd-97bd204b0f51',
 '4404bbd8-177a-4e4a-b87d-40cf3f9bc613',
 '5511a37f-b3d1-4e40-bd64-3ad0ff966163',
 'bee6fad4-8040-472f-92e7-b147ccc8eebf',
 'c2ff4261-d6b8-4379-a6bf-c0663f78aab4',

db로부터 retriever를 구성합니다.

In [13]:
retriever = db.as_retriever(search_kwargs={'k':5})
# Chunk Size * K = Context 글자
# 1000      *  5 = 5000 토큰

RAG를 위한 간단한 프롬프트를 작성합니다.

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate([
    ("system", '''당신은 QA(Question-Answering)을 수행하는 Assistant입니다.
다음의 Context를 이용하여 Question에 답변하세요.
정확한 답변을 제공하세요.
만약 모든 Context를 다 확인해도 정보가 없다면,
"정보가 부족하여 답변할 수 없습니다."를 출력하세요.'''),
("human",'''
Context: {context}
---
Question: {question}''')])

prompt.pretty_print()

================================ System Message ================================

당신은 QA(Question-Answering)을 수행하는 Assistant입니다.
다음의 Context를 이용하여 Question에 답변하세요.
정확한 답변을 제공하세요.
만약 모든 Context를 다 확인해도 정보가 없다면,
"정보가 부족하여 답변할 수 없습니다."를 출력하세요.

================================ Human Message =================================


Context: {context}
---
Question: {question}

RAG를 수행하기 위한 Chain을 만듭니다.

In [ ]:
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from langchain_community.output_parsers import StrOutputParser

def format_docs(docs):
    return " \n---\n ".join([doc.page_content+ '\n' for doc in docs])

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

In [35]:
rag_chain_from_docs = (
    prompt
    | llm
    | StrOutputParser()
)

rag_chain_with_ref = RunnableParallel(
    context = retriever | format_docs, question = RunnablePassthrough()
).assign(answer=rag_chain_from_docs)
# context, question, answer

# RAGAS 사용하기


RAGAS 는 다양한 메트릭을 통한 RAG의 성능 평가를 지원합니다.


각각의 메트릭은 아래의 링크에서 확인할 수 있습니다.

https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/

시트에서 평가 데이터셋을 불러옵니다.   
Question/Ground Truth의 구성입니다.

In [18]:
# Best: Retrieval의 Ground Truth, Generation의 Ground Truth가 모두 존재

import pandas as pd
df = pd.read_csv('./eval_dataset.csv', encoding='cp949')
eval_dataset = df.to_dict('list')
eval_dataset

{'questions': ['2022~2024년 삼성SDS의 매출 구성을 IT서비스와 물류 관점에서 비교하고, 이 변화가 의미하는 전략적 시사점을 설명하시오.',
  '삼성SDS가 ‘클라우드 기업’으로 전환한다고 밝힌 바 있는 전략을, 제품·플랫폼·인프라·交부문 운영모델 측면에서 통합적으로 설명하시오.',
  '물류 부문에서 삼성SDS가 디지털 포워딩 경쟁력을 어떻게 구축했는지, 플랫폼 진화와 글로벌 네트워크 관점에서 설명하시오.',
  '회사가 서비스 가격표를 제시하지 않는 이유와 실제 가격 결정 방식은 무엇이며, 이는 IT서비스·물류 사업의 어떤 특성과 연결되는가?',
  '경기변동이 IT서비스와 물류에 미치는 영향과, 삼성SDS가 그 민감도를 낮추기 위해 취하는 대응을 설명하시오.',
  'SRM 분야에서의 인수·출시 활동이 삼성SDS의 SaaS 전략과 글로벌 확장에 어떤 의미가 있는지 설명하시오.',
  '인력·시설·보안 측면에서 삼성SDS의 운영 기반과 이것이 서비스 신뢰성에 주는 함의를 설명하시오.',
  '재무 안정성 측면에서 회사의 공시 내용을 종합하되, 상장 이력과 조달 구조까지 연결해 설명하시오.',
  '삼성SDS의 2024년 3분기말(9월 30일) 연결 기준 부채비율을 재무상태표 수치로 검증하고, 전기말(2023년 12월 31일)과 비교해 변화 요인을 설명하시오.',
  '2024년 3분기 누적과 2024 사업연도(사업보고서 기준)에서 삼성SDS의 희석주당이익이 기본주당이익과 동일한 이유는 무엇이며, 각 기간의 기본주당이익 산출 근거를 제시하시오.',
  '2024년 삼성SDS의 주식기준보상(엠로 포함) 현황을 수량, 행사가격, 만기, 비용 인식, 자본변동 영향까지 종합해 설명하시오.',
  '온실가스 배출권과 배출부채에 대해, 2024년 중 배출권 수량·장부금액 변동과 기말 배출부채(충당부채) 인식, 담보 제공 여부를 함께 설명하시오.',
  '특수관계자와의 배당거래는 2024년에 어떻게 이루어졌으며, 연결 현금흐름에서의 배당금 지급과 어떤 관계가 있습니까?',
  '2024년 9월말까지 삼성SDS 연결 자본(지배주주지분)은 어떤 요인들로 증가·감소했는지, 금액을 들어 설명하시오.',
  '2024년 3분기 누적 연구개발(R&D) 활동과 비용은 어떤 특징을 보였는지, 매출 대비 비율과 자산화/비용 처리 내역, 주요 연구 분야를 함께 기술하시오.',
  '삼성SDS가 2024년 3분기 (주)동아미디어엔 보통주 18.01%만을 보유하면서도 ‘관계기업’으로 분류한 이유와 그 회계적 근거를 공시자료에 근거해 설명하시오.',
  '삼성SDS가 2024년 중 한국정보인증(주) 지분을 전량 처분한 사실이 연결재무제표에 어떤 항목들로 나타났는지, 손익과 장부금액 변화를 함께 설명하시오.',
  '만약 삼성SDS가 CMC Corporation(현재 유효지분율 약 29.83%)의 추가 지분을 취득해 지배력을 확보(종속기업 전환)한다면, 기존 보유지분은 어떤 회계처리를 하게 되며, 공시된 시장가격 정보를 이용할 때 잠재적 재측정손익은 어느 정도로 추정되는가?',
  '2024년 중 삼성SDS의 종속기업 지분 관련 변동을 별도·연결 재무제표 관점에서 비교·분석하시오. 사업결합(합병·인수) 여부, 소유지분 변동의 회계처리, 그리고 관련 공시수치를 함께 제시하시오.',
  '삼성SDS가 향후 종속회사와의 합병을 추진하는 경우, 사내 거버넌스와 주주총회 절차 측면에서 어떤 승인과 의결이 필요한가? 현재의 의결권 구조와 함께 설명하시오.'],
 'ground_truths': ['공시자료에 따르면 전체 매출에서 IT서비스와 물류 비중은 2022년 34.6% 대 65.4%, 2023년 46.0% 대 54.0%, 2024년 46.3% 대 53.7%로 나타났습니다. 특히 IT서비스 내에서도 클라우드 매출이 2022년 1,162,676백만원(6.7%) → 2023년 1,880,680백만원(14.2%) → 2024년 2,323,476백만원(16.8%)로 빠르게 확대된 반면, SI와 ITO는 정체 또는 소폭 감소했습니다. 이는 2021~2022년 물류 운임 급등 효과가 둔화되며 물류 비중이 정상화되는 가운데, 회사가 클라우드·SaaS·생성형 AI 중심의 포트폴리오 전환으로 성장축을 IT로 재정렬하고 있음을 보여줍니다. 전략적으로는 SCP 기반 CSP·MSP 역량, Brity Works·Caidentia 등 엔터프라이즈 SaaS, FabriX·Brity Copilot·GPUaaS 같은 생성형 AI 상품을 앞세워 고성장·고부가의 클라우드 매출 비중을 키우고, 물류는 Cello·Cello Square로 디지털포워딩과 운영효율화 경쟁력을 강화해 양축의 균형 성장을 지향하는 방향으로 해석됩니다.',
  '제품·플랫폼 측면에서 회사는 SCP를 전개하며 CSP·MSP·SaaS를 End-to-End로 제공하고, 협업·업무혁신 솔루션 Brity Works, 글로벌 SRM SaaS ‘Caidentia’(엠로 지분 인수 기반), 공급망·인사 등 Nexprime/Nextprime 기반 솔루션을 갖추고 있습니다. 생성형 AI 측면에서는 기업용 AI 플랫폼 FabriX, 협업AI인 Brity Copilot, 그리고 모델 실험·추론을 위한 GPUaaS를 통해 애플리케이션부터 인프라까지 수요를 포괄합니다. 인프라 측면에서는 국내 5개 데이터센터(상암·수원·춘천·동탄 자가, 구미 임차)를 운영하고, 동탄을 HPC 전용 센터로 고도화하여 R&D·AI·시뮬레이션 수요를 대응합니다. 운영모델 측면에서는 인도·베트남·중국 글로벌 개발센터 및 ITO Off-site를 활용한 원격운영으로 효율성과 전문성을 강화합니다. 이러한 구성은 클라우드-데이터센터-HPC 인프라와 엔터프라이즈 SaaS·AI 플랫폼을 수직결합해 고객의 클라우드 전환, 운영자동화, 생성형 AI 도입을 일관되게 지원하는 통합 전략으로 연결됩니다.',
  '삼성SDS는 통합물류 플랫폼 Cello와 디지털 물류 플랫폼 Cello Square를 통해 국제운송·내륙운송·창고·프로젝트 물류까지 End-to-End 서비스를 제공하며, 2021년 한국에서 디지털포워딩을 시작해 2022년 중국·동남아 등 수출국으로, 2023년부터는 미국·유럽 등 수입국으로 서비스를 확대했습니다. 네트워크는 전 세계 36개국에서 300~330여 개 사이트, 6,000~6,300명의 물류 전문가, 5,300~5,700개 파트너를 아우르며 글로벌 25위의 운영 역량을 갖춘 것으로 공시되어 있습니다. 고객은 삼성 관계사가 핵심이지만 대외 고객을 적극 확대 중이며, Cello Square에서 견적-예약-운송-트래킹-정산을 단일 플랫폼으로 처리하고 축적 데이터 기반 분석·예측까지 제공함으로써 고객이 직접, 신속, 투명하게 물류를 운영하도록 지원합니다. 즉, IT역량을 바탕으로 플랫폼 일원화와 AI/데이터 분석을 결합해 디지털포워딩에서 차별화된 사용자 경험과 운영 효율을 구현한 구조입니다.',
  '공시자료는 IT서비스(SI·ITO·클라우드)와 물류가 개인용 규격 상품이 아니라 고객 상황·요구에 따른 맞춤형 B2B 서비스라고 명시합니다. 따라서 가격은 표준 단가표가 아니라 투입 원가에 일정 마진을 가산해 제안·협의로 확정됩니다. IT에서는 프로젝트별 서버·소프트웨어 라이선스·전문인력 구성 등 변동요소가 크고, 물류 역시 국가·운송수단·부가서비스·시점에 따른 요인이 다양해 기간별 단가 비교가 적절치 않습니다. 원재료·상품 측면에서도 전산장비·소프트웨어·외주용역 등 구성과 사양이 프로젝트별로 달라 단순 가격 추이 표기가 어렵다고 설명합니다. 요컨대, 높은 커스터마이징과 복잡한 조합형 서비스 구조가 가격표 부재와 개별견적 방식의 근거입니다.',
  'IT서비스는 기업 설비투자와 연동돼 경기 둔화 시 투자 보류 영향이 있으나, 클라우드·AI·빅데이터 등 디지털 전환 수요 확대로 민감도는 낮아지는 추세이며, 예산 집행이 하반기에 집중되는 경향이 있습니다. 물류는 세계 경기·무역량·유가·선복 수급·국제정세 등 외생변수에 민감하고, IT 신제품 출시나 명절·연말 등 계절성도 영향을 줍니다. 삼성SDS는 이러한 변동성에 대응해 IT에서는 하이브리드 멀티클라우드, 엔터프라이즈 SaaS, 생성형 AI 플랫폼·GPUaaS로 구조적 성장영역을 확장하고, 글로벌 개발센터·Off-site 운영으로 비용·품질 균형을 강화합니다. 물류에서는 Cello·Cello Square로 플랫폼 기반 운영 표준화와 가시성, 데이터 분석·예측을 높여 운임·수요 변동의 충격을 완화합니다. 또한 삼성 관계사라는 대내 시장의 진입장벽과 장기 파트너십을 기반으로 안정적 수요를 확보하면서 대외 고객을 확대해 포트폴리오를 다변화하고 있습니다.',
  '회사는 2023년 2분기에 국내 1위 SRM 기업 엠로의 지분 인수를 완료해 핵심 공급망·구매 역량을 내재화했고, 2024년 2분기에는 글로벌향 SRM SaaS ‘Caidentia’를 출시해 해외 시장 공략을 본격화했습니다. 이는 Brity Works, EMM, Nexprime/Nextprime SCM·HCM, Brightics 등과 함께 엔터프라이즈 SaaS 포트폴리오를 보강해, CSP·MSP와 결합한 ‘클라우드 위의 애플리케이션’ 전략을 강화하는 조치입니다. 검증된 삼성 관계사 레퍼런스와 자체 솔루션을 결합해 대외 시장에서 차별화된 도메인 전문성을 제공하고, 글로벌 SaaS 생태계(예: 글로벌 SaaS 구축·적용 역량)와 연계해 수주 경쟁력을 높이는 의미를 가집니다.',
  '2024년 말 기준 연결 인력은 약 25,666명으로, IT서비스 16,798명, 물류 5,204명 등 인적자원이 핵심 생산요소입니다. 시설은 국내 5개 데이터센터와 다수의 통신거점을 운영하며, 상암·수원·춘천·동탄은 자가, 구미는 임차 구조입니다. 모든 데이터센터가 Tier3급 수준의 안정성을 갖추고, 동탄은 HPC 전용으로 AI·시뮬레이션 수요를 담당합니다. 회사는 세계 최고 수준의 정보보안 체계를 표방하고, 데이터전문기관 지정 등 대내외 신뢰 기반을 확보했으며, 기업어음 신용등급 A1을 지속 유지해 재무적 신뢰도도 높습니다. 이러한 인력 규모, 데이터센터 안정성, 보안 통제, 재무 건전성이 결합되어 IT·물류 서비스의 가용성·연속성·보안성에 대한 고객 신뢰를 뒷받침합니다.',
  '삼성SDS는 2014년 11월 14일 유가증권시장에 상장했으며, 단기 조달 수단인 기업어음 신용등급을 2021~2023년에 걸쳐 한국기업평가와 NICE신용평가로부터 A1 등급을 유지해 단기 상환능력의 안정성을 인정받고 있습니다. 공모·사모 회사채 등 유가증권 발행에 따른 미상환 잔액은 공시 기준 시점에 없고, 증권 발행으로 조달된 자금 사용내역도 해당사항이 없다고 밝혔습니다. 이는 현금창출력과 내부 재원, 관계사 네트워크 등을 바탕으로 외부 차입 의존도를 낮게 유지하며, 필요한 투자에는 선택적으로 집행하는 보수적 재무운용 기조를 시사합니다. 안정적 신용도와 낮은 채무비중은 대규모 데이터센터·클라우드 인프라 투자나 글로벌 물류 운영에서도 재무적 유연성을 제공하는 기반이 됩니다.',
  '2024년 3분기말 연결 기준 부채총계는 3,409,626,256천원, 자본총계는 9,393,068,289천원으로 공시되어 있습니다. 이를 이용해 계산한 부채비율은 3,409,626,256 ÷ 9,393,068,289 ? 36.30%로, 공시된 부채비율(36.30%)과 일치합니다. 전기말(2023.12.31)에는 부채총계 3,345,453,419천원, 자본총계 8,975,571,142천원으로 부채비율이 37.27%였습니다. 즉, 2024년 들어 부채비율이 36.30%로 개선되었습니다. 같은 기간 지배주주지분이 8,658,009,435,402원에서 9,029,477,673,582원으로 증가(분기순이익 567,196,773,122원, 해외사업환산손익 +46,977,194,013원, 주식보상비용 인식 +5,636,306,702원 등의 누적 효과)한 반면, 부채는 유사한 수준에서 관리되면서 분모(자본) 확대로 비율이 낮아진 것이 주된 요인입니다.',
  '삼성SDS는 당기 및 전기에 희석증권을 보유하지 않아 희석주당이익이 기본주당이익과 동일합니다(사업보고서 주석: "당기 및 전기 중 희석증권을 보유하지 않아 희석주당이익은 기본주당이익과 동일"). 2024년 3분기 누적 연결 기준 기본주당이익은 7,333원(지배기업 소유지분 분기누적 순이익 567,196,773,122원 기준)으로 공시되었고, 동일 값이 희석주당이익으로 재표시되었습니다. 2024 사업보고서(연결)에서는 기본주당이익이 9,787원이며, 산출 근거로 지배기업 소유지분 순이익 756,996,882천원과 가중평균유통보통주식수 77,350,186주가 제시되어 있습니다(756,996,882천원 ÷ 77,350,186주 ? 9,787원). 한편 종속회사(엠로) 차원의 주식선택권이 존재하나 이는 지배기업 보통주에 대한 희석증권이 아니므로 연결 EPS의 희석효과를 발생시키지 않습니다.',
  '연결실체 종속회사 (주)엠로의 주식매입선택권이 2024년 보고기간에 연결 주식기준보상의 핵심입니다. 기말 유효한 주식선택권은 총 633,540주이며, 트렌치는 다음과 같습니다: 2차(부여일 2021-10-29, 최장만기 2027-10-29, 행사가 16,440원, 425,440주), 3차(2022-03-25, 2028-03-25, 17,678원, 94,860주), 4차(2023-03-31, 2029-03-31, 43,393원, 43,380주), 5차(2024-03-20, 2030-03-19, 58,405원, 69,860주). 2024년 상반기에는 신규 부여 71,460주, 만료 10,880주가 있었고, 기말 가중평균 행사가격은 23,098원입니다. 비용 측면에서 상반기 주식기준보상비용은 4,018백만원, 3분기에는 6,207백만원이 비용으로 인식되었습니다. 자본변동표에도 2024.09.30 누적 주식보상비용 5,636,306,702원이 기타자본항목에 반영되어 있습니다(기간별 인식시점 차이로 비용계정 vs 자본항목 표시금액의 시차가 존재). 요약하면, 2024년에는 엠로의 지분결제형 옵션이 지속 가득·만기 스케줄을 따르며 비용이 인식되었고, 연결 자본에는 주식보상비용이 증가 요인으로 작용했습니다.',
  '삼성SDS는 3차 계획기간(2021~2025년)에 대해 무상할당을 받고 있으며, 당기 기말 기준 누적 무상할당 수량은 476,076 KAU로 공시되어 있습니다. 2024년 중 배출권 수량 변동은 기초 93,143 KAU에서 무상할당 133,504 KAU, 유상매입 47,089 KAU, 제출(사용) (149,538) KAU를 반영해 기말 124,198 KAU입니다. 장부금액은 기초 0에서 유상매입 415,939천원 인식 후 제출 (149,834)천원을 반영하여 기말 266,105천원입니다. 배출량에 대응한 배출부채는 유동 온실가스배출충당부채로 203,562천원을 인식했습니다. 아울러 당기말 현재 담보로 제공된 배출권은 없다고 공시되어 있습니다. 정리하면, 2024년에는 무상할당과 일부 유상매입으로 확보한 배출권을 제출해 의무를 이행했고, 잔여 배출량에 대해서는 충당부채를 계상했으며, 배출권에 대한 담보 제공은 없습니다.',
  '사업보고서 특수관계자 주석에 따르면, 2024년 중 특수관계자로부터 수취한 배당금은 234백만원, 특수관계자에게 지급결의한 배당금은 84,695백만원입니다. 해당 배당과 관련한 미수·미지급 잔액은 당기말에 존재하지 않습니다(각 0). 한편 연결 현금흐름표에서는 2024년 1~9월 누적 배당금 지급이 215,847,813,600원으로 공시되어 있는데, 이는 전체 주주(비특수관계자 포함)에 대한 현금배당을 반영한 금액입니다. 따라서 특수관계자 관련 배당은 전체 현금배당 중 일부이며, 특수관계자 주석은 거래상대방이 특수관계자인 항목만 분리 공시했다는 점에서 연결 현금흐름표의 총배당금 지급액과 항목 범위가 다릅니다.',
  '지배주주지분은 2023.12.31의 8,658,009,435,402원에서 2024.09.30의 9,029,477,673,582원으로 증가했습니다. 주요 증감요인은 다음과 같습니다. 증가 요인: (1) 분기누적 지배주주 순이익 +567,196,773,122원, (2) 해외사업환산손익 +46,977,194,013원, (3) 주식보상비용 인식 +5,636,306,702원. 감소 요인: (4) 연차배당 -208,845,502,200원, (5) 기타포괄손익 중 확정급여 재측정손실 -9,115,146,308원, FVOCI 금융자산평가손익 -367,932,353원, 지분법자본변동 -2,197,421,605원, (6) 종속기업 소유지분 변동 등 기타자본변동 -22,179,726,489원. 종합하면, 실적 호조와 환산이익이 자본 확대로 기여했으나 현금배당과 기타포괄손익의 일부 손실, 지분변동이 일부 상쇄했습니다.',
  '2024년 3분기 누적 연결 기준 연구개발비용 총계는 175,502,420천원이며, 이 중 개발비 자산화가 19,280,108천원, 연구개발비(기간비용)가 156,222,312천원입니다. 매출 대비 R&D 비율은 1.72%로 공시되어 있으며(동 기간 연결 매출 10,185,908,244,048원 기준 약 1.72%), 전년 동기 대비 확대되었습니다. 연구 분야는 AI(엔터프라이즈 생성형 AI 모델 고도화, RAG 정확도 개선, 코드 LLM 특화, API Retrieval·Conversational QA, 멀티모달 문서·GUI 분석 등), Cloud/HPC(스카이 컴퓨팅 기반 전송, 이기종 스토리지 복제·콜드 스토리지 자동화, LLM 서빙 최적화, GPU 스케줄러 고도화), Security(양자내성암호·PQC 마이그레이션, 이상탐지, 클라우드 네이티브 보안), 네트워크·로드밸런싱 성능 개선 등으로, 사업화와 운영 효율 제고에 직결되는 과제를 폭넓게 수행했습니다.',
  '2024년 3분기 공시에 따르면 (주)동아미디어엔은 지분율이 20% 미만(18.01%)임에도 불구하고 관계기업으로 분류되었습니다. 주석에는 “이사회에 참여하거나 경영진의 상호교류가 있어 피투자회사의 재무정책과 영업정책 의사결정 과정에 참여할 수 있으므로 관계기업투자주식으로 분류”했다고 명시되어 있습니다. 이는 K-IFRS에서 지분율 20% 미만이라도 재무·영업정책 결정에 ‘유의적인 영향력’을 행사하면 관계기업(지분법 적용 대상)으로 분류할 수 있다는 정의(사업보고서의 관계기업 회계정책 설명)와 부합합니다. 해당 투자에 대해 삼성SDS는 지분법을 적용해 장부금액 360,988천원을 인식하고 있으며, 이는 단순한 공정가치측정이 아니라 피투자자의 순자산 변동을 반영하는 지분법 회계처리 결과입니다.',
  '관계기업투자주식 주석에 “한국정보인증(주) 당분기 중 전량 매각”이 명시되어 있으며, 기중 변동표에서도 기초 장부금액(8,483,615천원)이 처분으로 0이 된 흐름이 확인됩니다. 처분 손익은 연결 기타수익에 ‘관계기업투자주식 처분이익’ 1,731,221천원이 인식되어 반영되었습니다(2024년 3분기 누적 기준). 처분으로 인해 연결 기준 관계기업투자주식 잔액에서 한국정보인증 관련 금액이 제거되었고, 기존 지분법으로 누적 인식된 금액 및 해당 투자에 연결된 기타포괄손익 누계액은 K-IFRS 기준에 따라 처분 시점에 적절히 재분류 또는 대체됩니다(금액 세부내역은 공시 내 개별 표시 없음).',
  'K-IFRS에 따르면 단계적 취득으로 지배력을 확보하는 경우, 기존에 보유하던 관계기업 지분은 취득일 공정가치로 재측정하고 그 차이는 당기손익으로 인식합니다. 공시된 시장정보에 따르면 CMC의 보유주식 수는 56,792,115주, 주당 시장가격은 2,723원으로 공정가치 총액은 약 154,644,929천원입니다. 현재 지분법 장부금액은 64,926,596천원이므로, 지배력 취득 시점에 이 금액을 공정가치로 재측정할 경우 약 89,718,333천원의 재측정이익(세전, 추정치)이 인식될 수 있습니다. 이후에는 CMC를 종속기업으로 연결 편입하고, 취득일 현재 식별가능한 순자산에 공정가치 배분을 수행하며, 잔여분은 영업권으로 인식됩니다. 기존 비지배지분(NCI)은 공정가치 또는 비례법 중 선택한 방식으로 측정됩니다.',
  '2024년에는 신규 사업결합이 없었습니다(연결 현금흐름표 ‘사업결합으로 인한 순현금유출 0’, 연결 자본변동표 ‘사업결합 0’). 그럼에도 별도재무제표에서 종속기업투자주식은 2023.12 말 626,664백만원에서 2024.09 말 676,263백만원으로 약 49,599백만원 증가했습니다. 이는 종속기업 지분 추가 취득(또는 증자 참여 등)로 원가법상 취득원가가 증가했음을 시사합니다. 한편 연결 재무제표에서는 지배력을 유지한 상태의 소유지분 변동은 자본거래로 처리되며 당기손익에 반영되지 않습니다. 실제 2024.09 누적 연결 자본변동표에 ‘종속기업에 대한 소유지분의 변동 등’이 (22,179,726,489)원으로 기타자본항목에서 인식되었고, 동시에 비지배지분 변동 21,655,888,941원이 맞물려 표시되었습니다. 요약하면 2024년에는 합병·신규 취득 없이, 기존 종속기업에 대한 지분율 변경(또는 구조조정)이 있었고, 별도는 원가 증가로, 연결은 자본 변동으로 각각 반영되었습니다.',
  '회사 이사회 규정에 따르면 합병·분할·분할합병 등은 이사회 부의사항이며, 주주총회 결의 대상입니다(정관·이사회 규정상 중요 사항). 따라서 절차상 ① 이사회에서 합병안 심의·의결 후, ② 주주총회에서 합병계약 승인 결의를 받아야 합니다. 2024년 말 기준 보통주 발행주식총수는 77,377,800주이며, 자기주식 27,614주를 제외한 의결권 행사 가능 주식수는 77,350,186주입니다. 최대주주는 삼성전자(22.58%)이며, 특수관계인 등을 포함한 최대주주 그룹 지분은 48.95%(2024.09.30 기준)입니다. 전자투표 제도도 도입되어 있어 주주총회 의결권 행사가 가능하며, 집중투표제·서면투표제는 미도입입니다. 요컨대 합병 추진 시 이사회와 주주총회라는 이중 승인 절차가 필요하며, 의결권 구조 하에서 법정 요건을 충족하는 찬성이 확보되어야 합니다.']}

구성된 RAG 체인을 이용해, RAGAS의 Evaluate 형태로 변환합니다.

In [19]:
questions, ground_truths = eval_dataset['questions'], eval_dataset['ground_truths']

In [20]:
for i in range(len(questions)):
    print(f'#{i}')
    print(f'Question: {questions[i]}\n')
    print(f'Ground Truth: {ground_truths[i]}\n')
    print('-----------')

#0
Question: 2022~2024년 삼성SDS의 매출 구성을 IT서비스와 물류 관점에서 비교하고, 이 변화가 의미하는 전략적 시사점을 설명하시오.

Ground Truth: 공시자료에 따르면 전체 매출에서 IT서비스와 물류 비중은 2022년 34.6% 대 65.4%, 2023년 46.0% 대 54.0%, 2024년 46.3% 대 53.7%로 나타났습니다. 특히 IT서비스 내에서도 클라우드 매출이 2022년 1,162,676백만원(6.7%) → 2023년 1,880,680백만원(14.2%) → 2024년 2,323,476백만원(16.8%)로 빠르게 확대된 반면, SI와 ITO는 정체 또는 소폭 감소했습니다. 이는 2021~2022년 물류 운임 급등 효과가 둔화되며 물류 비중이 정상화되는 가운데, 회사가 클라우드·SaaS·생성형 AI 중심의 포트폴리오 전환으로 성장축을 IT로 재정렬하고 있음을 보여줍니다. 전략적으로는 SCP 기반 CSP·MSP 역량, Brity Works·Caidentia 등 엔터프라이즈 SaaS, FabriX·Brity Copilot·GPUaaS 같은 생성형 AI 상품을 앞세워 고성장·고부가의 클라우드 매출 비중을 키우고, 물류는 Cello·Cello Square로 디지털포워딩과 운영효율화 경쟁력을 강화해 양축의 균형 성장을 지향하는 방향으로 해석됩니다.

-----------
#1
Question: 삼성SDS가 ‘클라우드 기업’으로 전환한다고 밝힌 바 있는 전략을, 제품·플랫폼·인프라·交부문 운영모델 측면에서 통합적으로 설명하시오.

Ground Truth: 제품·플랫폼 측면에서 회사는 SCP를 전개하며 CSP·MSP·SaaS를 End-to-End로 제공하고, 협업·업무혁신 솔루션 Brity Works, 글로벌 SRM SaaS ‘Caidentia’(엠로 지분 인수 기반), 공급망·인사 등 Nexprime/Nextprime 기반 솔루션을 갖추고 있습니다. 생성형 AI 측면에서는 기업용 AI 플랫폼 FabriX, 협업AI인 Brity Copilot, 그리고 모델 실험·추론을 위한 GPUaaS를 통해 애플리케이션부터 인프라까지 수요를 포괄합니다. 인프라 측면에서는 국내 5개 데이터센터(상암·수원·춘천·동탄 자가, 구미 임차)를 운영하고, 동탄을 HPC 전용 센터로 고도화하여 R&D·AI·시뮬레이션 수요를 대응합니다. 운영모델 측면에서는 인도·베트남·중국 글로벌 개발센터 및 ITO Off-site를 활용한 원격운영으로 효율성과 전문성을 강화합니다. 이러한 구성은 클라우드-데이터센터-HPC 인프라와 엔터프라이즈 SaaS·AI 플랫폼을 수직결합해 고객의 클라우드 전환, 운영자동화, 생성형 AI 도입을 일관되게 지원하는 통합 전략으로 연결됩니다.

-----------
#2
Question: 물류 부문에서 삼성SDS가 디지털 포워딩 경쟁력을 어떻게 구축했는지, 플랫폼 진화와 글로벌 네트워크 관점에서 설명하시오.

Ground Truth: 삼성SDS는 통합물류 플랫폼 Cello와 디지털 물류 플랫폼 Cello Square를 통해 국제운송·내륙운송·창고·프로젝트 물류까지 End-to-End 서비스를 제공하며, 2021년 한국에서 디지털포워딩을 시작해 2022년 중국·동남아 등 수출국으로, 2023년부터는 미국·유럽 등 수입국으로 서비스를 확대했습니다. 네트워크는 전 세계 36개국에서 300~330여 개 사이트, 6,000~6,300명의 물류 전문가, 5,300~5,700개 파트너를 아우르며 글로벌 25위의 운영 역량을 갖춘 것으로 공시되어 있습니다. 고객은 삼성 관계사가 핵심이지만 대외 고객을 적극 확대 중이며, Cello Square에서 견적-예약-운송-트래킹-정산을 단일 플랫폼으로 처리하고 축적 데이터 기반 분석·예측까지 제공함으로써 고객이 직접, 신속, 투명하게 물류를 운영하도록 지원합니다. 즉, IT역량을 바탕으로 플랫폼 일원화와 AI/데이터 분석을 결합해 디지털포워딩에서 차별화된 사용자 경험과 운영 효율을 구현한 구조입니다.

-----------
#3
Question: 회사가 서비스 가격표를 제시하지 않는 이유와 실제 가격 결정 방식은 무엇이며, 이는 IT서비스·물류 사업의 어떤 특성과 연결되는가?

Ground Truth: 공시자료는 IT서비스(SI·ITO·클라우드)와 물류가 개인용 규격 상품이 아니라 고객 상황·요구에 따른 맞춤형 B2B 서비스라고 명시합니다. 따라서 가격은 표준 단가표가 아니라 투입 원가에 일정 마진을 가산해 제안·협의로 확정됩니다. IT에서는 프로젝트별 서버·소프트웨어 라이선스·전문인력 구성 등 변동요소가 크고, 물류 역시 국가·운송수단·부가서비스·시점에 따른 요인이 다양해 기간별 단가 비교가 적절치 않습니다. 원재료·상품 측면에서도 전산장비·소프트웨어·외주용역 등 구성과 사양이 프로젝트별로 달라 단순 가격 추이 표기가 어렵다고 설명합니다. 요컨대, 높은 커스터마이징과 복잡한 조합형 서비스 구조가 가격표 부재와 개별견적 방식의 근거입니다.

-----------
#4
Question: 경기변동이 IT서비스와 물류에 미치는 영향과, 삼성SDS가 그 민감도를 낮추기 위해 취하는 대응을 설명하시오.

Ground Truth: IT서비스는 기업 설비투자와 연동돼 경기 둔화 시 투자 보류 영향이 있으나, 클라우드·AI·빅데이터 등 디지털 전환 수요 확대로 민감도는 낮아지는 추세이며, 예산 집행이 하반기에 집중되는 경향이 있습니다. 물류는 세계 경기·무역량·유가·선복 수급·국제정세 등 외생변수에 민감하고, IT 신제품 출시나 명절·연말 등 계절성도 영향을 줍니다. 삼성SDS는 이러한 변동성에 대응해 IT에서는 하이브리드 멀티클라우드, 엔터프라이즈 SaaS, 생성형 AI 플랫폼·GPUaaS로 구조적 성장영역을 확장하고, 글로벌 개발센터·Off-site 운영으로 비용·품질 균형을 강화합니다. 물류에서는 Cello·Cello Square로 플랫폼 기반 운영 표준화와 가시성, 데이터 분석·예측을 높여 운임·수요 변동의 충격을 완화합니다. 또한 삼성 관계사라는 대내 시장의 진입장벽과 장기 파트너십을 기반으로 안정적 수요를 확보하면서 대외 고객을 확대해 포트폴리오를 다변화하고 있습니다.

-----------
#5
Question: SRM 분야에서의 인수·출시 활동이 삼성SDS의 SaaS 전략과 글로벌 확장에 어떤 의미가 있는지 설명하시오.

Ground Truth: 회사는 2023년 2분기에 국내 1위 SRM 기업 엠로의 지분 인수를 완료해 핵심 공급망·구매 역량을 내재화했고, 2024년 2분기에는 글로벌향 SRM SaaS ‘Caidentia’를 출시해 해외 시장 공략을 본격화했습니다. 이는 Brity Works, EMM, Nexprime/Nextprime SCM·HCM, Brightics 등과 함께 엔터프라이즈 SaaS 포트폴리오를 보강해, CSP·MSP와 결합한 ‘클라우드 위의 애플리케이션’ 전략을 강화하는 조치입니다. 검증된 삼성 관계사 레퍼런스와 자체 솔루션을 결합해 대외 시장에서 차별화된 도메인 전문성을 제공하고, 글로벌 SaaS 생태계(예: 글로벌 SaaS 구축·적용 역량)와 연계해 수주 경쟁력을 높이는 의미를 가집니다.

-----------
#6
Question: 인력·시설·보안 측면에서 삼성SDS의 운영 기반과 이것이 서비스 신뢰성에 주는 함의를 설명하시오.

Ground Truth: 2024년 말 기준 연결 인력은 약 25,666명으로, IT서비스 16,798명, 물류 5,204명 등 인적자원이 핵심 생산요소입니다. 시설은 국내 5개 데이터센터와 다수의 통신거점을 운영하며, 상암·수원·춘천·동탄은 자가, 구미는 임차 구조입니다. 모든 데이터센터가 Tier3급 수준의 안정성을 갖추고, 동탄은 HPC 전용으로 AI·시뮬레이션 수요를 담당합니다. 회사는 세계 최고 수준의 정보보안 체계를 표방하고, 데이터전문기관 지정 등 대내외 신뢰 기반을 확보했으며, 기업어음 신용등급 A1을 지속 유지해 재무적 신뢰도도 높습니다. 이러한 인력 규모, 데이터센터 안정성, 보안 통제, 재무 건전성이 결합되어 IT·물류 서비스의 가용성·연속성·보안성에 대한 고객 신뢰를 뒷받침합니다.

-----------
#7
Question: 재무 안정성 측면에서 회사의 공시 내용을 종합하되, 상장 이력과 조달 구조까지 연결해 설명하시오.

Ground Truth: 삼성SDS는 2014년 11월 14일 유가증권시장에 상장했으며, 단기 조달 수단인 기업어음 신용등급을 2021~2023년에 걸쳐 한국기업평가와 NICE신용평가로부터 A1 등급을 유지해 단기 상환능력의 안정성을 인정받고 있습니다. 공모·사모 회사채 등 유가증권 발행에 따른 미상환 잔액은 공시 기준 시점에 없고, 증권 발행으로 조달된 자금 사용내역도 해당사항이 없다고 밝혔습니다. 이는 현금창출력과 내부 재원, 관계사 네트워크 등을 바탕으로 외부 차입 의존도를 낮게 유지하며, 필요한 투자에는 선택적으로 집행하는 보수적 재무운용 기조를 시사합니다. 안정적 신용도와 낮은 채무비중은 대규모 데이터센터·클라우드 인프라 투자나 글로벌 물류 운영에서도 재무적 유연성을 제공하는 기반이 됩니다.

-----------
#8
Question: 삼성SDS의 2024년 3분기말(9월 30일) 연결 기준 부채비율을 재무상태표 수치로 검증하고, 전기말(2023년 12월 31일)과 비교해 변화 요인을 설명하시오.

Ground Truth: 2024년 3분기말 연결 기준 부채총계는 3,409,626,256천원, 자본총계는 9,393,068,289천원으로 공시되어 있습니다. 이를 이용해 계산한 부채비율은 3,409,626,256 ÷ 9,393,068,289 ? 36.30%로, 공시된 부채비율(36.30%)과 일치합니다. 전기말(2023.12.31)에는 부채총계 3,345,453,419천원, 자본총계 8,975,571,142천원으로 부채비율이 37.27%였습니다. 즉, 2024년 들어 부채비율이 36.30%로 개선되었습니다. 같은 기간 지배주주지분이 8,658,009,435,402원에서 9,029,477,673,582원으로 증가(분기순이익 567,196,773,122원, 해외사업환산손익 +46,977,194,013원, 주식보상비용 인식 +5,636,306,702원 등의 누적 효과)한 반면, 부채는 유사한 수준에서 관리되면서 분모(자본) 확대로 비율이 낮아진 것이 주된 요인입니다.

-----------
#9
Question: 2024년 3분기 누적과 2024 사업연도(사업보고서 기준)에서 삼성SDS의 희석주당이익이 기본주당이익과 동일한 이유는 무엇이며, 각 기간의 기본주당이익 산출 근거를 제시하시오.

Ground Truth: 삼성SDS는 당기 및 전기에 희석증권을 보유하지 않아 희석주당이익이 기본주당이익과 동일합니다(사업보고서 주석: "당기 및 전기 중 희석증권을 보유하지 않아 희석주당이익은 기본주당이익과 동일"). 2024년 3분기 누적 연결 기준 기본주당이익은 7,333원(지배기업 소유지분 분기누적 순이익 567,196,773,122원 기준)으로 공시되었고, 동일 값이 희석주당이익으로 재표시되었습니다. 2024 사업보고서(연결)에서는 기본주당이익이 9,787원이며, 산출 근거로 지배기업 소유지분 순이익 756,996,882천원과 가중평균유통보통주식수 77,350,186주가 제시되어 있습니다(756,996,882천원 ÷ 77,350,186주 ? 9,787원). 한편 종속회사(엠로) 차원의 주식선택권이 존재하나 이는 지배기업 보통주에 대한 희석증권이 아니므로 연결 EPS의 희석효과를 발생시키지 않습니다.

-----------
#10
Question: 2024년 삼성SDS의 주식기준보상(엠로 포함) 현황을 수량, 행사가격, 만기, 비용 인식, 자본변동 영향까지 종합해 설명하시오.

Ground Truth: 연결실체 종속회사 (주)엠로의 주식매입선택권이 2024년 보고기간에 연결 주식기준보상의 핵심입니다. 기말 유효한 주식선택권은 총 633,540주이며, 트렌치는 다음과 같습니다: 2차(부여일 2021-10-29, 최장만기 2027-10-29, 행사가 16,440원, 425,440주), 3차(2022-03-25, 2028-03-25, 17,678원, 94,860주), 4차(2023-03-31, 2029-03-31, 43,393원, 43,380주), 5차(2024-03-20, 2030-03-19, 58,405원, 69,860주). 2024년 상반기에는 신규 부여 71,460주, 만료 10,880주가 있었고, 기말 가중평균 행사가격은 23,098원입니다. 비용 측면에서 상반기 주식기준보상비용은 4,018백만원, 3분기에는 6,207백만원이 비용으로 인식되었습니다. 자본변동표에도 2024.09.30 누적 주식보상비용 5,636,306,702원이 기타자본항목에 반영되어 있습니다(기간별 인식시점 차이로 비용계정 vs 자본항목 표시금액의 시차가 존재). 요약하면, 2024년에는 엠로의 지분결제형 옵션이 지속 가득·만기 스케줄을 따르며 비용이 인식되었고, 연결 자본에는 주식보상비용이 증가 요인으로 작용했습니다.

-----------
#11
Question: 온실가스 배출권과 배출부채에 대해, 2024년 중 배출권 수량·장부금액 변동과 기말 배출부채(충당부채) 인식, 담보 제공 여부를 함께 설명하시오.

Ground Truth: 삼성SDS는 3차 계획기간(2021~2025년)에 대해 무상할당을 받고 있으며, 당기 기말 기준 누적 무상할당 수량은 476,076 KAU로 공시되어 있습니다. 2024년 중 배출권 수량 변동은 기초 93,143 KAU에서 무상할당 133,504 KAU, 유상매입 47,089 KAU, 제출(사용) (149,538) KAU를 반영해 기말 124,198 KAU입니다. 장부금액은 기초 0에서 유상매입 415,939천원 인식 후 제출 (149,834)천원을 반영하여 기말 266,105천원입니다. 배출량에 대응한 배출부채는 유동 온실가스배출충당부채로 203,562천원을 인식했습니다. 아울러 당기말 현재 담보로 제공된 배출권은 없다고 공시되어 있습니다. 정리하면, 2024년에는 무상할당과 일부 유상매입으로 확보한 배출권을 제출해 의무를 이행했고, 잔여 배출량에 대해서는 충당부채를 계상했으며, 배출권에 대한 담보 제공은 없습니다.

-----------
#12
Question: 특수관계자와의 배당거래는 2024년에 어떻게 이루어졌으며, 연결 현금흐름에서의 배당금 지급과 어떤 관계가 있습니까?

Ground Truth: 사업보고서 특수관계자 주석에 따르면, 2024년 중 특수관계자로부터 수취한 배당금은 234백만원, 특수관계자에게 지급결의한 배당금은 84,695백만원입니다. 해당 배당과 관련한 미수·미지급 잔액은 당기말에 존재하지 않습니다(각 0). 한편 연결 현금흐름표에서는 2024년 1~9월 누적 배당금 지급이 215,847,813,600원으로 공시되어 있는데, 이는 전체 주주(비특수관계자 포함)에 대한 현금배당을 반영한 금액입니다. 따라서 특수관계자 관련 배당은 전체 현금배당 중 일부이며, 특수관계자 주석은 거래상대방이 특수관계자인 항목만 분리 공시했다는 점에서 연결 현금흐름표의 총배당금 지급액과 항목 범위가 다릅니다.

-----------
#13
Question: 2024년 9월말까지 삼성SDS 연결 자본(지배주주지분)은 어떤 요인들로 증가·감소했는지, 금액을 들어 설명하시오.

Ground Truth: 지배주주지분은 2023.12.31의 8,658,009,435,402원에서 2024.09.30의 9,029,477,673,582원으로 증가했습니다. 주요 증감요인은 다음과 같습니다. 증가 요인: (1) 분기누적 지배주주 순이익 +567,196,773,122원, (2) 해외사업환산손익 +46,977,194,013원, (3) 주식보상비용 인식 +5,636,306,702원. 감소 요인: (4) 연차배당 -208,845,502,200원, (5) 기타포괄손익 중 확정급여 재측정손실 -9,115,146,308원, FVOCI 금융자산평가손익 -367,932,353원, 지분법자본변동 -2,197,421,605원, (6) 종속기업 소유지분 변동 등 기타자본변동 -22,179,726,489원. 종합하면, 실적 호조와 환산이익이 자본 확대로 기여했으나 현금배당과 기타포괄손익의 일부 손실, 지분변동이 일부 상쇄했습니다.

-----------
#14
Question: 2024년 3분기 누적 연구개발(R&D) 활동과 비용은 어떤 특징을 보였는지, 매출 대비 비율과 자산화/비용 처리 내역, 주요 연구 분야를 함께 기술하시오.

Ground Truth: 2024년 3분기 누적 연결 기준 연구개발비용 총계는 175,502,420천원이며, 이 중 개발비 자산화가 19,280,108천원, 연구개발비(기간비용)가 156,222,312천원입니다. 매출 대비 R&D 비율은 1.72%로 공시되어 있으며(동 기간 연결 매출 10,185,908,244,048원 기준 약 1.72%), 전년 동기 대비 확대되었습니다. 연구 분야는 AI(엔터프라이즈 생성형 AI 모델 고도화, RAG 정확도 개선, 코드 LLM 특화, API Retrieval·Conversational QA, 멀티모달 문서·GUI 분석 등), Cloud/HPC(스카이 컴퓨팅 기반 전송, 이기종 스토리지 복제·콜드 스토리지 자동화, LLM 서빙 최적화, GPU 스케줄러 고도화), Security(양자내성암호·PQC 마이그레이션, 이상탐지, 클라우드 네이티브 보안), 네트워크·로드밸런싱 성능 개선 등으로, 사업화와 운영 효율 제고에 직결되는 과제를 폭넓게 수행했습니다.

-----------
#15
Question: 삼성SDS가 2024년 3분기 (주)동아미디어엔 보통주 18.01%만을 보유하면서도 ‘관계기업’으로 분류한 이유와 그 회계적 근거를 공시자료에 근거해 설명하시오.

Ground Truth: 2024년 3분기 공시에 따르면 (주)동아미디어엔은 지분율이 20% 미만(18.01%)임에도 불구하고 관계기업으로 분류되었습니다. 주석에는 “이사회에 참여하거나 경영진의 상호교류가 있어 피투자회사의 재무정책과 영업정책 의사결정 과정에 참여할 수 있으므로 관계기업투자주식으로 분류”했다고 명시되어 있습니다. 이는 K-IFRS에서 지분율 20% 미만이라도 재무·영업정책 결정에 ‘유의적인 영향력’을 행사하면 관계기업(지분법 적용 대상)으로 분류할 수 있다는 정의(사업보고서의 관계기업 회계정책 설명)와 부합합니다. 해당 투자에 대해 삼성SDS는 지분법을 적용해 장부금액 360,988천원을 인식하고 있으며, 이는 단순한 공정가치측정이 아니라 피투자자의 순자산 변동을 반영하는 지분법 회계처리 결과입니다.

-----------
#16
Question: 삼성SDS가 2024년 중 한국정보인증(주) 지분을 전량 처분한 사실이 연결재무제표에 어떤 항목들로 나타났는지, 손익과 장부금액 변화를 함께 설명하시오.

Ground Truth: 관계기업투자주식 주석에 “한국정보인증(주) 당분기 중 전량 매각”이 명시되어 있으며, 기중 변동표에서도 기초 장부금액(8,483,615천원)이 처분으로 0이 된 흐름이 확인됩니다. 처분 손익은 연결 기타수익에 ‘관계기업투자주식 처분이익’ 1,731,221천원이 인식되어 반영되었습니다(2024년 3분기 누적 기준). 처분으로 인해 연결 기준 관계기업투자주식 잔액에서 한국정보인증 관련 금액이 제거되었고, 기존 지분법으로 누적 인식된 금액 및 해당 투자에 연결된 기타포괄손익 누계액은 K-IFRS 기준에 따라 처분 시점에 적절히 재분류 또는 대체됩니다(금액 세부내역은 공시 내 개별 표시 없음).

-----------
#17
Question: 만약 삼성SDS가 CMC Corporation(현재 유효지분율 약 29.83%)의 추가 지분을 취득해 지배력을 확보(종속기업 전환)한다면, 기존 보유지분은 어떤 회계처리를 하게 되며, 공시된 시장가격 정보를 이용할 때 잠재적 재측정손익은 어느 정도로 추정되는가?

Ground Truth: K-IFRS에 따르면 단계적 취득으로 지배력을 확보하는 경우, 기존에 보유하던 관계기업 지분은 취득일 공정가치로 재측정하고 그 차이는 당기손익으로 인식합니다. 공시된 시장정보에 따르면 CMC의 보유주식 수는 56,792,115주, 주당 시장가격은 2,723원으로 공정가치 총액은 약 154,644,929천원입니다. 현재 지분법 장부금액은 64,926,596천원이므로, 지배력 취득 시점에 이 금액을 공정가치로 재측정할 경우 약 89,718,333천원의 재측정이익(세전, 추정치)이 인식될 수 있습니다. 이후에는 CMC를 종속기업으로 연결 편입하고, 취득일 현재 식별가능한 순자산에 공정가치 배분을 수행하며, 잔여분은 영업권으로 인식됩니다. 기존 비지배지분(NCI)은 공정가치 또는 비례법 중 선택한 방식으로 측정됩니다.

-----------
#18
Question: 2024년 중 삼성SDS의 종속기업 지분 관련 변동을 별도·연결 재무제표 관점에서 비교·분석하시오. 사업결합(합병·인수) 여부, 소유지분 변동의 회계처리, 그리고 관련 공시수치를 함께 제시하시오.

Ground Truth: 2024년에는 신규 사업결합이 없었습니다(연결 현금흐름표 ‘사업결합으로 인한 순현금유출 0’, 연결 자본변동표 ‘사업결합 0’). 그럼에도 별도재무제표에서 종속기업투자주식은 2023.12 말 626,664백만원에서 2024.09 말 676,263백만원으로 약 49,599백만원 증가했습니다. 이는 종속기업 지분 추가 취득(또는 증자 참여 등)로 원가법상 취득원가가 증가했음을 시사합니다. 한편 연결 재무제표에서는 지배력을 유지한 상태의 소유지분 변동은 자본거래로 처리되며 당기손익에 반영되지 않습니다. 실제 2024.09 누적 연결 자본변동표에 ‘종속기업에 대한 소유지분의 변동 등’이 (22,179,726,489)원으로 기타자본항목에서 인식되었고, 동시에 비지배지분 변동 21,655,888,941원이 맞물려 표시되었습니다. 요약하면 2024년에는 합병·신규 취득 없이, 기존 종속기업에 대한 지분율 변경(또는 구조조정)이 있었고, 별도는 원가 증가로, 연결은 자본 변동으로 각각 반영되었습니다.

-----------
#19
Question: 삼성SDS가 향후 종속회사와의 합병을 추진하는 경우, 사내 거버넌스와 주주총회 절차 측면에서 어떤 승인과 의결이 필요한가? 현재의 의결권 구조와 함께 설명하시오.

Ground Truth: 회사 이사회 규정에 따르면 합병·분할·분할합병 등은 이사회 부의사항이며, 주주총회 결의 대상입니다(정관·이사회 규정상 중요 사항). 따라서 절차상 ① 이사회에서 합병안 심의·의결 후, ② 주주총회에서 합병계약 승인 결의를 받아야 합니다. 2024년 말 기준 보통주 발행주식총수는 77,377,800주이며, 자기주식 27,614주를 제외한 의결권 행사 가능 주식수는 77,350,186주입니다. 최대주주는 삼성전자(22.58%)이며, 특수관계인 등을 포함한 최대주주 그룹 지분은 48.95%(2024.09.30 기준)입니다. 전자투표 제도도 도입되어 있어 주주총회 의결권 행사가 가능하며, 집중투표제·서면투표제는 미도입입니다. 요컨대 합병 추진 시 이사회와 주주총회라는 이중 승인 절차가 필요하며, 의결권 구조 하에서 법정 요건을 충족하는 찬성이 확보되어야 합니다.

-----------

RAG 체인을 실행해, 테스트 문제에 대한 답변을 생성합니다.

In [ ]:
rag_chain_from_docs = (
    prompt
    | llm
    | StrOutputParser()
)

rag_chain_with_ref = RunnableParallel(
    raw_context = retriever, question = RunnablePassthrough()
).assign(context = lambda x: format_docs(x['raw_context'])).assign(answer=rag_chain_from_docs)

rag_chain_with_ref.invoke("이 보고서는 어느 회사 꺼야?")
# raw_context, question, context, answer

{'raw_context': [Document(id='05034748-0d1c-40dc-a021-005fa132382f', metadata={'source': 'reports\\사업보고서(2025.03.11).pdf', 'index': 2}, page_content='배출부채 (연결).162 38. 사업결합 (연결) .164 39. 주식기준보상 (연결).166 4. 재무제표.170 4-1. 재무상태표.170 4-2. 손익계산서.171 4-3. 포괄손익계산서.172 4-4. 자본변동표.172 4-5. 현금흐름표.172 5. 재무제표 주석.175 1. 당사의 개요.175 2. 별도재무제표 작성기준 및 중요한 회계정책.175 3. 중요한 판단과 추정 불확실성의 주요 원천.199 4. 현금및현금성자산.201 5. 사용이 제한되거나 담보로 제공된 금융자산.201 6. 범주별 금융상품.202 7. 금융상품의 공정가치.205 8. 매출채권 및 미수금.210 9. 재고자산.212 10. 공정가치측정금융자산.213 11. 관계기업투자주식.216 12. 종속기업투자주식.216 13. 유형자산.219 14. 무형자산.220 15. 리스.225 16. 리스부채.226 17. 금융리스채권.228 18. 충당부채.229 19. 퇴직급여제도.231 20. 우발채무와 약정사항.235 21. 납입자본.238 22. 이익잉여금.238 23. 기타자본항목.240 24. 매출액.241 25. 비용의 성격별 분류 등.244 26. 판매비와 관리비.245 27. 기타수익 및 기타비용.247 28. 금융수익 및 금융비용.248 29. 법인세비용.249 30. 현금흐름표.252 31. 재무위험관리.256 32. 특수관계자.262 33. 주당이익.273 34. 재무제표의 승인.274 35. 온실가스 배출권과 배출부채.274 6. 배당에 관한 사항.276 7. 증권의 발행을 통한 자금조달에 관한 사항.278 7-1. 증권의 발행을 통한 자금조달 실적.278 7-2. 증권의 발행을 통해 조달된 자금의 사용실적.281 8. 기타 재무에 관한 사항.282 IV. 이사의 경영진단 및 분석의견.290 V. 회계감사인의 감사의견 등.299 1. 외부감사에 관한 사항.299 2. 내부통제에 관한 사항.302 VI. 이사회 등 회사의 기관에 관한 사항.305 1. 이사회에 관한 사항.305 2. 감사제도에 관한 사항.313 3. 주주총회 등에 관한 사항.319 VII. 주주에 관한 사항.323 VIII. 임원 및 직원 등에 관한 사항.328 1. 임원 및 직원 등의 현황.328 2. 임원의 보수 등.334 IX. 계열회사 등에 관한 사항.343 X. 대주주 등과의 거래내용.364 XI. 그 밖에 투자자 보호를 위하여 필요한 사항.367 1. 공시내용 진행 및 변경사항.367 2. 우발부채 등에 관한 사항.367 3. 제재 등과 관련된 사항.369 4. 작성기준일 이후 발생한 주요사항 등 기타사항.369 XII. 상세표.371 1. 연결대상 종속회사 현황(상세) .371 2. 계열회사 현황(상세) .372 3. 타법인출자 현황(상세).387 【 전문가의 확인 】.390 1. 전문가의 확인.390 2. 전문가와의 이해관계.390 사 업 보 고 서 (제 40 기) 사업연도 2024년 01월 01일 부터 2024년 12월 31일 까지 금융위원회 한국거래소 귀중 2025년 3월 11일 제출대상법인 유형 : 주권상장법인 면제사유발생 : 해당사항 없음 회 사 명 :'),
  Document(id='2f5b4fda-961e-4983-a13d-df26ad3d4540', metadata={'index': 2, 'source': 'reports\\사업보고서(2025.03.11).pdf'}, page_content='목 차 사 업 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 1. 회사의 개요.3 2. 회사의 연혁.5 3. 자본금 변동사항.8 4. 주식의 총수 등.9 5. 정관에 관한 사항.10 II. 사업의 내용.12 1. 사업의 개요.12 2. 주요 제품 및 서비스.13 3. 원재료 및 생산설비.17 4. 매출 및 수주상황.20 5. 위험관리 및 파생거래.21 6. 주요계약 및 연구개발활동.23 7. 기타 참고사항.25 III. 재무에 관한 사항.35 1. 요약재무정보.35 2. 연결재무제표.38 2-1. 연결 재무상태표.38 2-2. 연결 손익계산서.39 2-3. 연결 포괄손익계산서.40 2-4. 연결 자본변동표.40 2-5. 연결 현금흐름표.41 3. 연결재무제표 주석.43 1. 지배기업의 개요 (연결) .43 2. 연결재무제표 작성기준 및 중요한 회계정책 (연결).43 3. 중요한 판단과 추정 불확실성의 주요 원천 (연결) .71 4. 영업부문 (연결) .73 5. 현금및현금성자산 (연결).76 6. 사용이 제한되거나 담보로 제공된 금융자산 (연결).76 7. 범주별 금융상품 (연결) .77 8. 금융상품의 공정가치 (연결) .80 9. 매출채권 및 미수금 (연결) .85 10. 재고자산 (연결) .87 11. 공정가치측정금융자산 (연결).88 12. 관계기업투자주식 (연결).91 13. 종속기업 (연결) .94 14. 유형자산 (연결) .102 15. 무형자산 (연결) .104 16. 투자부동산 (연결).109 17. 리스 (연결) .111 18. 리스부채 (연결) .113 19. 금융리스채권 (연결).114 20. 충당부채 (연결) .115 21. 퇴직급여제도 (연결).119 22. 우발채무와 약정사항 (연결) .123 23. 납입자본 (연결) .126 24. 이익잉여금 (연결).127 25. 기타자본항목 (연결).128 26. 매출액 (연결).130 27. 비용의 성격별 분류 등 (연결).132 28. 판매비와 관리비 (연결).134 29. 기타수익 및 기타비용 (연결).135 30. 금융수익 및 금융비용 (연결).137 31. 법인세비용 (연결).138 32. 현금흐름표 (연결).141 33. 재무위험관리 (연결).144 34. 특수관계자 (연결).151 35. 주당이익 (연결) .161 36. 재무제표의 승인 (연결).162 37. 온실가스 배출권과 배출부채 (연결).162 38. 사업결합 (연결) .164 39. 주식기준보상 (연결).166 4. 재무제표.170 4-1. 재무상태표.170 4-2. 손익계산서.171 4-3. 포괄손익계산서.172 4-4. 자본변동표.172 4-5. 현금흐름표.172 5. 재무제표 주석.175 1. 당사의 개요.175 2. 별도재무제표 작성기준 및 중요한 회계정책.175 3. 중요한 판단과 추정 불확실성의 주요 원천.199 4. 현금및현금성자산.201 5. 사용이 제한되거나 담보로 제공된 금융자산.201'),
  Document(id='2b1a83be-9405-4614-80a8-36649c68ac13', metadata={'index': 0, 'source': 'reports\\반기보고서(2024.08.14).pdf'}, page_content='Cloud 서비스 운영감사보고서 발행 용 역 2023.12 ~ 2024.01 54 삼일회계법인 2023.11 IT서비스 운영감사보고서 발행 용역 2023.11 ~ 2023.12 75 삼일회계법인 2023.08 세무조정 업무 2023.08 ~ 2024.04 50 삼일회계법인 2022.12 Cloud 서비스 운영감사보고서 발행 용 역 2022.12 ~ 2023.01 54 삼일회계법인 제38기 (전전기) 2022.11 물류시스템 운영통제 적절성 검증 2022.11 ~ 2022.12 52 안진회계법인 2022.10 국제거래정보 통합보고서 작성 2022.10 ~ 2023.01 50 안진회계법인 2022.07 ERP 컨설팅 용역 2022.07 ~ 2023.01 810 안진회계법인 2022.05 세무조정 업무 2022.05 ~ 2023.03 45 안진회계법인 구분 일자 참석자 방식 주요 논의 내용 1 2024년 01월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2023년 회계 및 내부회계관리제 도 감사 진행경과 2 2024년 02월 20일 감사위원회 삼일회계법인 업무수행이사 외 1명 대면회의 2023년 회계 및 내부회계관리제 도 감사결과 3 2024년 04월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2024년 회계 및 내부회계관리제 도 감사계획 4 2024년 07월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2024년 회계 및 내부회계관리제 도 감사 진행경과 전자공시시스템 dart.fss.or.kr Page 190 이는 「주식회사 등의 외부감사에 관한 법률」제11조 2항 및 「외부감사 및 회계 등에 관한 규정」제10조에 의거한 감사인 주기적 지정에 따른 회계감사인 변경입니다. 제40기 반기말(당반기) 당사의 종속기업은 48개이며 당반기 중 국내종속기업인 엠로는 다산 회계법인에서 삼일회계법인(PwC)으로 회계감사인을 변경하였고, 해외종속기업인 Samsung SDS Global SCL Hong Kong Limited는 KPMG에서 PwC로 회계감사인을 변경하였습니다. [제40기 종속기업의 회계감사인 변경 현황] 제39기말(전기) 당사의 종속기업은 47개이며, 당기 중 멀티캠퍼스 등 2개 국내종속기업은 안진회계법인(Deloitte)에서 삼일회계법인(PwC)으로 회계감사인을 변경하였고, Samsung SDS America, Inc. 등 3개 해외종속기업은 Deloitte에서 PwC로, Samsung SDS China Co., Ltd. 등 2개 해외종속기업은 KPMG에서 PwC로, PT. Samsung SDS Global SCL Indonesia 등 2개 해외종속기업은 EY에서 PwC로, Samsung SDS Global SCL Slovakia, S.R.O. 등 2개 해외종속기업은 Deloitte에서 KPMG로, Samsung SDS Global SCL Malaysia Sdn.Bhd. 는 KPMG에서 Deloitte로 회계감사인을 변경하였습니다. [제39기 종속기업의 회계감사인 변경 현황] 제38기말(전전기) 당사의 종속기업은 48개입니다. 이 중 해외 종속기업인 Samsung SDS Global SCL Nakliyat ve Lojistik Anonim Sirketi는 PwC에서 Deloitte로 회계감사인을 변경하였습니다. [제38기 종속기업의 회계감사인 변경 현황] 구 분 종속기업명 변경전 회계감사인 변경후 회계감사인 국내종속기업 (주)엠로 다산회계법인 삼일회계법인(PwC) 해외종속기업 Samsung SDS Global SCL Hong Kong Limited KPMG PwC 구 분'),
  Document(id='16e84624-0fc2-49d0-9037-cd6127782fbb', metadata={'source': 'reports\\분기보고서(2024.11.14).pdf', 'index': 1}, page_content='회계정책.104 3. 중요한 판단과 추정 불확실성의 주요 원천.105 4. 범주별 금융상품.106 5. 공정가치.107 6. 공정가치측정금융자산.111 7. 관계기업투자주식.113 8. 종속기업투자주식.114 9. 유형자산.116 10. 무형자산.116 11. 리스.117 12. 리스부채.120 13. 금융리스채권.121 14. 충당부채.123 15. 재무위험관리.125 16. 우발채무와 약정사항.127 17. 납입자본.129 18. 이익잉여금.129 19. 기타자본항목.130 20. 매출액.131 21. 판매비와 관리비.134 22. 기타수익 및 기타비용.135 23. 금융수익 및 금융비용.137 24. 법인세비용.138 25. 현금흐름표.138 26. 주당이익.141 27. 특수관계자.142 6. 배당에 관한 사항.154 7. 증권의 발행을 통한 자금조달에 관한 사항.155 7-1. 증권의 발행을 통한 자금조달 실적.155 7-2. 증권의 발행을 통해 조달된 자금의 사용실적.158 8. 기타 재무에 관한 사항.159 IV. 이사의 경영진단 및 분석의견.166 V. 회계감사인의 감사의견 등.167 1. 외부감사에 관한 사항.167 2. 내부통제에 관한 사항.170 VI. 이사회 등 회사의 기관에 관한 사항.171 1. 이사회에 관한 사항.171 2. 감사제도에 관한 사항.171 3. 주주총회 등에 관한 사항.171 VII. 주주에 관한 사항.172 VIII. 임원 및 직원 등에 관한 사항.176 1. 임원 및 직원 등의 현황.176 2. 임원의 보수 등.180 IX. 계열회사 등에 관한 사항.181 X. 대주주 등과의 거래내용.182 XI. 그 밖에 투자자 보호를 위하여 필요한 사항.184 1. 공시내용 진행 및 변경사항.184 2. 우발부채 등에 관한 사항.184 3. 제재 등과 관련된 사항.185 4. 작성기준일 이후 발생한 주요사항 등 기타사항.185 XII. 상세표.187 1. 연결대상 종속회사 현황(상세) .187 2. 계열회사 현황(상세) .187 3. 타법인출자 현황(상세).187 【 전문가의 확인 】.188 1. 전문가의 확인.188 2. 전문가와의 이해관계.188 분 기 보 고 서 (제 40 기 3분기) 사업연도 2024년 01월 01일 부터 2024년 09월 30일 까지 금융위원회 한국거래소 귀중 2024년 11월 14일 제출대상법인 유형 : 주권상장법인 면제사유발생 : 해당사항 없음 회 사 명 : 삼성에스디에스(주) 대 표 이 사 : 황 성 우 본 점 소 재 지 : 서울특별시 송파구 올림픽로 35길 125 (신천동) (전 화) 02-6155-3114 (홈페이지) http://www.samsungsds.com 작 성 책 임 자 : (직 책) 경영지원실장 (성 명) 안 정 태 (전 화) 02-6155-5114 전자공시시스템 dart.fss.or.kr Page 1 【 대표이사 등의 확인 】 전자공시시스템 dart.fss.or.kr Page 2 I. 회사의 개요 1. 회사의 개요 회사의 개요는 기업공시서식 작성기준에 따라 분기보고서에 기재하지 않습니다.(반기/사업 보고서에 기재 예정) 2. 회사의 연혁 회사의 연혁은 기업공시서식 작성기준에 따라 분기보고서에 기재하지 않습니다.(반기/사업 보고서에 기재 예정) 3. 자본금 변동사항 자본금 변동사항은 기업공시서식 작성기준에 따라'),
  Document(id='890650c2-180b-4f62-82e7-502553a62823', metadata={'source': 'reports\\분기보고서(2024.11.14).pdf', 'index': 1}, page_content='목 차 분 기 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 1. 회사의 개요.3 2. 회사의 연혁.3 3. 자본금 변동사항.3 4. 주식의 총수 등.3 5. 정관에 관한 사항.3 II. 사업의 내용.4 1. 사업의 개요.4 2. 주요 제품 및 서비스.5 3. 원재료 및 생산설비.9 4. 매출 및 수주상황.11 5. 위험관리 및 파생거래.13 6. 주요계약 및 연구개발활동.15 7. 기타 참고사항.17 III. 재무에 관한 사항.26 1. 요약재무정보.26 2. 연결재무제표.29 2-1. 연결 재무상태표.29 2-2. 연결 손익계산서.30 2-3. 연결 포괄손익계산서.31 2-4. 연결 자본변동표.31 2-5. 연결 현금흐름표.32 3. 연결재무제표 주석.34 1. 지배기업의 개요 (연결) .34 2. 연결재무제표 작성기준 및 중요한 회계정책 (연결).34 3. 중요한 판단과 추정 불확실성의 주요 원천 (연결) .35 4. 영업부문 (연결) .36 5. 범주별 금융상품 (연결) .39 6. 공정가치 (연결) .40 7. 공정가치측정금융자산 (연결).44 8. 관계기업투자주식 (연결).47 9. 종속기업 (연결) .49 10. 유형자산 (연결) .57 11. 무형자산 (연결) .57 12. 투자부동산 (연결).59 13. 리스 (연결) .60 14. 리스부채 (연결) .62 15. 금융리스채권 (연결).64 16. 충당부채 (연결) .65 17. 재무위험관리 (연결).68 18. 우발채무와 약정사항 (연결) .70 19. 납입자본 (연결) .73 20. 이익잉여금 (연결).73 21. 기타자본항목 (연결).74 22. 매출액 (연결).75 23. 판매비와 관리비 (연결).78 24. 기타수익 및 기타비용 (연결).80 25. 금융수익 및 금융비용 (연결).81 26. 법인세비용 (연결).83 27. 현금흐름표 (연결).83 28. 주당이익 (연결) .86 29. 특수관계자 (연결).87 30. 주식기준보상 (연결).96 4. 재무제표.100 4-1. 재무상태표.100 4-2. 손익계산서.101 4-3. 포괄손익계산서.102 4-4. 자본변동표.102 4-5. 현금흐름표.102 5. 재무제표 주석.104 1. 당사의 개요.104 2. 별도재무제표 작성기준 및 중요한 회계정책.104 3. 중요한 판단과 추정 불확실성의 주요 원천.105 4. 범주별 금융상품.106 5. 공정가치.107 6. 공정가치측정금융자산.111 7. 관계기업투자주식.113 8. 종속기업투자주식.114 9. 유형자산.116 10. 무형자산.116 11. 리스.117 12. 리스부채.120 13. 금융리스채권.121 14. 충당부채.123 15. 재무위험관리.125 16. 우발채무와 약정사항.127 17. 납입자본.129 18. 이익잉여금.129 19. 기타자본항목.130 20. 매출액.131 21. 판매비와')],
 'question': '이 보고서는 어느 회사 꺼야?',
 'context': '배출부채 (연결).162 38. 사업결합 (연결) .164 39. 주식기준보상 (연결).166 4. 재무제표.170 4-1. 재무상태표.170 4-2. 손익계산서.171 4-3. 포괄손익계산서.172 4-4. 자본변동표.172 4-5. 현금흐름표.172 5. 재무제표 주석.175 1. 당사의 개요.175 2. 별도재무제표 작성기준 및 중요한 회계정책.175 3. 중요한 판단과 추정 불확실성의 주요 원천.199 4. 현금및현금성자산.201 5. 사용이 제한되거나 담보로 제공된 금융자산.201 6. 범주별 금융상품.202 7. 금융상품의 공정가치.205 8. 매출채권 및 미수금.210 9. 재고자산.212 10. 공정가치측정금융자산.213 11. 관계기업투자주식.216 12. 종속기업투자주식.216 13. 유형자산.219 14. 무형자산.220 15. 리스.225 16. 리스부채.226 17. 금융리스채권.228 18. 충당부채.229 19. 퇴직급여제도.231 20. 우발채무와 약정사항.235 21. 납입자본.238 22. 이익잉여금.238 23. 기타자본항목.240 24. 매출액.241 25. 비용의 성격별 분류 등.244 26. 판매비와 관리비.245 27. 기타수익 및 기타비용.247 28. 금융수익 및 금융비용.248 29. 법인세비용.249 30. 현금흐름표.252 31. 재무위험관리.256 32. 특수관계자.262 33. 주당이익.273 34. 재무제표의 승인.274 35. 온실가스 배출권과 배출부채.274 6. 배당에 관한 사항.276 7. 증권의 발행을 통한 자금조달에 관한 사항.278 7-1. 증권의 발행을 통한 자금조달 실적.278 7-2. 증권의 발행을 통해 조달된 자금의 사용실적.281 8. 기타 재무에 관한 사항.282 IV. 이사의 경영진단 및 분석의견.290 V. 회계감사인의 감사의견 등.299 1. 외부감사에 관한 사항.299 2. 내부통제에 관한 사항.302 VI. 이사회 등 회사의 기관에 관한 사항.305 1. 이사회에 관한 사항.305 2. 감사제도에 관한 사항.313 3. 주주총회 등에 관한 사항.319 VII. 주주에 관한 사항.323 VIII. 임원 및 직원 등에 관한 사항.328 1. 임원 및 직원 등의 현황.328 2. 임원의 보수 등.334 IX. 계열회사 등에 관한 사항.343 X. 대주주 등과의 거래내용.364 XI. 그 밖에 투자자 보호를 위하여 필요한 사항.367 1. 공시내용 진행 및 변경사항.367 2. 우발부채 등에 관한 사항.367 3. 제재 등과 관련된 사항.369 4. 작성기준일 이후 발생한 주요사항 등 기타사항.369 XII. 상세표.371 1. 연결대상 종속회사 현황(상세) .371 2. 계열회사 현황(상세) .372 3. 타법인출자 현황(상세).387 【 전문가의 확인 】.390 1. 전문가의 확인.390 2. 전문가와의 이해관계.390 사 업 보 고 서 (제 40 기) 사업연도 2024년 01월 01일 부터 2024년 12월 31일 까지 금융위원회 한국거래소 귀중 2025년 3월 11일 제출대상법인 유형 : 주권상장법인 면제사유발생 : 해당사항 없음 회 사 명 :\n \n---\n 목 차 사 업 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 1. 회사의 개요.3 2. 회사의 연혁.5 3. 자본금 변동사항.8 4. 주식의 총수 등.9 5. 정관에 관한 사항.10 II. 사업의 내용.12 1. 사업의 개요.12 2. 주요 제품 및 서비스.13 3. 원재료 및 생산설비.17 4. 매출 및 수주상황.20 5. 위험관리 및 파생거래.21 6. 주요계약 및 연구개발활동.23 7. 기타 참고사항.25 III. 재무에 관한 사항.35 1. 요약재무정보.35 2. 연결재무제표.38 2-1. 연결 재무상태표.38 2-2. 연결 손익계산서.39 2-3. 연결 포괄손익계산서.40 2-4. 연결 자본변동표.40 2-5. 연결 현금흐름표.41 3. 연결재무제표 주석.43 1. 지배기업의 개요 (연결) .43 2. 연결재무제표 작성기준 및 중요한 회계정책 (연결).43 3. 중요한 판단과 추정 불확실성의 주요 원천 (연결) .71 4. 영업부문 (연결) .73 5. 현금및현금성자산 (연결).76 6. 사용이 제한되거나 담보로 제공된 금융자산 (연결).76 7. 범주별 금융상품 (연결) .77 8. 금융상품의 공정가치 (연결) .80 9. 매출채권 및 미수금 (연결) .85 10. 재고자산 (연결) .87 11. 공정가치측정금융자산 (연결).88 12. 관계기업투자주식 (연결).91 13. 종속기업 (연결) .94 14. 유형자산 (연결) .102 15. 무형자산 (연결) .104 16. 투자부동산 (연결).109 17. 리스 (연결) .111 18. 리스부채 (연결) .113 19. 금융리스채권 (연결).114 20. 충당부채 (연결) .115 21. 퇴직급여제도 (연결).119 22. 우발채무와 약정사항 (연결) .123 23. 납입자본 (연결) .126 24. 이익잉여금 (연결).127 25. 기타자본항목 (연결).128 26. 매출액 (연결).130 27. 비용의 성격별 분류 등 (연결).132 28. 판매비와 관리비 (연결).134 29. 기타수익 및 기타비용 (연결).135 30. 금융수익 및 금융비용 (연결).137 31. 법인세비용 (연결).138 32. 현금흐름표 (연결).141 33. 재무위험관리 (연결).144 34. 특수관계자 (연결).151 35. 주당이익 (연결) .161 36. 재무제표의 승인 (연결).162 37. 온실가스 배출권과 배출부채 (연결).162 38. 사업결합 (연결) .164 39. 주식기준보상 (연결).166 4. 재무제표.170 4-1. 재무상태표.170 4-2. 손익계산서.171 4-3. 포괄손익계산서.172 4-4. 자본변동표.172 4-5. 현금흐름표.172 5. 재무제표 주석.175 1. 당사의 개요.175 2. 별도재무제표 작성기준 및 중요한 회계정책.175 3. 중요한 판단과 추정 불확실성의 주요 원천.199 4. 현금및현금성자산.201 5. 사용이 제한되거나 담보로 제공된 금융자산.201\n \n---\n Cloud 서비스 운영감사보고서 발행 용 역 2023.12 ~ 2024.01 54 삼일회계법인 2023.11 IT서비스 운영감사보고서 발행 용역 2023.11 ~ 2023.12 75 삼일회계법인 2023.08 세무조정 업무 2023.08 ~ 2024.04 50 삼일회계법인 2022.12 Cloud 서비스 운영감사보고서 발행 용 역 2022.12 ~ 2023.01 54 삼일회계법인 제38기 (전전기) 2022.11 물류시스템 운영통제 적절성 검증 2022.11 ~ 2022.12 52 안진회계법인 2022.10 국제거래정보 통합보고서 작성 2022.10 ~ 2023.01 50 안진회계법인 2022.07 ERP 컨설팅 용역 2022.07 ~ 2023.01 810 안진회계법인 2022.05 세무조정 업무 2022.05 ~ 2023.03 45 안진회계법인 구분 일자 참석자 방식 주요 논의 내용 1 2024년 01월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2023년 회계 및 내부회계관리제 도 감사 진행경과 2 2024년 02월 20일 감사위원회 삼일회계법인 업무수행이사 외 1명 대면회의 2023년 회계 및 내부회계관리제 도 감사결과 3 2024년 04월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2024년 회계 및 내부회계관리제 도 감사계획 4 2024년 07월 25일 감사위원회 삼일회계법인 업무수행이사 외 2명 대면회의 2024년 회계 및 내부회계관리제 도 감사 진행경과 전자공시시스템 dart.fss.or.kr Page 190 이는 「주식회사 등의 외부감사에 관한 법률」제11조 2항 및 「외부감사 및 회계 등에 관한 규정」제10조에 의거한 감사인 주기적 지정에 따른 회계감사인 변경입니다. 제40기 반기말(당반기) 당사의 종속기업은 48개이며 당반기 중 국내종속기업인 엠로는 다산 회계법인에서 삼일회계법인(PwC)으로 회계감사인을 변경하였고, 해외종속기업인 Samsung SDS Global SCL Hong Kong Limited는 KPMG에서 PwC로 회계감사인을 변경하였습니다. [제40기 종속기업의 회계감사인 변경 현황] 제39기말(전기) 당사의 종속기업은 47개이며, 당기 중 멀티캠퍼스 등 2개 국내종속기업은 안진회계법인(Deloitte)에서 삼일회계법인(PwC)으로 회계감사인을 변경하였고, Samsung SDS America, Inc. 등 3개 해외종속기업은 Deloitte에서 PwC로, Samsung SDS China Co., Ltd. 등 2개 해외종속기업은 KPMG에서 PwC로, PT. Samsung SDS Global SCL Indonesia 등 2개 해외종속기업은 EY에서 PwC로, Samsung SDS Global SCL Slovakia, S.R.O. 등 2개 해외종속기업은 Deloitte에서 KPMG로, Samsung SDS Global SCL Malaysia Sdn.Bhd. 는 KPMG에서 Deloitte로 회계감사인을 변경하였습니다. [제39기 종속기업의 회계감사인 변경 현황] 제38기말(전전기) 당사의 종속기업은 48개입니다. 이 중 해외 종속기업인 Samsung SDS Global SCL Nakliyat ve Lojistik Anonim Sirketi는 PwC에서 Deloitte로 회계감사인을 변경하였습니다. [제38기 종속기업의 회계감사인 변경 현황] 구 분 종속기업명 변경전 회계감사인 변경후 회계감사인 국내종속기업 (주)엠로 다산회계법인 삼일회계법인(PwC) 해외종속기업 Samsung SDS Global SCL Hong Kong Limited KPMG PwC 구 분\n \n---\n 회계정책.104 3. 중요한 판단과 추정 불확실성의 주요 원천.105 4. 범주별 금융상품.106 5. 공정가치.107 6. 공정가치측정금융자산.111 7. 관계기업투자주식.113 8. 종속기업투자주식.114 9. 유형자산.116 10. 무형자산.116 11. 리스.117 12. 리스부채.120 13. 금융리스채권.121 14. 충당부채.123 15. 재무위험관리.125 16. 우발채무와 약정사항.127 17. 납입자본.129 18. 이익잉여금.129 19. 기타자본항목.130 20. 매출액.131 21. 판매비와 관리비.134 22. 기타수익 및 기타비용.135 23. 금융수익 및 금융비용.137 24. 법인세비용.138 25. 현금흐름표.138 26. 주당이익.141 27. 특수관계자.142 6. 배당에 관한 사항.154 7. 증권의 발행을 통한 자금조달에 관한 사항.155 7-1. 증권의 발행을 통한 자금조달 실적.155 7-2. 증권의 발행을 통해 조달된 자금의 사용실적.158 8. 기타 재무에 관한 사항.159 IV. 이사의 경영진단 및 분석의견.166 V. 회계감사인의 감사의견 등.167 1. 외부감사에 관한 사항.167 2. 내부통제에 관한 사항.170 VI. 이사회 등 회사의 기관에 관한 사항.171 1. 이사회에 관한 사항.171 2. 감사제도에 관한 사항.171 3. 주주총회 등에 관한 사항.171 VII. 주주에 관한 사항.172 VIII. 임원 및 직원 등에 관한 사항.176 1. 임원 및 직원 등의 현황.176 2. 임원의 보수 등.180 IX. 계열회사 등에 관한 사항.181 X. 대주주 등과의 거래내용.182 XI. 그 밖에 투자자 보호를 위하여 필요한 사항.184 1. 공시내용 진행 및 변경사항.184 2. 우발부채 등에 관한 사항.184 3. 제재 등과 관련된 사항.185 4. 작성기준일 이후 발생한 주요사항 등 기타사항.185 XII. 상세표.187 1. 연결대상 종속회사 현황(상세) .187 2. 계열회사 현황(상세) .187 3. 타법인출자 현황(상세).187 【 전문가의 확인 】.188 1. 전문가의 확인.188 2. 전문가와의 이해관계.188 분 기 보 고 서 (제 40 기 3분기) 사업연도 2024년 01월 01일 부터 2024년 09월 30일 까지 금융위원회 한국거래소 귀중 2024년 11월 14일 제출대상법인 유형 : 주권상장법인 면제사유발생 : 해당사항 없음 회 사 명 : 삼성에스디에스(주) 대 표 이 사 : 황 성 우 본 점 소 재 지 : 서울특별시 송파구 올림픽로 35길 125 (신천동) (전 화) 02-6155-3114 (홈페이지) http://www.samsungsds.com 작 성 책 임 자 : (직 책) 경영지원실장 (성 명) 안 정 태 (전 화) 02-6155-5114 전자공시시스템 dart.fss.or.kr Page 1 【 대표이사 등의 확인 】 전자공시시스템 dart.fss.or.kr Page 2 I. 회사의 개요 1. 회사의 개요 회사의 개요는 기업공시서식 작성기준에 따라 분기보고서에 기재하지 않습니다.(반기/사업 보고서에 기재 예정) 2. 회사의 연혁 회사의 연혁은 기업공시서식 작성기준에 따라 분기보고서에 기재하지 않습니다.(반기/사업 보고서에 기재 예정) 3. 자본금 변동사항 자본금 변동사항은 기업공시서식 작성기준에 따라\n \n---\n 목 차 분 기 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 1. 회사의 개요.3 2. 회사의 연혁.3 3. 자본금 변동사항.3 4. 주식의 총수 등.3 5. 정관에 관한 사항.3 II. 사업의 내용.4 1. 사업의 개요.4 2. 주요 제품 및 서비스.5 3. 원재료 및 생산설비.9 4. 매출 및 수주상황.11 5. 위험관리 및 파생거래.13 6. 주요계약 및 연구개발활동.15 7. 기타 참고사항.17 III. 재무에 관한 사항.26 1. 요약재무정보.26 2. 연결재무제표.29 2-1. 연결 재무상태표.29 2-2. 연결 손익계산서.30 2-3. 연결 포괄손익계산서.31 2-4. 연결 자본변동표.31 2-5. 연결 현금흐름표.32 3. 연결재무제표 주석.34 1. 지배기업의 개요 (연결) .34 2. 연결재무제표 작성기준 및 중요한 회계정책 (연결).34 3. 중요한 판단과 추정 불확실성의 주요 원천 (연결) .35 4. 영업부문 (연결) .36 5. 범주별 금융상품 (연결) .39 6. 공정가치 (연결) .40 7. 공정가치측정금융자산 (연결).44 8. 관계기업투자주식 (연결).47 9. 종속기업 (연결) .49 10. 유형자산 (연결) .57 11. 무형자산 (연결) .57 12. 투자부동산 (연결).59 13. 리스 (연결) .60 14. 리스부채 (연결) .62 15. 금융리스채권 (연결).64 16. 충당부채 (연결) .65 17. 재무위험관리 (연결).68 18. 우발채무와 약정사항 (연결) .70 19. 납입자본 (연결) .73 20. 이익잉여금 (연결).73 21. 기타자본항목 (연결).74 22. 매출액 (연결).75 23. 판매비와 관리비 (연결).78 24. 기타수익 및 기타비용 (연결).80 25. 금융수익 및 금융비용 (연결).81 26. 법인세비용 (연결).83 27. 현금흐름표 (연결).83 28. 주당이익 (연결) .86 29. 특수관계자 (연결).87 30. 주식기준보상 (연결).96 4. 재무제표.100 4-1. 재무상태표.100 4-2. 손익계산서.101 4-3. 포괄손익계산서.102 4-4. 자본변동표.102 4-5. 현금흐름표.102 5. 재무제표 주석.104 1. 당사의 개요.104 2. 별도재무제표 작성기준 및 중요한 회계정책.104 3. 중요한 판단과 추정 불확실성의 주요 원천.105 4. 범주별 금융상품.106 5. 공정가치.107 6. 공정가치측정금융자산.111 7. 관계기업투자주식.113 8. 종속기업투자주식.114 9. 유형자산.116 10. 무형자산.116 11. 리스.117 12. 리스부채.120 13. 금융리스채권.121 14. 충당부채.123 15. 재무위험관리.125 16. 우발채무와 약정사항.127 17. 납입자본.129 18. 이익잉여금.129 19. 기타자본항목.130 20. 매출액.131 21. 판매비와\n',
 'answer': '이 보고서는 삼성에스디에스(주)의 것임을 알 수 있습니다.'}

In [48]:
from tqdm import tqdm

results = rag_chain_with_ref.batch(questions)

dataset=[]

for result, reference in tqdm(zip(results,ground_truths)):
    dataset.append(
        {
            "user_input":result['question'],
            "retrieved_contexts":[doc.page_content for doc in result['raw_context']],
            "response":result['answer'],
            "reference":reference
        }
    )

20it [00:00, 19017.47it/s]

In [ ]:
# # [질문, 검색결과, 답변, 정답(레퍼런스)]
# for query,reference in tqdm(zip(questions,ground_truths)):

#     relevant_docs = [doc.page_content for doc in retriever.invoke(query)]
#     response = rag_chain.invoke(query)
#     dataset.append(
#         {
#             "user_input":query,
#             "retrieved_contexts":relevant_docs,
#             "response":response,
#             "reference":reference
#         }
#     )

20it [01:08,  3.41s/it]

In [49]:
from ragas import EvaluationDataset
evaluation_dataset = EvaluationDataset.from_list(dataset)
evaluation_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=20)

RAGAS는 LLM을 이용해 정답과 답변을 개별 Claim(주장)으로 분할합니다.

이후, `LLMContextRecall`, `Faithfulness`, `FactualCorrectness` 등의 다양한 메트릭을 통해 RAG 파이프라인의 성능을 평가합니다.   
LLM 기반의 방법이므로 평가 LLM의 선정이 중요하며, 절대 수치보다는 상대적 비교가 효과적입니다.


- Context Recall: 정답의 Claim들이 모두 검색됐는가
- Faithfulness : 답변의 Claim이 얼마나 검색 결과에 근거했는가
- Factual Correctness : 정답과 답변의 Claim이 얼마나 일치하는가
- Bleu Score : 정답과 답변 키워드가 얼마나 일치하는가
- Semantic Sim : 정답 답변 임베딩이 얼마나 가까운가

1) Context Recall: 검색 결과 - 정답

낮은 값 --> Retrieval 실패

2) Faithfulness: 검색 결과 - 답변

낮은 값 --> LLM의 성능 문제

3) Factual Correctness: 정답 - 답변

F1 Score 방식

In [50]:
from ragas import evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness
from ragas.metrics import BleuScore, SemanticSimilarity

# https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/

# 평가자 LLM
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))

# 평가자 Embedding
evaluator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model = 'text-embedding-3-large'))
semantic_scorer = SemanticSimilarity(embeddings = evaluator_embeddings)


result = evaluate(dataset=evaluation_dataset,
                  metrics=[BleuScore(), LLMContextRecall(), semantic_scorer, Faithfulness(), FactualCorrectness()],
                  llm=evaluator_llm,
                  embeddings = evaluator_embeddings
                  )
result

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

{'bleu_score': 0.0397, 'context_recall': 0.6558, 'semantic_similarity': 0.5248, 'faithfulness': 0.5666, 'factual_correctness(mode=f1)': 0.2140}

In [53]:
result.scores

[{'bleu_score': 0.029189453645337295,
  'context_recall': 1.0,
  'semantic_similarity': 0.7769170222691305,
  'faithfulness': 1.0,
  'factual_correctness(mode=f1)': np.float64(0.45)},
 {'bleu_score': 0.028848167261307532,
  'context_recall': 0.8,
  'semantic_similarity': 0.6700853643309139,
  'faithfulness': 0.9444444444444444,
  'factual_correctness(mode=f1)': np.float64(0.36)},
 {'bleu_score': 0.029809077846520732,
  'context_recall': 1.0,
  'semantic_similarity': 0.8510903628726033,
  'faithfulness': 0.9333333333333333,
  'factual_correctness(mode=f1)': np.float64(0.6)},
 {'bleu_score': 0.023901021968803136,
  'context_recall': 1.0,
  'semantic_similarity': 0.7558906952664655,
  'faithfulness': 1.0,
  'factual_correctness(mode=f1)': np.float64(0.72)},
 {'bleu_score': 0.015330462064343475,
  'context_recall': 1.0,
  'semantic_similarity': 0.19665467940885206,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.0024510303821316144,
  'context_recall': 1.0,
  'semantic_similarity': 0.1439676451167686,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.07474875887495341,
  'context_recall': 0.8,
  'semantic_similarity': 0.8034262618627196,
  'faithfulness': 0.6470588235294118,
  'factual_correctness(mode=f1)': np.float64(0.65)},
 {'bleu_score': 0.012976955971595585,
  'context_recall': 0.5,
  'semantic_similarity': 0.1526611607906722,
  'faithfulness': 1.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.012962405344232954,
  'context_recall': 1.0,
  'semantic_similarity': 0.7003139375460035,
  'faithfulness': 0.9166666666666666,
  'factual_correctness(mode=f1)': np.float64(0.26)},
 {'bleu_score': 0.00787092166651367,
  'context_recall': 0.5,
  'semantic_similarity': 0.1448080721804334,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.04167251645138561,
  'context_recall': 0.6666666666666666,
  'semantic_similarity': 0.18447984567748626,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.11724489878110317,
  'context_recall': 0.16666666666666666,
  'semantic_similarity': 0.6459244617949033,
  'faithfulness': 1.0,
  'factual_correctness(mode=f1)': np.float64(0.2)},
 {'bleu_score': 0.017345617945636577,
  'context_recall': 1.0,
  'semantic_similarity': 0.812761523548346,
  'faithfulness': 0.9230769230769231,
  'factual_correctness(mode=f1)': np.float64(0.36)},
 {'bleu_score': 0.035792807886387674,
  'context_recall': 0.6,
  'semantic_similarity': 0.7515037801848061,
  'faithfulness': 0.7142857142857143,
  'factual_correctness(mode=f1)': np.float64(0.26)},
 {'bleu_score': 0.13706146326959748,
  'context_recall': 0.6666666666666666,
  'semantic_similarity': 0.8467752378943876,
  'faithfulness': 0.8333333333333334,
  'factual_correctness(mode=f1)': np.float64(0.17)},
 {'bleu_score': 0.07408590762781679,
  'context_recall': 0.75,
  'semantic_similarity': 0.7869956875306606,
  'faithfulness': 0.5555555555555556,
  'factual_correctness(mode=f1)': np.float64(0.17)},
 {'bleu_score': 0.01811080099375393,
  'context_recall': 0.0,
  'semantic_similarity': 0.23458085249108826,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.02544354209531657,
  'context_recall': 0.0,
  'semantic_similarity': 0.16188635197022017,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)},
 {'bleu_score': 0.054415030658658256,
  'context_recall': 0.16666666666666666,
  'semantic_similarity': 0.6949264556000637,
  'faithfulness': 0.8648648648648649,
  'factual_correctness(mode=f1)': np.float64(0.08)},
 {'bleu_score': 0.03527502360630139,
  'context_recall': 0.5,
  'semantic_similarity': 0.18119187728549563,
  'faithfulness': 0.0,
  'factual_correctness(mode=f1)': np.float64(0.0)}]

In [54]:
result.to_pandas()

,user_input,retrieved_contexts,response,reference,bleu_score,context_recall,semantic_similarity,faithfulness,factual_correctness(mode=f1)
0,"2022~2024년 삼성SDS의 매출 구성을 IT서비스와 물류 관점에서 비교하고, ...",[더욱 확대되고 있습니다. 특 히 IT서비스 산업은 고급인력 중심의 지식기반사업으로...,2022년부터 2024년까지 삼성SDS의 매출 구성은 IT서비스와 물류 부문에서 다...,공시자료에 따르면 전체 매출에서 IT서비스와 물류 비중은 2022년 34.6% 대 ...,0.029189,1.000000,0.776917,1.000000,0.45
1,"삼성SDS가 ‘클라우드 기업’으로 전환한다고 밝힌 바 있는 전략을, 제품·플랫폼·인...",[높입니다. 당사는 클라우드 기업으로의 전환을 위해 클라우드 기술력 강화와 전문인력...,"삼성SDS는 ‘클라우드 기업’으로의 전환 전략을 제품, 플랫폼, 인프라, 그리고 운...",제품·플랫폼 측면에서 회사는 SCP를 전개하며 CSP·MSP·SaaS를 End-to...,0.028848,0.800000,0.670085,0.944444,0.36
2,"물류 부문에서 삼성SDS가 디지털 포워딩 경쟁력을 어떻게 구축했는지, 플랫폼 진화와...",[한계에 직면하였습니 다. 이에 따라 최근 국내 IT서비스 업체는 자체 솔루션에 대...,물류 부문에서 삼성SDS는 Cello와 Cello Square라는 최신 IT기반의 ...,삼성SDS는 통합물류 플랫폼 Cello와 디지털 물류 플랫폼 Cello Square...,0.029809,1.000000,0.851090,0.933333,0.60
3,"회사가 서비스 가격표를 제시하지 않는 이유와 실제 가격 결정 방식은 무엇이며, 이는...",[데이터센터 인프라 서비 스 운영으로 구분할 수 있습니다. ① 애플리케이션 아웃소싱...,"회사가 서비스 가격표를 제시하지 않는 이유는, 고객의 상황과 요구사항에 따라 맞춤형...",공시자료는 IT서비스(SI·ITO·클라우드)와 물류가 개인용 규격 상품이 아니라 고...,0.023901,1.000000,0.755891,1.000000,0.72
4,"경기변동이 IT서비스와 물류에 미치는 영향과, 삼성SDS가 그 민감도를 낮추기 위해...","[및 방법 대화방에 초대받은 사용자가 대화방의 이전 대화 내역을 조회할 수 있으며,...",정보가 부족하여 답변할 수 없습니다.,"IT서비스는 기업 설비투자와 연동돼 경기 둔화 시 투자 보류 영향이 있으나, 클라우...",0.015330,1.000000,0.196655,0.000000,0.00
5,SRM 분야에서의 인수·출시 활동이 삼성SDS의 SaaS 전략과 글로벌 확장에 어떤...,"[(65.4%) 합계 6,616,222 (100.0%) 6,691,688 (100....",정보가 부족하여 답변할 수 없습니다.,회사는 2023년 2분기에 국내 1위 SRM 기업 엠로의 지분 인수를 완료해 핵심 ...,0.002451,1.000000,0.143968,0.000000,0.00
6,인력·시설·보안 측면에서 삼성SDS의 운영 기반과 이것이 서비스 신뢰성에 주는 함의...,[(홈페이지) http://www.samsungsds.com 작 성 책 임 자 : ...,"삼성SDS는 인력, 시설, 보안 측면에서 안정적이고 신뢰성 높은 운영 기반을 갖추고...","2024년 말 기준 연결 인력은 약 25,666명으로, IT서비스 16,798명, ...",0.074749,0.800000,0.803426,0.647059,0.65
7,"재무 안정성 측면에서 회사의 공시 내용을 종합하되, 상장 이력과 조달 구조까지 연결...",[목 차 반 기 보 고 서.1 【 대표이사 등의 확인 】.2 I. 회사의 개요.3 ...,정보가 부족하여 답변할 수 없습니다.,"삼성SDS는 2014년 11월 14일 유가증권시장에 상장했으며, 단기 조달 수단인 ...",0.012977,0.500000,0.152661,1.000000,0.00
8,삼성SDS의 2024년 3분기말(9월 30일) 연결 기준 부채비율을 재무상태표 수치...,"[814,126 818,854 712,749 ㆍ사용권자산 916,317 821,71...",삼성SDS의 2024년 3분기말(9월 30일) 연결 기준 부채비율은 다음과 같이 계...,"2024년 3분기말 연결 기준 부채총계는 3,409,626,256천원, 자본총계는 ...",0.012962,1.000000,0.700314,0.916667,0.26
9,2024년 3분기 누적과 2024 사업연도(사업보고서 기준)에서 삼성SDS의 희석주...,[따라 작성되었습니다. 나. 요약 별도재무정보 *삼성에스디에스 주식회사 매출액 10...,정보가 부족하여 답변할 수 없습니다.,삼성SDS는 당기 및 전기에 희석증권을 보유하지 않아 희석주당이익이 기본주당이익과 ...,0.007871,0.500000,0.144808,0.000000,0.00
10,"2024년 삼성SDS의 주식기준보상(엠로 포함) 현황을 수량, 행사가격, 만기, 비...",[내 (2) (주)엠로가 임직원에게 부여한 주식선택권의 수량과 변동내역은 다음과 같...,정보가 부족하여 답변할 수 없습니다.,연결실체 종속회사 (주)엠로의 주식매입선택권이 2024년 보고기간에 연결 주식기준보...,0.041673,0.666667,0.184480,0.000000,0.00
11,"온실가스 배출권과 배출부채에 대해, 2024년 중 배출권 수량·장부금액 변동과 기말...","[공정가치로 최초 측정하며, 당기손익인식항목으로 지정되거나 자산의 양도로 인해 발생...","온실가스 배출권과 배출부채에 대해, 2024년 중 배출권 수량과 장부금액의 변동은 ...","삼성SDS는 3차 계획기간(2021~2025년)에 대해 무상할당을 받고 있으며, 당...",0.117245,0.166667,0.645924,1.000000,0.20
12,"특수관계자와의 배당거래는 2024년에 어떻게 이루어졌으며, 연결 현금흐름에서의 배당...",[50 특수관계자와 관련된 사외적립자산의 이자수익 당분기 (단위 : 백만원) ...,"2024년 특수관계자와의 배당거래는 당분기(반기) 기준으로 수취 배당금이 664,8...","사업보고서 특수관계자 주석에 따르면, 2024년 중 특수관계자로부터 수취한 배당금은...",0.017346,1.000000,0.812762,0.923077,0.36
13,2024년 9월말까지 삼성SDS 연결 자본(지배주주지분)은 어떤 요인들로 증가·감소...,[다음과 같습니다. 이익잉여금 내역 당반기말 (단위 : 천원) 공시금액 법정...,2024년 9월말까지 삼성SDS 연결 자본(지배주주지분)은 다음과 같은 요인들로 인...,"지배주주지분은 2023.12.31의 8,658,009,435,402원에서 2024....",0.035793,0.600000,0.751504,0.714286,0.26
14,"2024년 3분기 누적 연구개발(R&D) 활동과 비용은 어떤 특징을 보였는지, 매출...",[기준입니다. ※ 비율은 정부보조금(국고보조금)을 차감하기 전의 연구개발비용 지출총...,2024년 3분기 누적 연구개발(R&D) 활동은 전반적으로 연구비용이 증가하는 추세...,"2024년 3분기 누적 연결 기준 연구개발비용 총계는 175,502,420천원이며,...",0.137061,0.666667,0.846775,0.833333,0.17
15,삼성SDS가 2024년 3분기 (주)동아미디어엔 보통주 18.01%만을 보유하면서도...,[현황은 다음과 같습니다. 구 분 회사명 당분기말 전기말 지분율(%) 종속기업 보유...,"공시자료에 따르면, 삼성SDS는 (주)동아미디어엔의 지분율이 18.01%로 낮음에도...",2024년 3분기 공시에 따르면 (주)동아미디어엔은 지분율이 20% 미만(18.01...,0.074086,0.750000,0.786996,0.555556,0.17
16,삼성SDS가 2024년 중 한국정보인증(주) 지분을 전량 처분한 사실이 연결재무제표...,[공모 - - - - - - - - 사모 - - - - - - - - 합계 - - ...,정보가 부족하여 답변할 수 없습니다.,관계기업투자주식 주석에 “한국정보인증(주) 당분기 중 전량 매각”이 명시되어 있으며...,0.018111,0.000000,0.234581,0.000000,0.00
17,만약 삼성SDS가 CMC Corporation(현재 유효지분율 약 29.83%)의 ...,"[Ltd. CMC Corporation 요약 재무상태표: 당기말 유동자산 21,02...",정보가 부족하여 답변할 수 없습니다.,"K-IFRS에 따르면 단계적 취득으로 지배력을 확보하는 경우, 기존에 보유하던 관계...",0.025444,0.000000,0.161886,0.000000,0.00
18,2024년 중 삼성SDS의 종속기업 지분 관련 변동을 별도·연결 재무제표 관점에서 ...,[분산되어 있는 점 등을 종합적으로 고려하여 실질적 지배력이 있는 것으로 판단하였습...,2024년 중 삼성SDS의 종속기업 지분 관련 변동을 별도·연결 재무제표 관점에서 ...,2024년에는 신규 사업결합이 없었습니다(연결 현금흐름표 ‘사업결합으로 인한 순현금...,0.054415,0.166667,0.694926,0.864865,0.08
19,"삼성SDS가 향후 종속회사와의 합병을 추진하는 경우, 사내 거버넌스와 주주총회 절차...",[목적을 달성하기 위하여 필요한 경우 가. 호 외의 방법으로 특정한 자(본 회사의 ...,정보가 부족하여 답변할 수 없습니다.,"회사 이사회 규정에 따르면 합병·분할·분할합병 등은 이사회 부의사항이며, 주주총회 ...",0.035275,0.500000,0.181192,0.000000,0.00

In [55]:
# dict로 변경하기(복잡..)
import ast

result_str = str(result)
result_dict = ast.literal_eval(result_str)
result_dict

{'bleu_score': 0.0397,
 'context_recall': 0.6558,
 'semantic_similarity': 0.5248,
 'faithfulness': 0.5666,
 'factual_correctness(mode=f1)': 0.214}

# [실습] 다양한 파이프라인 파라미터 수정하기

현재 파이프라인에는 매우 다양한 조절 가능한 파라미터가 있습니다.   

각각의 파라미터를 수정하여, 성능 변화를 확인해 보세요.

Ex)
- Chunk의 크기/개수 늘리기   
- 모델 더 저렴한 모델로 바꾸기   
-

In [63]:
MODEL_NAME='gpt-5'
TEMPERATURE=0
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K = 5

# CSV 파일 경로 설정
csv_path = "experiments/experiment_log.csv"
os.makedirs("experiments", exist_ok=True)


def RAG_pipeline():

    dataset = []

    llm = ChatOpenAI(model=MODEL_NAME, temperature = TEMPERATURE, max_tokens = 4096)
    Chroma().delete_collection() # 메모리 기존 데이터 삭제
    

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP)
    print('## DB 구성 중...')
    

    chunks = text_splitter.split_documents(all_papers)
    print(f'## Chunks 생성 완료... 총 {len(chunks)} 개 청크')




    db = Chroma(embedding_function=openai_embeddings,
                collection_metadata={'hnsw:space':'l2'},
                )
    for i in tqdm(range(0, len(chunks), 50)):
        db.add_documents(chunks[i:min(i+50, len(chunks))])

    print('## DB 구성 완료...')


    retriever = db.as_retriever(search_kwargs={'k':TOP_K})


    def format_docs(docs):
        return " \n---\n ".join([f'[출처]:{doc.metadata['source']}\n[내용]: {doc.page_content}\n' for doc in docs])
    
    rag_chain_from_docs = (
    prompt
    | llm
    | StrOutputParser()
    )


    rag_chain_with_ref = RunnableParallel(
        raw_context = retriever, question = RunnablePassthrough()
    ).assign(context = lambda x: format_docs(x['raw_context'])).assign(answer=rag_chain_from_docs)



    results = rag_chain_with_ref.batch(questions)

    dataset=[]

    for result, reference in tqdm(zip(results,ground_truths)):
        dataset.append(
            {
                "user_input":result['question'],
                "retrieved_contexts":[doc.page_content for doc in result['raw_context']],
                "response":result['answer'],
                "reference":reference
            }
        )    

    print('## 답변 생성 완료...')
    evaluation_dataset = EvaluationDataset.from_list(dataset)

    result = evaluate(dataset=evaluation_dataset,
                    metrics=[BleuScore(), LLMContextRecall(), semantic_scorer, Faithfulness(), FactualCorrectness()],
                    llm=evaluator_llm,
                    embeddings = evaluator_embeddings
                    )

    result_str = str(result)
    result_dict = ast.literal_eval(result_str)
    return result_dict

실험 시작 시간과 정보를 저장할 수 있습니다.

In [57]:
import csv
import datetime
import os
def run_experiment():
    result = RAG_pipeline()
    timestamp = datetime.datetime.now().isoformat()
    row = {
        "timestamp": timestamp,
        "model_name": MODEL_NAME,
        "temperature": TEMPERATURE,
        "chunk_size": CHUNK_SIZE,
        "chunk_overlap": CHUNK_OVERLAP,
        "top_k": TOP_K,
        **result
    }
    # 파일이 없으면 헤더 추가
    write_header = not os.path.exists(csv_path)

    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=row.keys())
        if write_header:
            writer.writeheader()
        writer.writerow(row)

    print(f"[{timestamp}] {MODEL_NAME} | temp={TEMPERATURE}, chunk={CHUNK_SIZE}/{CHUNK_OVERLAP}, top_k={TOP_K} | results={result}")

In [58]:
MODEL_NAME='gpt-4.1-nano'
TEMPERATURE=0
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K = 5

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 1337 개 청크

100%|██████████| 27/27 [00:56<00:00,  2.11s/it]

## DB 구성 완료...

20it [00:00, 128070.35it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:14:11.118123] gpt-4.1-nano | temp=0, chunk=1000/200, top_k=5 | results={'bleu_score': 0.055, 'context_recall': 0.5692, 'semantic_similarity': 0.5172, 'faithfulness': 0.5102, 'factual_correctness(mode=f1)': 0.253}

In [59]:
MODEL_NAME='gpt-4.1-nano'
TEMPERATURE=0
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K = 10

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 1337 개 청크

100%|██████████| 27/27 [00:51<00:00,  1.91s/it]

## DB 구성 완료...

20it [00:00, 122104.92it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:17:22.657510] gpt-4.1-nano | temp=0, chunk=1000/200, top_k=10 | results={'bleu_score': 0.0556, 'context_recall': 0.7483, 'semantic_similarity': 0.6135, 'faithfulness': 0.6623, 'factual_correctness(mode=f1)': 0.294}

In [60]:
MODEL_NAME='gpt-4.1-nano'
TEMPERATURE=0
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 400
TOP_K = 5

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 668 개 청크

100%|██████████| 14/14 [00:35<00:00,  2.52s/it]

## DB 구성 완료...

20it [00:00, 167437.29it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:19:49.027079] gpt-4.1-nano | temp=0, chunk=2000/400, top_k=5 | results={'bleu_score': 0.0421, 'context_recall': 0.6392, 'semantic_similarity': 0.5016, 'faithfulness': 0.4118, 'factual_correctness(mode=f1)': 0.208}

In [61]:
MODEL_NAME='gpt-4.1-nano'
TEMPERATURE=0
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 400
TOP_K = 10

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 668 개 청크

100%|██████████| 14/14 [00:40<00:00,  2.89s/it]

## DB 구성 완료...

20it [00:00, 125766.24it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:22:37.118243] gpt-4.1-nano | temp=0, chunk=2000/400, top_k=10 | results={'bleu_score': 0.0465, 'context_recall': 0.8475, 'semantic_similarity': 0.578, 'faithfulness': 0.6018, 'factual_correctness(mode=f1)': 0.316}

다양한 기법을 위 코드에서 적용하여 성능을 높일 수 있습니다.

In [62]:
MODEL_NAME='gpt-4.1-mini'
TEMPERATURE=0
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 400
TOP_K = 10

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 668 개 청크

100%|██████████| 14/14 [00:38<00:00,  2.74s/it]

## DB 구성 완료...

20it [00:00, 118650.75it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:28:18.083208] gpt-4.1-mini | temp=0, chunk=2000/400, top_k=10 | results={'bleu_score': 0.0593, 'context_recall': 0.8183, 'semantic_similarity': 0.7289, 'faithfulness': 0.9059, 'factual_correctness(mode=f1)': 0.429}

In [64]:
MODEL_NAME='gpt-5-mini'
TEMPERATURE=0
CHUNK_SIZE = 2000
CHUNK_OVERLAP = 400
TOP_K = 10

run_experiment()

## DB 구성 중...
## Chunks 생성 완료... 총 668 개 청크

100%|██████████| 14/14 [00:37<00:00,  2.68s/it]

## DB 구성 완료...

20it [00:00, 153076.79it/s]

## 답변 생성 완료...

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

[2025-08-30T15:34:36.372959] gpt-5-mini | temp=0, chunk=2000/400, top_k=10 | results={'bleu_score': 0.0325, 'context_recall': 0.8392, 'semantic_similarity': 0.6444, 'faithfulness': 0.8142, 'factual_correctness(mode=f1)': 0.443}